// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.biznetgio.biznetgio;

import com.biznetgio.biznetgio.Utilities;
import com.biznetgio.biznetgio.inputs.BaremetalOpenvpnArgs;
import com.biznetgio.biznetgio.inputs.BaremetalOpenvpnPlainArgs;
import com.biznetgio.biznetgio.inputs.BaremetalProductsArgs;
import com.biznetgio.biznetgio.inputs.BaremetalProductsPlainArgs;
import com.biznetgio.biznetgio.inputs.BaremetalRebuildOsListArgs;
import com.biznetgio.biznetgio.inputs.BaremetalRebuildOsListPlainArgs;
import com.biznetgio.biznetgio.inputs.GpuConsoleArgs;
import com.biznetgio.biznetgio.inputs.GpuConsolePlainArgs;
import com.biznetgio.biznetgio.inputs.GpuGraphArgs;
import com.biznetgio.biznetgio.inputs.GpuGraphPlainArgs;
import com.biznetgio.biznetgio.inputs.GpuProductsArgs;
import com.biznetgio.biznetgio.inputs.GpuProductsPlainArgs;
import com.biznetgio.biznetgio.inputs.NeoliteChangePackageOptionsArgs;
import com.biznetgio.biznetgio.inputs.NeoliteChangePackageOptionsPlainArgs;
import com.biznetgio.biznetgio.inputs.NeoliteIPAvailabilityArgs;
import com.biznetgio.biznetgio.inputs.NeoliteIPAvailabilityPlainArgs;
import com.biznetgio.biznetgio.inputs.NeoliteOsListArgs;
import com.biznetgio.biznetgio.inputs.NeoliteOsListPlainArgs;
import com.biznetgio.biznetgio.inputs.NeoliteProChangePackageOptionsArgs;
import com.biznetgio.biznetgio.inputs.NeoliteProChangePackageOptionsPlainArgs;
import com.biznetgio.biznetgio.inputs.NeoliteProIPAvailabilityArgs;
import com.biznetgio.biznetgio.inputs.NeoliteProIPAvailabilityPlainArgs;
import com.biznetgio.biznetgio.inputs.NeoliteProOsListArgs;
import com.biznetgio.biznetgio.inputs.NeoliteProOsListPlainArgs;
import com.biznetgio.biznetgio.inputs.NeoliteProProductsArgs;
import com.biznetgio.biznetgio.inputs.NeoliteProProductsPlainArgs;
import com.biznetgio.biznetgio.inputs.NeoliteProStorageUpgradeOptionsArgs;
import com.biznetgio.biznetgio.inputs.NeoliteProStorageUpgradeOptionsPlainArgs;
import com.biznetgio.biznetgio.inputs.NeoliteProductsArgs;
import com.biznetgio.biznetgio.inputs.NeoliteProductsPlainArgs;
import com.biznetgio.biznetgio.inputs.NeoliteStorageUpgradeOptionsArgs;
import com.biznetgio.biznetgio.inputs.NeoliteStorageUpgradeOptionsPlainArgs;
import com.biznetgio.biznetgio.inputs.ObjectStorageBucketsArgs;
import com.biznetgio.biznetgio.inputs.ObjectStorageBucketsPlainArgs;
import com.biznetgio.biznetgio.inputs.ObjectStorageCredentialsArgs;
import com.biznetgio.biznetgio.inputs.ObjectStorageCredentialsPlainArgs;
import com.biznetgio.biznetgio.inputs.ObjectStorageInstancesArgs;
import com.biznetgio.biznetgio.inputs.ObjectStorageInstancesPlainArgs;
import com.biznetgio.biznetgio.outputs.BaremetalOpenvpnResult;
import com.biznetgio.biznetgio.outputs.BaremetalProductsResult;
import com.biznetgio.biznetgio.outputs.BaremetalRebuildOsListResult;
import com.biznetgio.biznetgio.outputs.GpuConsoleResult;
import com.biznetgio.biznetgio.outputs.GpuGraphResult;
import com.biznetgio.biznetgio.outputs.GpuProductsResult;
import com.biznetgio.biznetgio.outputs.NeoliteChangePackageOptionsResult;
import com.biznetgio.biznetgio.outputs.NeoliteIPAvailabilityResult;
import com.biznetgio.biznetgio.outputs.NeoliteOsListResult;
import com.biznetgio.biznetgio.outputs.NeoliteProChangePackageOptionsResult;
import com.biznetgio.biznetgio.outputs.NeoliteProIPAvailabilityResult;
import com.biznetgio.biznetgio.outputs.NeoliteProOsListResult;
import com.biznetgio.biznetgio.outputs.NeoliteProProductsResult;
import com.biznetgio.biznetgio.outputs.NeoliteProStorageUpgradeOptionsResult;
import com.biznetgio.biznetgio.outputs.NeoliteProductsResult;
import com.biznetgio.biznetgio.outputs.NeoliteStorageUpgradeOptionsResult;
import com.biznetgio.biznetgio.outputs.ObjectStorageBucketsResult;
import com.biznetgio.biznetgio.outputs.ObjectStorageCredentialsResult;
import com.biznetgio.biznetgio.outputs.ObjectStorageInstancesResult;
import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import java.util.concurrent.CompletableFuture;

public final class BiznetgioFunctions {
    public static Output<BaremetalOpenvpnResult> baremetalOpenvpn() {
        return baremetalOpenvpn(BaremetalOpenvpnArgs.Empty, InvokeOptions.Empty);
    }
    public static CompletableFuture<BaremetalOpenvpnResult> baremetalOpenvpnPlain() {
        return baremetalOpenvpnPlain(BaremetalOpenvpnPlainArgs.Empty, InvokeOptions.Empty);
    }
    public static Output<BaremetalOpenvpnResult> baremetalOpenvpn(BaremetalOpenvpnArgs args) {
        return baremetalOpenvpn(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<BaremetalOpenvpnResult> baremetalOpenvpnPlain(BaremetalOpenvpnPlainArgs args) {
        return baremetalOpenvpnPlain(args, InvokeOptions.Empty);
    }
    public static Output<BaremetalOpenvpnResult> baremetalOpenvpn(BaremetalOpenvpnArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:baremetalOpenvpn", TypeShape.of(BaremetalOpenvpnResult.class), args, Utilities.withVersion(options));
    }
    public static Output<BaremetalOpenvpnResult> baremetalOpenvpn(BaremetalOpenvpnArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:baremetalOpenvpn", TypeShape.of(BaremetalOpenvpnResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<BaremetalOpenvpnResult> baremetalOpenvpnPlain(BaremetalOpenvpnPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:baremetalOpenvpn", TypeShape.of(BaremetalOpenvpnResult.class), args, Utilities.withVersion(options));
    }
    public static Output<BaremetalProductsResult> baremetalProducts() {
        return baremetalProducts(BaremetalProductsArgs.Empty, InvokeOptions.Empty);
    }
    public static CompletableFuture<BaremetalProductsResult> baremetalProductsPlain() {
        return baremetalProductsPlain(BaremetalProductsPlainArgs.Empty, InvokeOptions.Empty);
    }
    public static Output<BaremetalProductsResult> baremetalProducts(BaremetalProductsArgs args) {
        return baremetalProducts(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<BaremetalProductsResult> baremetalProductsPlain(BaremetalProductsPlainArgs args) {
        return baremetalProductsPlain(args, InvokeOptions.Empty);
    }
    public static Output<BaremetalProductsResult> baremetalProducts(BaremetalProductsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:baremetalProducts", TypeShape.of(BaremetalProductsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<BaremetalProductsResult> baremetalProducts(BaremetalProductsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:baremetalProducts", TypeShape.of(BaremetalProductsResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<BaremetalProductsResult> baremetalProductsPlain(BaremetalProductsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:baremetalProducts", TypeShape.of(BaremetalProductsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<BaremetalRebuildOsListResult> baremetalRebuildOsList(BaremetalRebuildOsListArgs args) {
        return baremetalRebuildOsList(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<BaremetalRebuildOsListResult> baremetalRebuildOsListPlain(BaremetalRebuildOsListPlainArgs args) {
        return baremetalRebuildOsListPlain(args, InvokeOptions.Empty);
    }
    public static Output<BaremetalRebuildOsListResult> baremetalRebuildOsList(BaremetalRebuildOsListArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:baremetalRebuildOsList", TypeShape.of(BaremetalRebuildOsListResult.class), args, Utilities.withVersion(options));
    }
    public static Output<BaremetalRebuildOsListResult> baremetalRebuildOsList(BaremetalRebuildOsListArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:baremetalRebuildOsList", TypeShape.of(BaremetalRebuildOsListResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<BaremetalRebuildOsListResult> baremetalRebuildOsListPlain(BaremetalRebuildOsListPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:baremetalRebuildOsList", TypeShape.of(BaremetalRebuildOsListResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GpuConsoleResult> gpuConsole(GpuConsoleArgs args) {
        return gpuConsole(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GpuConsoleResult> gpuConsolePlain(GpuConsolePlainArgs args) {
        return gpuConsolePlain(args, InvokeOptions.Empty);
    }
    public static Output<GpuConsoleResult> gpuConsole(GpuConsoleArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:gpuConsole", TypeShape.of(GpuConsoleResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GpuConsoleResult> gpuConsole(GpuConsoleArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:gpuConsole", TypeShape.of(GpuConsoleResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GpuConsoleResult> gpuConsolePlain(GpuConsolePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:gpuConsole", TypeShape.of(GpuConsoleResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GpuGraphResult> gpuGraph(GpuGraphArgs args) {
        return gpuGraph(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GpuGraphResult> gpuGraphPlain(GpuGraphPlainArgs args) {
        return gpuGraphPlain(args, InvokeOptions.Empty);
    }
    public static Output<GpuGraphResult> gpuGraph(GpuGraphArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:gpuGraph", TypeShape.of(GpuGraphResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GpuGraphResult> gpuGraph(GpuGraphArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:gpuGraph", TypeShape.of(GpuGraphResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GpuGraphResult> gpuGraphPlain(GpuGraphPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:gpuGraph", TypeShape.of(GpuGraphResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GpuProductsResult> gpuProducts() {
        return gpuProducts(GpuProductsArgs.Empty, InvokeOptions.Empty);
    }
    public static CompletableFuture<GpuProductsResult> gpuProductsPlain() {
        return gpuProductsPlain(GpuProductsPlainArgs.Empty, InvokeOptions.Empty);
    }
    public static Output<GpuProductsResult> gpuProducts(GpuProductsArgs args) {
        return gpuProducts(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GpuProductsResult> gpuProductsPlain(GpuProductsPlainArgs args) {
        return gpuProductsPlain(args, InvokeOptions.Empty);
    }
    public static Output<GpuProductsResult> gpuProducts(GpuProductsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:gpuProducts", TypeShape.of(GpuProductsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GpuProductsResult> gpuProducts(GpuProductsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:gpuProducts", TypeShape.of(GpuProductsResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GpuProductsResult> gpuProductsPlain(GpuProductsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:gpuProducts", TypeShape.of(GpuProductsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteChangePackageOptionsResult> neoliteChangePackageOptions(NeoliteChangePackageOptionsArgs args) {
        return neoliteChangePackageOptions(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<NeoliteChangePackageOptionsResult> neoliteChangePackageOptionsPlain(NeoliteChangePackageOptionsPlainArgs args) {
        return neoliteChangePackageOptionsPlain(args, InvokeOptions.Empty);
    }
    public static Output<NeoliteChangePackageOptionsResult> neoliteChangePackageOptions(NeoliteChangePackageOptionsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteChangePackageOptions", TypeShape.of(NeoliteChangePackageOptionsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteChangePackageOptionsResult> neoliteChangePackageOptions(NeoliteChangePackageOptionsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteChangePackageOptions", TypeShape.of(NeoliteChangePackageOptionsResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<NeoliteChangePackageOptionsResult> neoliteChangePackageOptionsPlain(NeoliteChangePackageOptionsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:neoliteChangePackageOptions", TypeShape.of(NeoliteChangePackageOptionsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteIPAvailabilityResult> neoliteIPAvailability(NeoliteIPAvailabilityArgs args) {
        return neoliteIPAvailability(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<NeoliteIPAvailabilityResult> neoliteIPAvailabilityPlain(NeoliteIPAvailabilityPlainArgs args) {
        return neoliteIPAvailabilityPlain(args, InvokeOptions.Empty);
    }
    public static Output<NeoliteIPAvailabilityResult> neoliteIPAvailability(NeoliteIPAvailabilityArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteIPAvailability", TypeShape.of(NeoliteIPAvailabilityResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteIPAvailabilityResult> neoliteIPAvailability(NeoliteIPAvailabilityArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteIPAvailability", TypeShape.of(NeoliteIPAvailabilityResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<NeoliteIPAvailabilityResult> neoliteIPAvailabilityPlain(NeoliteIPAvailabilityPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:neoliteIPAvailability", TypeShape.of(NeoliteIPAvailabilityResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteOsListResult> neoliteOsList(NeoliteOsListArgs args) {
        return neoliteOsList(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<NeoliteOsListResult> neoliteOsListPlain(NeoliteOsListPlainArgs args) {
        return neoliteOsListPlain(args, InvokeOptions.Empty);
    }
    public static Output<NeoliteOsListResult> neoliteOsList(NeoliteOsListArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteOsList", TypeShape.of(NeoliteOsListResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteOsListResult> neoliteOsList(NeoliteOsListArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteOsList", TypeShape.of(NeoliteOsListResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<NeoliteOsListResult> neoliteOsListPlain(NeoliteOsListPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:neoliteOsList", TypeShape.of(NeoliteOsListResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteProChangePackageOptionsResult> neoliteProChangePackageOptions(NeoliteProChangePackageOptionsArgs args) {
        return neoliteProChangePackageOptions(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<NeoliteProChangePackageOptionsResult> neoliteProChangePackageOptionsPlain(NeoliteProChangePackageOptionsPlainArgs args) {
        return neoliteProChangePackageOptionsPlain(args, InvokeOptions.Empty);
    }
    public static Output<NeoliteProChangePackageOptionsResult> neoliteProChangePackageOptions(NeoliteProChangePackageOptionsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteProChangePackageOptions", TypeShape.of(NeoliteProChangePackageOptionsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteProChangePackageOptionsResult> neoliteProChangePackageOptions(NeoliteProChangePackageOptionsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteProChangePackageOptions", TypeShape.of(NeoliteProChangePackageOptionsResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<NeoliteProChangePackageOptionsResult> neoliteProChangePackageOptionsPlain(NeoliteProChangePackageOptionsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:neoliteProChangePackageOptions", TypeShape.of(NeoliteProChangePackageOptionsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteProIPAvailabilityResult> neoliteProIPAvailability(NeoliteProIPAvailabilityArgs args) {
        return neoliteProIPAvailability(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<NeoliteProIPAvailabilityResult> neoliteProIPAvailabilityPlain(NeoliteProIPAvailabilityPlainArgs args) {
        return neoliteProIPAvailabilityPlain(args, InvokeOptions.Empty);
    }
    public static Output<NeoliteProIPAvailabilityResult> neoliteProIPAvailability(NeoliteProIPAvailabilityArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteProIPAvailability", TypeShape.of(NeoliteProIPAvailabilityResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteProIPAvailabilityResult> neoliteProIPAvailability(NeoliteProIPAvailabilityArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteProIPAvailability", TypeShape.of(NeoliteProIPAvailabilityResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<NeoliteProIPAvailabilityResult> neoliteProIPAvailabilityPlain(NeoliteProIPAvailabilityPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:neoliteProIPAvailability", TypeShape.of(NeoliteProIPAvailabilityResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteProOsListResult> neoliteProOsList(NeoliteProOsListArgs args) {
        return neoliteProOsList(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<NeoliteProOsListResult> neoliteProOsListPlain(NeoliteProOsListPlainArgs args) {
        return neoliteProOsListPlain(args, InvokeOptions.Empty);
    }
    public static Output<NeoliteProOsListResult> neoliteProOsList(NeoliteProOsListArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteProOsList", TypeShape.of(NeoliteProOsListResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteProOsListResult> neoliteProOsList(NeoliteProOsListArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteProOsList", TypeShape.of(NeoliteProOsListResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<NeoliteProOsListResult> neoliteProOsListPlain(NeoliteProOsListPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:neoliteProOsList", TypeShape.of(NeoliteProOsListResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteProProductsResult> neoliteProProducts() {
        return neoliteProProducts(NeoliteProProductsArgs.Empty, InvokeOptions.Empty);
    }
    public static CompletableFuture<NeoliteProProductsResult> neoliteProProductsPlain() {
        return neoliteProProductsPlain(NeoliteProProductsPlainArgs.Empty, InvokeOptions.Empty);
    }
    public static Output<NeoliteProProductsResult> neoliteProProducts(NeoliteProProductsArgs args) {
        return neoliteProProducts(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<NeoliteProProductsResult> neoliteProProductsPlain(NeoliteProProductsPlainArgs args) {
        return neoliteProProductsPlain(args, InvokeOptions.Empty);
    }
    public static Output<NeoliteProProductsResult> neoliteProProducts(NeoliteProProductsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteProProducts", TypeShape.of(NeoliteProProductsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteProProductsResult> neoliteProProducts(NeoliteProProductsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteProProducts", TypeShape.of(NeoliteProProductsResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<NeoliteProProductsResult> neoliteProProductsPlain(NeoliteProProductsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:neoliteProProducts", TypeShape.of(NeoliteProProductsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteProStorageUpgradeOptionsResult> neoliteProStorageUpgradeOptions(NeoliteProStorageUpgradeOptionsArgs args) {
        return neoliteProStorageUpgradeOptions(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<NeoliteProStorageUpgradeOptionsResult> neoliteProStorageUpgradeOptionsPlain(NeoliteProStorageUpgradeOptionsPlainArgs args) {
        return neoliteProStorageUpgradeOptionsPlain(args, InvokeOptions.Empty);
    }
    public static Output<NeoliteProStorageUpgradeOptionsResult> neoliteProStorageUpgradeOptions(NeoliteProStorageUpgradeOptionsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteProStorageUpgradeOptions", TypeShape.of(NeoliteProStorageUpgradeOptionsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteProStorageUpgradeOptionsResult> neoliteProStorageUpgradeOptions(NeoliteProStorageUpgradeOptionsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteProStorageUpgradeOptions", TypeShape.of(NeoliteProStorageUpgradeOptionsResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<NeoliteProStorageUpgradeOptionsResult> neoliteProStorageUpgradeOptionsPlain(NeoliteProStorageUpgradeOptionsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:neoliteProStorageUpgradeOptions", TypeShape.of(NeoliteProStorageUpgradeOptionsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteProductsResult> neoliteProducts() {
        return neoliteProducts(NeoliteProductsArgs.Empty, InvokeOptions.Empty);
    }
    public static CompletableFuture<NeoliteProductsResult> neoliteProductsPlain() {
        return neoliteProductsPlain(NeoliteProductsPlainArgs.Empty, InvokeOptions.Empty);
    }
    public static Output<NeoliteProductsResult> neoliteProducts(NeoliteProductsArgs args) {
        return neoliteProducts(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<NeoliteProductsResult> neoliteProductsPlain(NeoliteProductsPlainArgs args) {
        return neoliteProductsPlain(args, InvokeOptions.Empty);
    }
    public static Output<NeoliteProductsResult> neoliteProducts(NeoliteProductsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteProducts", TypeShape.of(NeoliteProductsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteProductsResult> neoliteProducts(NeoliteProductsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteProducts", TypeShape.of(NeoliteProductsResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<NeoliteProductsResult> neoliteProductsPlain(NeoliteProductsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:neoliteProducts", TypeShape.of(NeoliteProductsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteStorageUpgradeOptionsResult> neoliteStorageUpgradeOptions(NeoliteStorageUpgradeOptionsArgs args) {
        return neoliteStorageUpgradeOptions(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<NeoliteStorageUpgradeOptionsResult> neoliteStorageUpgradeOptionsPlain(NeoliteStorageUpgradeOptionsPlainArgs args) {
        return neoliteStorageUpgradeOptionsPlain(args, InvokeOptions.Empty);
    }
    public static Output<NeoliteStorageUpgradeOptionsResult> neoliteStorageUpgradeOptions(NeoliteStorageUpgradeOptionsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteStorageUpgradeOptions", TypeShape.of(NeoliteStorageUpgradeOptionsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<NeoliteStorageUpgradeOptionsResult> neoliteStorageUpgradeOptions(NeoliteStorageUpgradeOptionsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:neoliteStorageUpgradeOptions", TypeShape.of(NeoliteStorageUpgradeOptionsResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<NeoliteStorageUpgradeOptionsResult> neoliteStorageUpgradeOptionsPlain(NeoliteStorageUpgradeOptionsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:neoliteStorageUpgradeOptions", TypeShape.of(NeoliteStorageUpgradeOptionsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<ObjectStorageBucketsResult> objectStorageBuckets(ObjectStorageBucketsArgs args) {
        return objectStorageBuckets(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<ObjectStorageBucketsResult> objectStorageBucketsPlain(ObjectStorageBucketsPlainArgs args) {
        return objectStorageBucketsPlain(args, InvokeOptions.Empty);
    }
    public static Output<ObjectStorageBucketsResult> objectStorageBuckets(ObjectStorageBucketsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:objectStorageBuckets", TypeShape.of(ObjectStorageBucketsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<ObjectStorageBucketsResult> objectStorageBuckets(ObjectStorageBucketsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:objectStorageBuckets", TypeShape.of(ObjectStorageBucketsResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<ObjectStorageBucketsResult> objectStorageBucketsPlain(ObjectStorageBucketsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:objectStorageBuckets", TypeShape.of(ObjectStorageBucketsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<ObjectStorageCredentialsResult> objectStorageCredentials(ObjectStorageCredentialsArgs args) {
        return objectStorageCredentials(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<ObjectStorageCredentialsResult> objectStorageCredentialsPlain(ObjectStorageCredentialsPlainArgs args) {
        return objectStorageCredentialsPlain(args, InvokeOptions.Empty);
    }
    public static Output<ObjectStorageCredentialsResult> objectStorageCredentials(ObjectStorageCredentialsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:objectStorageCredentials", TypeShape.of(ObjectStorageCredentialsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<ObjectStorageCredentialsResult> objectStorageCredentials(ObjectStorageCredentialsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:objectStorageCredentials", TypeShape.of(ObjectStorageCredentialsResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<ObjectStorageCredentialsResult> objectStorageCredentialsPlain(ObjectStorageCredentialsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:objectStorageCredentials", TypeShape.of(ObjectStorageCredentialsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<ObjectStorageInstancesResult> objectStorageInstances() {
        return objectStorageInstances(ObjectStorageInstancesArgs.Empty, InvokeOptions.Empty);
    }
    public static CompletableFuture<ObjectStorageInstancesResult> objectStorageInstancesPlain() {
        return objectStorageInstancesPlain(ObjectStorageInstancesPlainArgs.Empty, InvokeOptions.Empty);
    }
    public static Output<ObjectStorageInstancesResult> objectStorageInstances(ObjectStorageInstancesArgs args) {
        return objectStorageInstances(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<ObjectStorageInstancesResult> objectStorageInstancesPlain(ObjectStorageInstancesPlainArgs args) {
        return objectStorageInstancesPlain(args, InvokeOptions.Empty);
    }
    public static Output<ObjectStorageInstancesResult> objectStorageInstances(ObjectStorageInstancesArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:objectStorageInstances", TypeShape.of(ObjectStorageInstancesResult.class), args, Utilities.withVersion(options));
    }
    public static Output<ObjectStorageInstancesResult> objectStorageInstances(ObjectStorageInstancesArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("biznetgio:index:objectStorageInstances", TypeShape.of(ObjectStorageInstancesResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<ObjectStorageInstancesResult> objectStorageInstancesPlain(ObjectStorageInstancesPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("biznetgio:index:objectStorageInstances", TypeShape.of(ObjectStorageInstancesResult.class), args, Utilities.withVersion(options));
    }
}
// wip 327
