// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.biznetgio.biznetgio;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GpuKeypairArgs extends com.pulumi.resources.ResourceArgs {

    public static final GpuKeypairArgs Empty = new GpuKeypairArgs();

    /**
     * Name of the keypair. Create-only, changing it replaces the keypair.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Name of the keypair. Create-only, changing it replaces the keypair.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    private GpuKeypairArgs() {}

    private GpuKeypairArgs(GpuKeypairArgs $) {
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GpuKeypairArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GpuKeypairArgs $;

        public Builder() {
            $ = new GpuKeypairArgs();
        }

        public Builder(GpuKeypairArgs defaults) {
            $ = new GpuKeypairArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name Name of the keypair. Create-only, changing it replaces the keypair.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of the keypair. Create-only, changing it replaces the keypair.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public GpuKeypairArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GpuKeypairArgs", "name");
            }
            return $;
        }
    }

}
