// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.biznetgio.biznetgio;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class NeoliteKeypairArgs extends com.pulumi.resources.ResourceArgs {

    public static final NeoliteKeypairArgs Empty = new NeoliteKeypairArgs();

    /**
     * Nama keypair.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Nama keypair.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    private NeoliteKeypairArgs() {}

    private NeoliteKeypairArgs(NeoliteKeypairArgs $) {
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NeoliteKeypairArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NeoliteKeypairArgs $;

        public Builder() {
            $ = new NeoliteKeypairArgs();
        }

        public Builder(NeoliteKeypairArgs defaults) {
            $ = new NeoliteKeypairArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name Nama keypair.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Nama keypair.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public NeoliteKeypairArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("NeoliteKeypairArgs", "name");
            }
            return $;
        }
    }

}
