// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.biznetgio.biznetgio;

import com.biznetgio.biznetgio.NeoliteVmArgs;
import com.biznetgio.biznetgio.Utilities;
import com.biznetgio.biznetgio.outputs.NeoliteLastInvoice;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="biznetgio:index:NeoliteVm")
public class NeoliteVm extends com.pulumi.resources.CustomResource {
    /**
     * Siklus billing aktif.
     * 
     */
    @Export(name="billingcycle", refs={String.class}, tree="[0]")
    private Output<String> billingcycle;

    /**
     * @return Siklus billing aktif.
     * 
     */
    public Output<String> billingcycle() {
        return this.billingcycle;
    }
    /**
     * Cloud-init password VM (sensitive).
     * 
     */
    @Export(name="ciPassword", refs={String.class}, tree="[0]")
    private Output<String> ciPassword;

    /**
     * @return Cloud-init password VM (sensitive).
     * 
     */
    public Output<String> ciPassword() {
        return this.ciPassword;
    }
    /**
     * Cloud-init user VM.
     * 
     */
    @Export(name="ciUser", refs={String.class}, tree="[0]")
    private Output<String> ciUser;

    /**
     * @return Cloud-init user VM.
     * 
     */
    public Output<String> ciUser() {
        return this.ciUser;
    }
    /**
     * Password console saat create. Write-only: ga pernah di-refetch dari API.
     * 
     */
    @Export(name="consolePassword", refs={String.class}, tree="[0]")
    private Output<String> consolePassword;

    /**
     * @return Password console saat create. Write-only: ga pernah di-refetch dari API.
     * 
     */
    public Output<String> consolePassword() {
        return this.consolePassword;
    }
    /**
     * Jumlah CPU VM.
     * 
     */
    @Export(name="cpus", refs={Integer.class}, tree="[0]")
    private Output<Integer> cpus;

    /**
     * @return Jumlah CPU VM.
     * 
     */
    public Output<Integer> cpus() {
        return this.cpus;
    }
    /**
     * Siklus billing: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
     * 
     */
    @Export(name="cycle", refs={String.class}, tree="[0]")
    private Output<String> cycle;

    /**
     * @return Siklus billing: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
     * 
     */
    public Output<String> cycle() {
        return this.cycle;
    }
    /**
     * Deskripsi VM.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return Deskripsi VM.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * Ukuran disk target (GB, absolute — bukan tambahan). Cuma bisa naik, bukan turun.
     * 
     */
    @Export(name="diskSize", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> diskSize;

    /**
     * @return Ukuran disk target (GB, absolute — bukan tambahan). Cuma bisa naik, bukan turun.
     * 
     */
    public Output<Optional<Integer>> diskSize() {
        return Codegen.optional(this.diskSize);
    }
    /**
     * Id keypair dari `NeoliteKeypair`. Bisa diganti via change-keypair.
     * 
     */
    @Export(name="keypairId", refs={Integer.class}, tree="[0]")
    private Output<Integer> keypairId;

    /**
     * @return Id keypair dari `NeoliteKeypair`. Bisa diganti via change-keypair.
     * 
     */
    public Output<Integer> keypairId() {
        return this.keypairId;
    }
    /**
     * Invoice terakhir VM.
     * 
     */
    @Export(name="lastInvoice", refs={NeoliteLastInvoice.class}, tree="[0]")
    private Output<NeoliteLastInvoice> lastInvoice;

    /**
     * @return Invoice terakhir VM.
     * 
     */
    public Output<NeoliteLastInvoice> lastInvoice() {
        return this.lastInvoice;
    }
    /**
     * Ukuran disk maksimal VM (GB).
     * 
     */
    @Export(name="maxDisk", refs={Integer.class}, tree="[0]")
    private Output<Integer> maxDisk;

    /**
     * @return Ukuran disk maksimal VM (GB).
     * 
     */
    public Output<Integer> maxDisk() {
        return this.maxDisk;
    }
    /**
     * Memory maksimal VM (MB).
     * 
     */
    @Export(name="maxMem", refs={Integer.class}, tree="[0]")
    private Output<Integer> maxMem;

    /**
     * @return Memory maksimal VM (MB).
     * 
     */
    public Output<Integer> maxMem() {
        return this.maxMem;
    }
    /**
     * Memory yang dipakai VM (MB).
     * 
     */
    @Export(name="mem", refs={Integer.class}, tree="[0]")
    private Output<Integer> mem;

    /**
     * @return Memory yang dipakai VM (MB).
     * 
     */
    public Output<Integer> mem() {
        return this.mem;
    }
    /**
     * Trigger one-shot migrate ke NEO Lite Pro: isi neolitepro_product_id target. Ganti nilainya buat re-trigger.
     * 
     */
    @Export(name="migrateToPro", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> migrateToPro;

    /**
     * @return Trigger one-shot migrate ke NEO Lite Pro: isi neolitepro_product_id target. Ganti nilainya buat re-trigger.
     * 
     */
    public Output<Optional<String>> migrateToPro() {
        return Codegen.optional(this.migrateToPro);
    }
    /**
     * Tanggal tagihan berikutnya.
     * 
     */
    @Export(name="nextDue", refs={String.class}, tree="[0]")
    private Output<String> nextDue;

    /**
     * @return Tanggal tagihan berikutnya.
     * 
     */
    public Output<String> nextDue() {
        return this.nextDue;
    }
    /**
     * Order id dari response create.
     * 
     */
    @Export(name="orderId", refs={String.class}, tree="[0]")
    private Output<String> orderId;

    /**
     * @return Order id dari response create.
     * 
     */
    public Output<String> orderId() {
        return this.orderId;
    }
    /**
     * Nama OS yang jalan di VM.
     * 
     */
    @Export(name="osName", refs={String.class}, tree="[0]")
    private Output<String> osName;

    /**
     * @return Nama OS yang jalan di VM.
     * 
     */
    public Output<String> osName() {
        return this.osName;
    }
    /**
     * Bayar invoice pake kartu kredit saat order. Default true (auto-charge). Set false kalau mau ninggalin invoice unpaid di portal — resource bakal stuck Pending sampai dibayar.
     * 
     */
    @Export(name="payWithCreditCard", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> payWithCreditCard;

    /**
     * @return Bayar invoice pake kartu kredit saat order. Default true (auto-charge). Set false kalau mau ninggalin invoice unpaid di portal — resource bakal stuck Pending sampai dibayar.
     * 
     */
    public Output<Optional<Boolean>> payWithCreditCard() {
        return Codegen.optional(this.payWithCreditCard);
    }
    /**
     * Power state VM: start, stop, suspend, resume, atau shutdown. Update cuma mengirim action kalau nilainya berubah.
     * 
     */
    @Export(name="powerState", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> powerState;

    /**
     * @return Power state VM: start, stop, suspend, resume, atau shutdown. Update cuma mengirim action kalau nilainya berubah.
     * 
     */
    public Output<Optional<String>> powerState() {
        return Codegen.optional(this.powerState);
    }
    /**
     * Product id dari function `getProducts` atau portal.
     * 
     */
    @Export(name="productId", refs={Integer.class}, tree="[0]")
    private Output<Integer> productId;

    /**
     * @return Product id dari function `getProducts` atau portal.
     * 
     */
    public Output<Integer> productId() {
        return this.productId;
    }
    /**
     * Nama product aktif.
     * 
     */
    @Export(name="productName", refs={String.class}, tree="[0]")
    private Output<String> productName;

    /**
     * @return Nama product aktif.
     * 
     */
    public Output<String> productName() {
        return this.productName;
    }
    /**
     * Kode promo saat order.
     * 
     */
    @Export(name="promocode", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> promocode;

    /**
     * @return Kode promo saat order.
     * 
     */
    public Output<Optional<String>> promocode() {
        return Codegen.optional(this.promocode);
    }
    /**
     * Full JSON response akun terakhir dari API, buat akses field yang belum dimodel (cipassword di-mask).
     * 
     */
    @Export(name="raw", refs={String.class}, tree="[0]")
    private Output<String> raw;

    /**
     * @return Full JSON response akun terakhir dari API, buat akses field yang belum dimodel (cipassword di-mask).
     * 
     */
    public Output<String> raw() {
        return this.raw;
    }
    /**
     * Kalau berubah, VM di-rebuild (wipe OS) pake OS baru via endpoint rebuild. List OS valid ada di function `getOsList`.
     * 
     */
    @Export(name="rebuildOs", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> rebuildOs;

    /**
     * @return Kalau berubah, VM di-rebuild (wipe OS) pake OS baru via endpoint rebuild. List OS valid ada di function `getOsList`.
     * 
     */
    public Output<Optional<String>> rebuildOs() {
        return Codegen.optional(this.rebuildOs);
    }
    /**
     * Nominal recurring per siklus.
     * 
     */
    @Export(name="recurringAmount", refs={Integer.class}, tree="[0]")
    private Output<Integer> recurringAmount;

    /**
     * @return Nominal recurring per siklus.
     * 
     */
    public Output<Integer> recurringAmount() {
        return this.recurringAmount;
    }
    /**
     * Region VM.
     * 
     */
    @Export(name="region", refs={String.class}, tree="[0]")
    private Output<String> region;

    /**
     * @return Region VM.
     * 
     */
    public Output<String> region() {
        return this.region;
    }
    /**
     * Label region VM.
     * 
     */
    @Export(name="regionLabel", refs={String.class}, tree="[0]")
    private Output<String> regionLabel;

    /**
     * @return Label region VM.
     * 
     */
    public Output<String> regionLabel() {
        return this.regionLabel;
    }
    /**
     * OS yang dipasang saat create, dari function `getOsList`. Ganti OS = pakai `rebuildOs`.
     * 
     */
    @Export(name="selectOs", refs={String.class}, tree="[0]")
    private Output<String> selectOs;

    /**
     * @return OS yang dipasang saat create, dari function `getOsList`. Ganti OS = pakai `rebuildOs`.
     * 
     */
    public Output<String> selectOs() {
        return this.selectOs;
    }
    /**
     * User SSH &amp; console yang dipasang saat create.
     * 
     */
    @Export(name="sshAndConsoleUser", refs={String.class}, tree="[0]")
    private Output<String> sshAndConsoleUser;

    /**
     * @return User SSH &amp; console yang dipasang saat create.
     * 
     */
    public Output<String> sshAndConsoleUser() {
        return this.sshAndConsoleUser;
    }
    /**
     * Status akun terakhir dari API (Active, Pending, Suspended, Terminated).
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    /**
     * @return Status akun terakhir dari API (Active, Pending, Suspended, Terminated).
     * 
     */
    public Output<String> status() {
        return this.status;
    }
    /**
     * Uptime VM dalam detik.
     * 
     */
    @Export(name="uptime", refs={Integer.class}, tree="[0]")
    private Output<Integer> uptime;

    /**
     * @return Uptime VM dalam detik.
     * 
     */
    public Output<Integer> uptime() {
        return this.uptime;
    }
    /**
     * Nama VM. Default `server-name`. Bisa diubah via change-vm-name.
     * 
     */
    @Export(name="vmName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> vmName;

    /**
     * @return Nama VM. Default `server-name`. Bisa diubah via change-vm-name.
     * 
     */
    public Output<Optional<String>> vmName() {
        return Codegen.optional(this.vmName);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public NeoliteVm(java.lang.String name) {
        this(name, NeoliteVmArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public NeoliteVm(java.lang.String name, NeoliteVmArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public NeoliteVm(java.lang.String name, NeoliteVmArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("biznetgio:index:NeoliteVm", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private NeoliteVm(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("biznetgio:index:NeoliteVm", name, null, makeResourceOptions(options, id), false);
    }

    private static NeoliteVmArgs makeArgs(NeoliteVmArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? NeoliteVmArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "ciPassword",
                "consolePassword",
                "raw"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static NeoliteVm get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new NeoliteVm(name, id, options);
    }
}
