// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.biznetgio.biznetgio.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;


public final class NeoliteProChangePackageOptionsArgs extends com.pulumi.resources.InvokeArgs {

    public static final NeoliteProChangePackageOptionsArgs Empty = new NeoliteProChangePackageOptionsArgs();

    /**
     * Account id VM NEO Lite Pro.
     * 
     */
    @Import(name="accountId", required=true)
    private Output<Integer> accountId;

    /**
     * @return Account id VM NEO Lite Pro.
     * 
     */
    public Output<Integer> accountId() {
        return this.accountId;
    }

    private NeoliteProChangePackageOptionsArgs() {}

    private NeoliteProChangePackageOptionsArgs(NeoliteProChangePackageOptionsArgs $) {
        this.accountId = $.accountId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NeoliteProChangePackageOptionsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NeoliteProChangePackageOptionsArgs $;

        public Builder() {
            $ = new NeoliteProChangePackageOptionsArgs();
        }

        public Builder(NeoliteProChangePackageOptionsArgs defaults) {
            $ = new NeoliteProChangePackageOptionsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accountId Account id VM NEO Lite Pro.
         * 
         * @return builder
         * 
         */
        public Builder accountId(Output<Integer> accountId) {
            $.accountId = accountId;
            return this;
        }

        /**
         * @param accountId Account id VM NEO Lite Pro.
         * 
         * @return builder
         * 
         */
        public Builder accountId(Integer accountId) {
            return accountId(Output.of(accountId));
        }

        public NeoliteProChangePackageOptionsArgs build() {
            if ($.accountId == null) {
                throw new MissingRequiredPropertyException("NeoliteProChangePackageOptionsArgs", "accountId");
            }
            return $;
        }
    }

}
