// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio.ren.shirasaka_biznetgio.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;


public final class NeoliteOsListPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final NeoliteOsListPlainArgs Empty = new NeoliteOsListPlainArgs();

    /**
     * Product id NEO Lite.
     * 
     */
    @Import(name="productId", required=true)
    private Integer productId;

    /**
     * @return Product id NEO Lite.
     * 
     */
    public Integer productId() {
        return this.productId;
    }

    private NeoliteOsListPlainArgs() {}

    private NeoliteOsListPlainArgs(NeoliteOsListPlainArgs $) {
        this.productId = $.productId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NeoliteOsListPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NeoliteOsListPlainArgs $;

        public Builder() {
            $ = new NeoliteOsListPlainArgs();
        }

        public Builder(NeoliteOsListPlainArgs defaults) {
            $ = new NeoliteOsListPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param productId Product id NEO Lite.
         * 
         * @return builder
         * 
         */
        public Builder productId(Integer productId) {
            $.productId = productId;
            return this;
        }

        public NeoliteOsListPlainArgs build() {
            if ($.productId == null) {
                throw new MissingRequiredPropertyException("NeoliteOsListPlainArgs", "productId");
            }
            return $;
        }
    }

}
