// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio.ren.shirasaka_biznetgio.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;


public final class NeoliteStorageUpgradeOptionsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final NeoliteStorageUpgradeOptionsPlainArgs Empty = new NeoliteStorageUpgradeOptionsPlainArgs();

    /**
     * Account id VM NEO Lite.
     * 
     */
    @Import(name="accountId", required=true)
    private Integer accountId;

    /**
     * @return Account id VM NEO Lite.
     * 
     */
    public Integer accountId() {
        return this.accountId;
    }

    private NeoliteStorageUpgradeOptionsPlainArgs() {}

    private NeoliteStorageUpgradeOptionsPlainArgs(NeoliteStorageUpgradeOptionsPlainArgs $) {
        this.accountId = $.accountId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NeoliteStorageUpgradeOptionsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NeoliteStorageUpgradeOptionsPlainArgs $;

        public Builder() {
            $ = new NeoliteStorageUpgradeOptionsPlainArgs();
        }

        public Builder(NeoliteStorageUpgradeOptionsPlainArgs defaults) {
            $ = new NeoliteStorageUpgradeOptionsPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accountId Account id VM NEO Lite.
         * 
         * @return builder
         * 
         */
        public Builder accountId(Integer accountId) {
            $.accountId = accountId;
            return this;
        }

        public NeoliteStorageUpgradeOptionsPlainArgs build() {
            if ($.accountId == null) {
                throw new MissingRequiredPropertyException("NeoliteStorageUpgradeOptionsPlainArgs", "accountId");
            }
            return $;
        }
    }

}
