// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Shirasakaren.Biznetgio
{
    public static class BaremetalOpenvpn
    {
        public static Task<BaremetalOpenvpnResult> InvokeAsync(BaremetalOpenvpnArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<BaremetalOpenvpnResult>("biznetgio:index:baremetalOpenvpn", args ?? new BaremetalOpenvpnArgs(), options.WithDefaults());

        public static Output<BaremetalOpenvpnResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<BaremetalOpenvpnResult>("biznetgio:index:baremetalOpenvpn", InvokeArgs.Empty, options.WithDefaults());

        public static Output<BaremetalOpenvpnResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<BaremetalOpenvpnResult>("biznetgio:index:baremetalOpenvpn", InvokeArgs.Empty, options.WithDefaults());
    }


    public sealed class BaremetalOpenvpnArgs : global::Pulumi.InvokeArgs
    {
        public BaremetalOpenvpnArgs()
        {
        }
        public static new BaremetalOpenvpnArgs Empty => new BaremetalOpenvpnArgs();
    }


    [OutputType]
    public sealed class BaremetalOpenvpnResult
    {
        /// <summary>
        /// OpenVPN client config from `GET /baremetals/openvpn`.
        /// </summary>
        public readonly string Config;
        /// <summary>
        /// Raw JSON of the full response.
        /// </summary>
        public readonly string Raw;

        [OutputConstructor]
        private BaremetalOpenvpnResult(
            string config,

            string raw)
        {
            Config = config;
            Raw = raw;
        }
    }
}
