// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Biznetgio.Biznetgio
{
    [BiznetgioResourceType("biznetgio:index:BaremetalElasticStorage")]
    public partial class BaremetalElasticStorage : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Creation timestamp (alias of created_at/date_created).
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Billing cycle, e.g. `m` for monthly or `a` for annual. Create-only, changing it replaces the storage.
        /// </summary>
        [Output("cycle")]
        public Output<string> Cycle { get; private set; } = null!;

        /// <summary>
        /// Account id of the target baremetal. Can only be set at creation (no re-attach endpoint).
        /// </summary>
        [Output("metalAccountId")]
        public Output<int> MetalAccountId { get; private set; } = null!;

        /// <summary>
        /// Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
        /// </summary>
        [Output("payWithCreditCard")]
        public Output<bool?> PayWithCreditCard { get; private set; } = null!;

        /// <summary>
        /// Product id from `GET /baremetal-neo-elastic-storages/products`. Changing it triggers change-package (`POST .../{account_id}`).
        /// </summary>
        [Output("productId")]
        public Output<int> ProductId { get; private set; } = null!;

        /// <summary>
        /// Promo code to apply at creation.
        /// </summary>
        [Output("promocode")]
        public Output<string?> Promocode { get; private set; } = null!;

        /// <summary>
        /// Raw JSON of the last read response, for anything not modeled yet.
        /// </summary>
        [Output("raw")]
        public Output<string> Raw { get; private set; } = null!;

        /// <summary>
        /// Storage size in GB. Defaults to 100. Changing it triggers upgrade (`PUT .../{account_id}`) — grow-only, shrinking is rejected by the API.
        /// </summary>
        [Output("size")]
        public Output<int?> Size { get; private set; } = null!;

        /// <summary>
        /// Current status of the storage (e.g. Active, Pending, Suspended, Terminated).
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// Name of the storage. Create-only, changing it replaces the storage.
        /// </summary>
        [Output("storageName")]
        public Output<string> StorageName { get; private set; } = null!;


        /// <summary>
        /// Create a BaremetalElasticStorage resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public BaremetalElasticStorage(string name, BaremetalElasticStorageArgs args, CustomResourceOptions? options = null)
            : base("biznetgio:index:BaremetalElasticStorage", name, args ?? new BaremetalElasticStorageArgs(), MakeResourceOptions(options, ""))
        {
        }

        private BaremetalElasticStorage(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("biznetgio:index:BaremetalElasticStorage", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "raw",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing BaremetalElasticStorage resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static BaremetalElasticStorage Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new BaremetalElasticStorage(name, id, options);
        }
    }

    public sealed class BaremetalElasticStorageArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Billing cycle, e.g. `m` for monthly or `a` for annual. Create-only, changing it replaces the storage.
        /// </summary>
        [Input("cycle", required: true)]
        public Input<string> Cycle { get; set; } = null!;

        /// <summary>
        /// Account id of the target baremetal. Can only be set at creation (no re-attach endpoint).
        /// </summary>
        [Input("metalAccountId", required: true)]
        public Input<int> MetalAccountId { get; set; } = null!;

        /// <summary>
        /// Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
        /// </summary>
        [Input("payWithCreditCard")]
        public Input<bool>? PayWithCreditCard { get; set; }

        /// <summary>
        /// Product id from `GET /baremetal-neo-elastic-storages/products`. Changing it triggers change-package (`POST .../{account_id}`).
        /// </summary>
        [Input("productId", required: true)]
        public Input<int> ProductId { get; set; } = null!;

        /// <summary>
        /// Promo code to apply at creation.
        /// </summary>
        [Input("promocode")]
        public Input<string>? Promocode { get; set; }

        /// <summary>
        /// Storage size in GB. Defaults to 100. Changing it triggers upgrade (`PUT .../{account_id}`) — grow-only, shrinking is rejected by the API.
        /// </summary>
        [Input("size")]
        public Input<int>? Size { get; set; }

        /// <summary>
        /// Name of the storage. Create-only, changing it replaces the storage.
        /// </summary>
        [Input("storageName", required: true)]
        public Input<string> StorageName { get; set; } = null!;

        public BaremetalElasticStorageArgs()
        {
            PayWithCreditCard = true;
            Size = 100;
        }
        public static new BaremetalElasticStorageArgs Empty => new BaremetalElasticStorageArgs();
    }
}
