// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Biznetgio.Biznetgio
{
    public static class GpuGraph
    {
        public static Task<GpuGraphResult> InvokeAsync(GpuGraphArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GpuGraphResult>("biznetgio:index:gpuGraph", args ?? new GpuGraphArgs(), options.WithDefaults());

        public static Output<GpuGraphResult> Invoke(GpuGraphInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GpuGraphResult>("biznetgio:index:gpuGraph", args ?? new GpuGraphInvokeArgs(), options.WithDefaults());

        public static Output<GpuGraphResult> Invoke(GpuGraphInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GpuGraphResult>("biznetgio:index:gpuGraph", args ?? new GpuGraphInvokeArgs(), options.WithDefaults());
    }


    public sealed class GpuGraphArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Account id of the GPU instance to get the monitoring graph for.
        /// </summary>
        [Input("accountId", required: true)]
        public string AccountId { get; set; } = null!;

        /// <summary>
        /// Timeframe of the graph: `hour`, `day`, `week`, `month`, or `year`. Defaults to `hour`.
        /// </summary>
        [Input("timeframe")]
        public string? Timeframe { get; set; }

        public GpuGraphArgs()
        {
        }
        public static new GpuGraphArgs Empty => new GpuGraphArgs();
    }

    public sealed class GpuGraphInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Account id of the GPU instance to get the monitoring graph for.
        /// </summary>
        [Input("accountId", required: true)]
        public Input<string> AccountId { get; set; } = null!;

        /// <summary>
        /// Timeframe of the graph: `hour`, `day`, `week`, `month`, or `year`. Defaults to `hour`.
        /// </summary>
        [Input("timeframe")]
        public Input<string>? Timeframe { get; set; }

        public GpuGraphInvokeArgs()
        {
        }
        public static new GpuGraphInvokeArgs Empty => new GpuGraphInvokeArgs();
    }


    [OutputType]
    public sealed class GpuGraphResult
    {
        /// <summary>
        /// Monitoring graph payload from `GET /neo-gpus/accounts/{account_id}/graph-monitor`, falls back to the raw JSON when no graph field is present.
        /// </summary>
        public readonly string Graph;
        /// <summary>
        /// Raw JSON of the full response.
        /// </summary>
        public readonly string Raw;

        [OutputConstructor]
        private GpuGraphResult(
            string graph,

            string raw)
        {
            Graph = graph;
            Raw = raw;
        }
    }
}
