// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Biznetgio.Biznetgio
{
    public static class NeoliteProOsList
    {
        public static Task<NeoliteProOsListResult> InvokeAsync(NeoliteProOsListArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<NeoliteProOsListResult>("biznetgio:index:neoliteProOsList", args ?? new NeoliteProOsListArgs(), options.WithDefaults());

        public static Output<NeoliteProOsListResult> Invoke(NeoliteProOsListInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<NeoliteProOsListResult>("biznetgio:index:neoliteProOsList", args ?? new NeoliteProOsListInvokeArgs(), options.WithDefaults());

        public static Output<NeoliteProOsListResult> Invoke(NeoliteProOsListInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<NeoliteProOsListResult>("biznetgio:index:neoliteProOsList", args ?? new NeoliteProOsListInvokeArgs(), options.WithDefaults());
    }


    public sealed class NeoliteProOsListArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Product id NEO Lite Pro.
        /// </summary>
        [Input("productId", required: true)]
        public int ProductId { get; set; }

        public NeoliteProOsListArgs()
        {
        }
        public static new NeoliteProOsListArgs Empty => new NeoliteProOsListArgs();
    }

    public sealed class NeoliteProOsListInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Product id NEO Lite Pro.
        /// </summary>
        [Input("productId", required: true)]
        public Input<int> ProductId { get; set; } = null!;

        public NeoliteProOsListInvokeArgs()
        {
        }
        public static new NeoliteProOsListInvokeArgs Empty => new NeoliteProOsListInvokeArgs();
    }


    [OutputType]
    public sealed class NeoliteProOsListResult
    {
        public readonly ImmutableArray<Outputs.NeoliteOsItem> Oss;

        [OutputConstructor]
        private NeoliteProOsListResult(ImmutableArray<Outputs.NeoliteOsItem> oss)
        {
            Oss = oss;
        }
    }
}
