// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Shirasakaren.Biznetgio
{
    [BiznetgioResourceType("biznetgio:index:ObjectStorageBucket")]
    public partial class ObjectStorageBucket : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Object storage instance account id. Create-only.
        /// </summary>
        [Output("accountId")]
        public Output<string> AccountId { get; private set; } = null!;

        /// <summary>
        /// S3-style canned ACL: empty (default private), private, public-read, public-read-write, authenticated-read, log-delivery-write. Defaults to empty.
        /// </summary>
        [Output("acl")]
        public Output<string?> Acl { get; private set; } = null!;

        /// <summary>
        /// Bucket name, minimum 3 chars, `[a-zA-Z0-9-_]`. Immutable, changing it replaces the bucket.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Raw JSON of the last read response, for anything not modeled yet.
        /// </summary>
        [Output("raw")]
        public Output<string> Raw { get; private set; } = null!;


        /// <summary>
        /// Create a ObjectStorageBucket resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ObjectStorageBucket(string name, ObjectStorageBucketArgs args, CustomResourceOptions? options = null)
            : base("biznetgio:index:ObjectStorageBucket", name, args ?? new ObjectStorageBucketArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ObjectStorageBucket(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("biznetgio:index:ObjectStorageBucket", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/shirasakaren/pulumi-biznetgio",
                AdditionalSecretOutputs =
                {
                    "raw",
                },
                ReplaceOnChanges =
                {
                    "accountId",
                    "name",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ObjectStorageBucket resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ObjectStorageBucket Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ObjectStorageBucket(name, id, options);
        }
    }

    public sealed class ObjectStorageBucketArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Object storage instance account id. Create-only.
        /// </summary>
        [Input("accountId", required: true)]
        public Input<string> AccountId { get; set; } = null!;

        /// <summary>
        /// S3-style canned ACL: empty (default private), private, public-read, public-read-write, authenticated-read, log-delivery-write. Defaults to empty.
        /// </summary>
        [Input("acl")]
        public Input<string>? Acl { get; set; }

        /// <summary>
        /// Bucket name, minimum 3 chars, `[a-zA-Z0-9-_]`. Immutable, changing it replaces the bucket.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public ObjectStorageBucketArgs()
        {
            Acl = "";
        }
        public static new ObjectStorageBucketArgs Empty => new ObjectStorageBucketArgs();
    }
}
