// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Shirasakaren.Biznetgio
{
    public static class ObjectStorageBuckets
    {
        public static Task<ObjectStorageBucketsResult> InvokeAsync(ObjectStorageBucketsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<ObjectStorageBucketsResult>("biznetgio:index:objectStorageBuckets", args ?? new ObjectStorageBucketsArgs(), options.WithDefaults());

        public static Output<ObjectStorageBucketsResult> Invoke(ObjectStorageBucketsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<ObjectStorageBucketsResult>("biznetgio:index:objectStorageBuckets", args ?? new ObjectStorageBucketsInvokeArgs(), options.WithDefaults());

        public static Output<ObjectStorageBucketsResult> Invoke(ObjectStorageBucketsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<ObjectStorageBucketsResult>("biznetgio:index:objectStorageBuckets", args ?? new ObjectStorageBucketsInvokeArgs(), options.WithDefaults());
    }


    public sealed class ObjectStorageBucketsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Object storage instance account id.
        /// </summary>
        [Input("accountId", required: true)]
        public string AccountId { get; set; } = null!;

        public ObjectStorageBucketsArgs()
        {
        }
        public static new ObjectStorageBucketsArgs Empty => new ObjectStorageBucketsArgs();
    }

    public sealed class ObjectStorageBucketsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Object storage instance account id.
        /// </summary>
        [Input("accountId", required: true)]
        public Input<string> AccountId { get; set; } = null!;

        public ObjectStorageBucketsInvokeArgs()
        {
        }
        public static new ObjectStorageBucketsInvokeArgs Empty => new ObjectStorageBucketsInvokeArgs();
    }


    [OutputType]
    public sealed class ObjectStorageBucketsResult
    {
        /// <summary>
        /// List of buckets inside the instance.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObjectStorageBucketsBucket> Buckets;

        [OutputConstructor]
        private ObjectStorageBucketsResult(ImmutableArray<Outputs.ObjectStorageBucketsBucket> buckets)
        {
            Buckets = buckets;
        }
    }
}
