// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Biznetgio.Biznetgio
{
    [BiznetgioResourceType("biznetgio:index:ObjectStorageObject")]
    public partial class ObjectStorageObject : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Object storage instance account id. Create-only.
        /// </summary>
        [Output("accountId")]
        public Output<string> AccountId { get; private set; } = null!;

        /// <summary>
        /// S3-style canned ACL applied to the object. Defaults to empty.
        /// </summary>
        [Output("acl")]
        public Output<string?> Acl { get; private set; } = null!;

        /// <summary>
        /// Bucket name. Create-only.
        /// </summary>
        [Output("bucket")]
        public Output<string> Bucket { get; private set; } = null!;

        /// <summary>
        /// Inline content yang mau di-upload. Exactly one of `source`/`content` required.
        /// </summary>
        [Output("content")]
        public Output<string?> Content { get; private set; } = null!;

        /// <summary>
        /// Object key inside the bucket. Create-only.
        /// </summary>
        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        /// <summary>
        /// Raw JSON of the last read response, for anything not modeled yet.
        /// </summary>
        [Output("raw")]
        public Output<string> Raw { get; private set; } = null!;

        /// <summary>
        /// Path ke file lokal yang mau di-upload. Exactly one of `source`/`content` required.
        /// </summary>
        [Output("source")]
        public Output<string?> Source { get; private set; } = null!;


        /// <summary>
        /// Create a ObjectStorageObject resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ObjectStorageObject(string name, ObjectStorageObjectArgs args, CustomResourceOptions? options = null)
            : base("biznetgio:index:ObjectStorageObject", name, args ?? new ObjectStorageObjectArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ObjectStorageObject(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("biznetgio:index:ObjectStorageObject", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "content",
                    "raw",
                },
                ReplaceOnChanges =
                {
                    "accountId",
                    "bucket",
                    "content",
                    "key",
                    "source",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ObjectStorageObject resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ObjectStorageObject Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ObjectStorageObject(name, id, options);
        }
    }

    public sealed class ObjectStorageObjectArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Object storage instance account id. Create-only.
        /// </summary>
        [Input("accountId", required: true)]
        public Input<string> AccountId { get; set; } = null!;

        /// <summary>
        /// S3-style canned ACL applied to the object. Defaults to empty.
        /// </summary>
        [Input("acl")]
        public Input<string>? Acl { get; set; }

        /// <summary>
        /// Bucket name. Create-only.
        /// </summary>
        [Input("bucket", required: true)]
        public Input<string> Bucket { get; set; } = null!;

        [Input("content")]
        private Input<string>? _content;

        /// <summary>
        /// Inline content yang mau di-upload. Exactly one of `source`/`content` required.
        /// </summary>
        public Input<string>? Content
        {
            get => _content;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _content = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Object key inside the bucket. Create-only.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// Path ke file lokal yang mau di-upload. Exactly one of `source`/`content` required.
        /// </summary>
        [Input("source")]
        public Input<string>? Source { get; set; }

        public ObjectStorageObjectArgs()
        {
            Acl = "";
        }
        public static new ObjectStorageObjectArgs Empty => new ObjectStorageObjectArgs();
    }
}
