// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;


public final class BaremetalAdditionalIpAssignmentArgs extends com.pulumi.resources.ResourceArgs {

    public static final BaremetalAdditionalIpAssignmentArgs Empty = new BaremetalAdditionalIpAssignmentArgs();

    /**
     * Account id of the additional IP to attach, from BaremetalAdditionalIp.
     * 
     */
    @Import(name="additionalIpId", required=true)
    private Output<Integer> additionalIpId;

    /**
     * @return Account id of the additional IP to attach, from BaremetalAdditionalIp.
     * 
     */
    public Output<Integer> additionalIpId() {
        return this.additionalIpId;
    }

    /**
     * Account id of the baremetal to attach to. Changing the target replaces the assignment.
     * 
     */
    @Import(name="metalAccountId", required=true)
    private Output<Integer> metalAccountId;

    /**
     * @return Account id of the baremetal to attach to. Changing the target replaces the assignment.
     * 
     */
    public Output<Integer> metalAccountId() {
        return this.metalAccountId;
    }

    private BaremetalAdditionalIpAssignmentArgs() {}

    private BaremetalAdditionalIpAssignmentArgs(BaremetalAdditionalIpAssignmentArgs $) {
        this.additionalIpId = $.additionalIpId;
        this.metalAccountId = $.metalAccountId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BaremetalAdditionalIpAssignmentArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BaremetalAdditionalIpAssignmentArgs $;

        public Builder() {
            $ = new BaremetalAdditionalIpAssignmentArgs();
        }

        public Builder(BaremetalAdditionalIpAssignmentArgs defaults) {
            $ = new BaremetalAdditionalIpAssignmentArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param additionalIpId Account id of the additional IP to attach, from BaremetalAdditionalIp.
         * 
         * @return builder
         * 
         */
        public Builder additionalIpId(Output<Integer> additionalIpId) {
            $.additionalIpId = additionalIpId;
            return this;
        }

        /**
         * @param additionalIpId Account id of the additional IP to attach, from BaremetalAdditionalIp.
         * 
         * @return builder
         * 
         */
        public Builder additionalIpId(Integer additionalIpId) {
            return additionalIpId(Output.of(additionalIpId));
        }

        /**
         * @param metalAccountId Account id of the baremetal to attach to. Changing the target replaces the assignment.
         * 
         * @return builder
         * 
         */
        public Builder metalAccountId(Output<Integer> metalAccountId) {
            $.metalAccountId = metalAccountId;
            return this;
        }

        /**
         * @param metalAccountId Account id of the baremetal to attach to. Changing the target replaces the assignment.
         * 
         * @return builder
         * 
         */
        public Builder metalAccountId(Integer metalAccountId) {
            return metalAccountId(Output.of(metalAccountId));
        }

        public BaremetalAdditionalIpAssignmentArgs build() {
            if ($.additionalIpId == null) {
                throw new MissingRequiredPropertyException("BaremetalAdditionalIpAssignmentArgs", "additionalIpId");
            }
            if ($.metalAccountId == null) {
                throw new MissingRequiredPropertyException("BaremetalAdditionalIpAssignmentArgs", "metalAccountId");
            }
            return $;
        }
    }

}
