// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio;

import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("biznetgio");
/**
 * BiznetGIO API token (x-token header). Falls back to BIZNETGIO_API_KEY.
 * 
 */
    public Optional<String> apiToken() {
        return Codegen.stringProp("apiToken").config(config).env("BIZNETGIO_API_KEY").get();
    }
/**
 * BiznetGIO API base URL. Falls back to BIZNETGIO_BASE_URL.
 * 
 */
    public Optional<String> baseUrl() {
        return Codegen.stringProp("baseUrl").config(config).env("BIZNETGIO_BASE_URL").def("https://api.portal.biznetgio.com/v1").get();
    }
}
