// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;
import ren.shirasaka.biznetgio.NeoliteSnapshotArgs;
import ren.shirasaka.biznetgio.Utilities;

@ResourceType(type="biznetgio:index:NeoliteSnapshot")
public class NeoliteSnapshot extends com.pulumi.resources.CustomResource {
    /**
     * Billing cycle: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
     * 
     */
    @Export(name="cycle", refs={String.class}, tree="[0]")
    private Output<String> cycle;

    /**
     * @return Billing cycle: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
     * 
     */
    public Output<String> cycle() {
        return this.cycle;
    }
    /**
     * Snapshot description.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return Snapshot description.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * Snapshot name. Defaults to `snapshot-name`.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> name;

    /**
     * @return Snapshot name. Defaults to `snapshot-name`.
     * 
     */
    public Output<Optional<String>> name() {
        return Codegen.optional(this.name);
    }
    /**
     * Account id of the NEO Lite VM being snapshotted.
     * 
     */
    @Export(name="neoliteAccountId", refs={Integer.class}, tree="[0]")
    private Output<Integer> neoliteAccountId;

    /**
     * @return Account id of the NEO Lite VM being snapshotted.
     * 
     */
    public Output<Integer> neoliteAccountId() {
        return this.neoliteAccountId;
    }
    /**
     * Order id from the creation response.
     * 
     */
    @Export(name="orderId", refs={String.class}, tree="[0]")
    private Output<String> orderId;

    /**
     * @return Order id from the creation response.
     * 
     */
    public Output<String> orderId() {
        return this.orderId;
    }
    /**
     * Pay the invoice with the registered credit card at order time. Defaults to true (auto-charge); set false to leave it unpaid in the portal until settled.
     * 
     */
    @Export(name="payWithCreditCard", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> payWithCreditCard;

    /**
     * @return Pay the invoice with the registered credit card at order time. Defaults to true (auto-charge); set false to leave it unpaid in the portal until settled.
     * 
     */
    public Output<Optional<Boolean>> payWithCreditCard() {
        return Codegen.optional(this.payWithCreditCard);
    }
    /**
     * Promo code to apply at order.
     * 
     */
    @Export(name="promocode", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> promocode;

    /**
     * @return Promo code to apply at order.
     * 
     */
    public Output<Optional<String>> promocode() {
        return Codegen.optional(this.promocode);
    }
    /**
     * Snapshot status (Active, Pending, Suspended, Terminated).
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    /**
     * @return Snapshot status (Active, Pending, Suspended, Terminated).
     * 
     */
    public Output<String> status() {
        return this.status;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public NeoliteSnapshot(java.lang.String name) {
        this(name, NeoliteSnapshotArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public NeoliteSnapshot(java.lang.String name, NeoliteSnapshotArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public NeoliteSnapshot(java.lang.String name, NeoliteSnapshotArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("biznetgio:index:NeoliteSnapshot", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private NeoliteSnapshot(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("biznetgio:index:NeoliteSnapshot", name, null, makeResourceOptions(options, id), false);
    }

    private static NeoliteSnapshotArgs makeArgs(NeoliteSnapshotArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? NeoliteSnapshotArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/shirasakaren/pulumi-biznetgio")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static NeoliteSnapshot get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new NeoliteSnapshot(name, id, options);
    }
}
