// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;
import ren.shirasaka.biznetgio.NeoliteVmArgs;
import ren.shirasaka.biznetgio.Utilities;
import ren.shirasaka.biznetgio.outputs.NeoliteLastInvoice;

@ResourceType(type="biznetgio:index:NeoliteVm")
public class NeoliteVm extends com.pulumi.resources.CustomResource {
    /**
     * Active billing cycle.
     * 
     */
    @Export(name="billingcycle", refs={String.class}, tree="[0]")
    private Output<String> billingcycle;

    /**
     * @return Active billing cycle.
     * 
     */
    public Output<String> billingcycle() {
        return this.billingcycle;
    }
    /**
     * VM cloud-init password (sensitive).
     * 
     */
    @Export(name="ciPassword", refs={String.class}, tree="[0]")
    private Output<String> ciPassword;

    /**
     * @return VM cloud-init password (sensitive).
     * 
     */
    public Output<String> ciPassword() {
        return this.ciPassword;
    }
    /**
     * VM cloud-init user.
     * 
     */
    @Export(name="ciUser", refs={String.class}, tree="[0]")
    private Output<String> ciUser;

    /**
     * @return VM cloud-init user.
     * 
     */
    public Output<String> ciUser() {
        return this.ciUser;
    }
    /**
     * Console password at creation. Write-only: never re-fetched from the API.
     * 
     */
    @Export(name="consolePassword", refs={String.class}, tree="[0]")
    private Output<String> consolePassword;

    /**
     * @return Console password at creation. Write-only: never re-fetched from the API.
     * 
     */
    public Output<String> consolePassword() {
        return this.consolePassword;
    }
    /**
     * Number of VM CPUs.
     * 
     */
    @Export(name="cpus", refs={Integer.class}, tree="[0]")
    private Output<Integer> cpus;

    /**
     * @return Number of VM CPUs.
     * 
     */
    public Output<Integer> cpus() {
        return this.cpus;
    }
    /**
     * Billing cycle: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
     * 
     */
    @Export(name="cycle", refs={String.class}, tree="[0]")
    private Output<String> cycle;

    /**
     * @return Billing cycle: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
     * 
     */
    public Output<String> cycle() {
        return this.cycle;
    }
    /**
     * VM description.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return VM description.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * Target disk size (GB, absolute - not an increment). Can only go up, never down.
     * 
     */
    @Export(name="diskSize", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> diskSize;

    /**
     * @return Target disk size (GB, absolute - not an increment). Can only go up, never down.
     * 
     */
    public Output<Optional<Integer>> diskSize() {
        return Codegen.optional(this.diskSize);
    }
    /**
     * Keypair id from `NeoliteKeypair`. Can be changed via change-keypair.
     * 
     */
    @Export(name="keypairId", refs={Integer.class}, tree="[0]")
    private Output<Integer> keypairId;

    /**
     * @return Keypair id from `NeoliteKeypair`. Can be changed via change-keypair.
     * 
     */
    public Output<Integer> keypairId() {
        return this.keypairId;
    }
    /**
     * VM&#39;s last invoice.
     * 
     */
    @Export(name="lastInvoice", refs={NeoliteLastInvoice.class}, tree="[0]")
    private Output<NeoliteLastInvoice> lastInvoice;

    /**
     * @return VM&#39;s last invoice.
     * 
     */
    public Output<NeoliteLastInvoice> lastInvoice() {
        return this.lastInvoice;
    }
    /**
     * Maximum VM disk size (GB).
     * 
     */
    @Export(name="maxDisk", refs={Integer.class}, tree="[0]")
    private Output<Integer> maxDisk;

    /**
     * @return Maximum VM disk size (GB).
     * 
     */
    public Output<Integer> maxDisk() {
        return this.maxDisk;
    }
    /**
     * Maximum VM memory (MB).
     * 
     */
    @Export(name="maxMem", refs={Integer.class}, tree="[0]")
    private Output<Integer> maxMem;

    /**
     * @return Maximum VM memory (MB).
     * 
     */
    public Output<Integer> maxMem() {
        return this.maxMem;
    }
    /**
     * Memory used by the VM (MB).
     * 
     */
    @Export(name="mem", refs={Integer.class}, tree="[0]")
    private Output<Integer> mem;

    /**
     * @return Memory used by the VM (MB).
     * 
     */
    public Output<Integer> mem() {
        return this.mem;
    }
    /**
     * Trigger a one-shot migration to NEO Lite Pro: set the neolitepro_product_id target. Change the value again to re-trigger.
     * 
     */
    @Export(name="migrateToPro", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> migrateToPro;

    /**
     * @return Trigger a one-shot migration to NEO Lite Pro: set the neolitepro_product_id target. Change the value again to re-trigger.
     * 
     */
    public Output<Optional<String>> migrateToPro() {
        return Codegen.optional(this.migrateToPro);
    }
    /**
     * Next billing due date.
     * 
     */
    @Export(name="nextDue", refs={String.class}, tree="[0]")
    private Output<String> nextDue;

    /**
     * @return Next billing due date.
     * 
     */
    public Output<String> nextDue() {
        return this.nextDue;
    }
    /**
     * Order id from the creation response.
     * 
     */
    @Export(name="orderId", refs={String.class}, tree="[0]")
    private Output<String> orderId;

    /**
     * @return Order id from the creation response.
     * 
     */
    public Output<String> orderId() {
        return this.orderId;
    }
    /**
     * Name of the OS running on the VM.
     * 
     */
    @Export(name="osName", refs={String.class}, tree="[0]")
    private Output<String> osName;

    /**
     * @return Name of the OS running on the VM.
     * 
     */
    public Output<String> osName() {
        return this.osName;
    }
    /**
     * Pay the invoice with the registered credit card at order time. Defaults to true (auto-charge); set false to leave it unpaid in the portal until settled.
     * 
     */
    @Export(name="payWithCreditCard", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> payWithCreditCard;

    /**
     * @return Pay the invoice with the registered credit card at order time. Defaults to true (auto-charge); set false to leave it unpaid in the portal until settled.
     * 
     */
    public Output<Optional<Boolean>> payWithCreditCard() {
        return Codegen.optional(this.payWithCreditCard);
    }
    /**
     * VM power state: start, stop, suspend, resume, or shutdown. Update only sends an action when the value changes.
     * 
     */
    @Export(name="powerState", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> powerState;

    /**
     * @return VM power state: start, stop, suspend, resume, or shutdown. Update only sends an action when the value changes.
     * 
     */
    public Output<Optional<String>> powerState() {
        return Codegen.optional(this.powerState);
    }
    /**
     * Product id from the `getProducts` function or the portal.
     * 
     */
    @Export(name="productId", refs={Integer.class}, tree="[0]")
    private Output<Integer> productId;

    /**
     * @return Product id from the `getProducts` function or the portal.
     * 
     */
    public Output<Integer> productId() {
        return this.productId;
    }
    /**
     * Active product name.
     * 
     */
    @Export(name="productName", refs={String.class}, tree="[0]")
    private Output<String> productName;

    /**
     * @return Active product name.
     * 
     */
    public Output<String> productName() {
        return this.productName;
    }
    /**
     * Promo code to apply at order.
     * 
     */
    @Export(name="promocode", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> promocode;

    /**
     * @return Promo code to apply at order.
     * 
     */
    public Output<Optional<String>> promocode() {
        return Codegen.optional(this.promocode);
    }
    /**
     * Raw JSON response of the last-read account, for accessing fields not yet modeled (cipassword masked).
     * 
     */
    @Export(name="raw", refs={String.class}, tree="[0]")
    private Output<String> raw;

    /**
     * @return Raw JSON response of the last-read account, for accessing fields not yet modeled (cipassword masked).
     * 
     */
    public Output<String> raw() {
        return this.raw;
    }
    /**
     * When changed, the VM is rebuilt (wipes the OS) with the new OS via the rebuild endpoint. Valid OS values are listed by the `getOsList` function.
     * 
     */
    @Export(name="rebuildOs", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> rebuildOs;

    /**
     * @return When changed, the VM is rebuilt (wipes the OS) with the new OS via the rebuild endpoint. Valid OS values are listed by the `getOsList` function.
     * 
     */
    public Output<Optional<String>> rebuildOs() {
        return Codegen.optional(this.rebuildOs);
    }
    /**
     * Recurring amount per cycle.
     * 
     */
    @Export(name="recurringAmount", refs={Integer.class}, tree="[0]")
    private Output<Integer> recurringAmount;

    /**
     * @return Recurring amount per cycle.
     * 
     */
    public Output<Integer> recurringAmount() {
        return this.recurringAmount;
    }
    /**
     * VM region.
     * 
     */
    @Export(name="region", refs={String.class}, tree="[0]")
    private Output<String> region;

    /**
     * @return VM region.
     * 
     */
    public Output<String> region() {
        return this.region;
    }
    /**
     * VM region label.
     * 
     */
    @Export(name="regionLabel", refs={String.class}, tree="[0]")
    private Output<String> regionLabel;

    /**
     * @return VM region label.
     * 
     */
    public Output<String> regionLabel() {
        return this.regionLabel;
    }
    /**
     * OS installed at creation, from the `getOsList` function. To change OS, use `rebuildOs`.
     * 
     */
    @Export(name="selectOs", refs={String.class}, tree="[0]")
    private Output<String> selectOs;

    /**
     * @return OS installed at creation, from the `getOsList` function. To change OS, use `rebuildOs`.
     * 
     */
    public Output<String> selectOs() {
        return this.selectOs;
    }
    /**
     * SSH and console user set at creation.
     * 
     */
    @Export(name="sshAndConsoleUser", refs={String.class}, tree="[0]")
    private Output<String> sshAndConsoleUser;

    /**
     * @return SSH and console user set at creation.
     * 
     */
    public Output<String> sshAndConsoleUser() {
        return this.sshAndConsoleUser;
    }
    /**
     * Last known account status from the API (Active, Pending, Suspended, Terminated).
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    /**
     * @return Last known account status from the API (Active, Pending, Suspended, Terminated).
     * 
     */
    public Output<String> status() {
        return this.status;
    }
    /**
     * VM uptime in seconds.
     * 
     */
    @Export(name="uptime", refs={Integer.class}, tree="[0]")
    private Output<Integer> uptime;

    /**
     * @return VM uptime in seconds.
     * 
     */
    public Output<Integer> uptime() {
        return this.uptime;
    }
    /**
     * VM name. Defaults to `server-name`. Can be changed via change-vm-name.
     * 
     */
    @Export(name="vmName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> vmName;

    /**
     * @return VM name. Defaults to `server-name`. Can be changed via change-vm-name.
     * 
     */
    public Output<Optional<String>> vmName() {
        return Codegen.optional(this.vmName);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public NeoliteVm(java.lang.String name) {
        this(name, NeoliteVmArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public NeoliteVm(java.lang.String name, NeoliteVmArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public NeoliteVm(java.lang.String name, NeoliteVmArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("biznetgio:index:NeoliteVm", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private NeoliteVm(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("biznetgio:index:NeoliteVm", name, null, makeResourceOptions(options, id), false);
    }

    private static NeoliteVmArgs makeArgs(NeoliteVmArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? NeoliteVmArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/shirasakaren/pulumi-biznetgio")
            .additionalSecretOutputs(List.of(
                "ciPassword",
                "consolePassword",
                "raw"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static NeoliteVm get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new NeoliteVm(name, id, options);
    }
}
