// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;
import ren.shirasaka.biznetgio.ObjectStorageBucketArgs;
import ren.shirasaka.biznetgio.Utilities;

@ResourceType(type="biznetgio:index:ObjectStorageBucket")
public class ObjectStorageBucket extends com.pulumi.resources.CustomResource {
    /**
     * Object storage instance account id. Create-only.
     * 
     */
    @Export(name="accountId", refs={String.class}, tree="[0]")
    private Output<String> accountId;

    /**
     * @return Object storage instance account id. Create-only.
     * 
     */
    public Output<String> accountId() {
        return this.accountId;
    }
    /**
     * S3-style canned ACL: empty (default private), private, public-read, public-read-write, authenticated-read, log-delivery-write. Defaults to empty.
     * 
     */
    @Export(name="acl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> acl;

    /**
     * @return S3-style canned ACL: empty (default private), private, public-read, public-read-write, authenticated-read, log-delivery-write. Defaults to empty.
     * 
     */
    public Output<Optional<String>> acl() {
        return Codegen.optional(this.acl);
    }
    /**
     * Bucket name, minimum 3 chars, `[a-zA-Z0-9-_]`. Immutable, changing it replaces the bucket.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Bucket name, minimum 3 chars, `[a-zA-Z0-9-_]`. Immutable, changing it replaces the bucket.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Raw JSON of the last read response, for anything not modeled yet.
     * 
     */
    @Export(name="raw", refs={String.class}, tree="[0]")
    private Output<String> raw;

    /**
     * @return Raw JSON of the last read response, for anything not modeled yet.
     * 
     */
    public Output<String> raw() {
        return this.raw;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ObjectStorageBucket(java.lang.String name) {
        this(name, ObjectStorageBucketArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ObjectStorageBucket(java.lang.String name, ObjectStorageBucketArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ObjectStorageBucket(java.lang.String name, ObjectStorageBucketArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("biznetgio:index:ObjectStorageBucket", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ObjectStorageBucket(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("biznetgio:index:ObjectStorageBucket", name, null, makeResourceOptions(options, id), false);
    }

    private static ObjectStorageBucketArgs makeArgs(ObjectStorageBucketArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ObjectStorageBucketArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/shirasakaren/pulumi-biznetgio")
            .additionalSecretOutputs(List.of(
                "raw"
            ))
            .replaceOnChanges(List.of(
                "accountId",
                "name"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ObjectStorageBucket get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ObjectStorageBucket(name, id, options);
    }
}
