// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GpuFlavor {
    /**
     * @return Flavor id.
     * 
     */
    private Integer flavorId;
    /**
     * @return Flavor name.
     * 
     */
    private String name;
    /**
     * @return Raw JSON of the flavor response.
     * 
     */
    private String raw;

    private GpuFlavor() {}
    /**
     * @return Flavor id.
     * 
     */
    public Integer flavorId() {
        return this.flavorId;
    }
    /**
     * @return Flavor name.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Raw JSON of the flavor response.
     * 
     */
    public String raw() {
        return this.raw;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GpuFlavor defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer flavorId;
        private String name;
        private String raw;
        public Builder() {}
        public Builder(GpuFlavor defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.flavorId = defaults.flavorId;
    	      this.name = defaults.name;
    	      this.raw = defaults.raw;
        }

        @CustomType.Setter
        public Builder flavorId(Integer flavorId) {
            if (flavorId == null) {
              throw new MissingRequiredPropertyException("GpuFlavor", "flavorId");
            }
            this.flavorId = flavorId;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GpuFlavor", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder raw(String raw) {
            if (raw == null) {
              throw new MissingRequiredPropertyException("GpuFlavor", "raw");
            }
            this.raw = raw;
            return this;
        }
        public GpuFlavor build() {
            final var _resultValue = new GpuFlavor();
            _resultValue.flavorId = flavorId;
            _resultValue.name = name;
            _resultValue.raw = raw;
            return _resultValue;
        }
    }
}
