// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GpuGraphResult {
    /**
     * @return Monitoring graph payload from `GET /neo-gpus/accounts/{account_id}/graph-monitor`, falls back to the raw JSON when no graph field is present.
     * 
     */
    private String graph;
    /**
     * @return Raw JSON of the full response.
     * 
     */
    private String raw;

    private GpuGraphResult() {}
    /**
     * @return Monitoring graph payload from `GET /neo-gpus/accounts/{account_id}/graph-monitor`, falls back to the raw JSON when no graph field is present.
     * 
     */
    public String graph() {
        return this.graph;
    }
    /**
     * @return Raw JSON of the full response.
     * 
     */
    public String raw() {
        return this.raw;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GpuGraphResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String graph;
        private String raw;
        public Builder() {}
        public Builder(GpuGraphResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.graph = defaults.graph;
    	      this.raw = defaults.raw;
        }

        @CustomType.Setter
        public Builder graph(String graph) {
            if (graph == null) {
              throw new MissingRequiredPropertyException("GpuGraphResult", "graph");
            }
            this.graph = graph;
            return this;
        }
        @CustomType.Setter
        public Builder raw(String raw) {
            if (raw == null) {
              throw new MissingRequiredPropertyException("GpuGraphResult", "raw");
            }
            this.raw = raw;
            return this;
        }
        public GpuGraphResult build() {
            final var _resultValue = new GpuGraphResult();
            _resultValue.graph = graph;
            _resultValue.raw = raw;
            return _resultValue;
        }
    }
}
