// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class ObjectStorageBucketsBucket {
    private String acl;
    private String name;
    private String raw;

    private ObjectStorageBucketsBucket() {}
    public String acl() {
        return this.acl;
    }
    public String name() {
        return this.name;
    }
    public String raw() {
        return this.raw;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ObjectStorageBucketsBucket defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String acl;
        private String name;
        private String raw;
        public Builder() {}
        public Builder(ObjectStorageBucketsBucket defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.acl = defaults.acl;
    	      this.name = defaults.name;
    	      this.raw = defaults.raw;
        }

        @CustomType.Setter
        public Builder acl(String acl) {
            if (acl == null) {
              throw new MissingRequiredPropertyException("ObjectStorageBucketsBucket", "acl");
            }
            this.acl = acl;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("ObjectStorageBucketsBucket", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder raw(String raw) {
            if (raw == null) {
              throw new MissingRequiredPropertyException("ObjectStorageBucketsBucket", "raw");
            }
            this.raw = raw;
            return this;
        }
        public ObjectStorageBucketsBucket build() {
            final var _resultValue = new ObjectStorageBucketsBucket();
            _resultValue.acl = acl;
            _resultValue.name = name;
            _resultValue.raw = raw;
            return _resultValue;
        }
    }
}
