// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class ObjectStorageCredentialsCredential {
    private String accessKey;
    private Boolean active;

    private ObjectStorageCredentialsCredential() {}
    public String accessKey() {
        return this.accessKey;
    }
    public Boolean active() {
        return this.active;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ObjectStorageCredentialsCredential defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String accessKey;
        private Boolean active;
        public Builder() {}
        public Builder(ObjectStorageCredentialsCredential defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accessKey = defaults.accessKey;
    	      this.active = defaults.active;
        }

        @CustomType.Setter
        public Builder accessKey(String accessKey) {
            if (accessKey == null) {
              throw new MissingRequiredPropertyException("ObjectStorageCredentialsCredential", "accessKey");
            }
            this.accessKey = accessKey;
            return this;
        }
        @CustomType.Setter
        public Builder active(Boolean active) {
            if (active == null) {
              throw new MissingRequiredPropertyException("ObjectStorageCredentialsCredential", "active");
            }
            this.active = active;
            return this;
        }
        public ObjectStorageCredentialsCredential build() {
            final var _resultValue = new ObjectStorageCredentialsCredential();
            _resultValue.accessKey = accessKey;
            _resultValue.active = active;
            return _resultValue;
        }
    }
}
