// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio.ren.shirasaka_biznetgio;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;
import ren.shirasaka.biznetgio.ren.shirasaka_biznetgio.BaremetalArgs;
import ren.shirasaka.biznetgio.ren.shirasaka_biznetgio.Utilities;

@ResourceType(type="biznetgio:index:Baremetal")
public class Baremetal extends com.pulumi.resources.CustomResource {
    /**
     * Creation timestamp (alias of created_at/date_created).
     * 
     */
    @Export(name="createdAt", refs={String.class}, tree="[0]")
    private Output<String> createdAt;

    /**
     * @return Creation timestamp (alias of created_at/date_created).
     * 
     */
    public Output<String> createdAt() {
        return this.createdAt;
    }
    /**
     * Billing cycle, e.g. `m` for monthly or `a` for annual.
     * 
     */
    @Export(name="cycle", refs={String.class}, tree="[0]")
    private Output<String> cycle;

    /**
     * @return Billing cycle, e.g. `m` for monthly or `a` for annual.
     * 
     */
    public Output<String> cycle() {
        return this.cycle;
    }
    /**
     * Public IP address of the server, when present.
     * 
     */
    @Export(name="ipAddress", refs={String.class}, tree="[0]")
    private Output<String> ipAddress;

    /**
     * @return Public IP address of the server, when present.
     * 
     */
    public Output<String> ipAddress() {
        return this.ipAddress;
    }
    /**
     * Baremetal keypair id, from BaremetalKeypair. The baremetal keypair pool is separate from neolite/gpu.
     * 
     */
    @Export(name="keypairId", refs={Integer.class}, tree="[0]")
    private Output<Integer> keypairId;

    /**
     * @return Baremetal keypair id, from BaremetalKeypair. The baremetal keypair pool is separate from neolite/gpu.
     * 
     */
    public Output<Integer> keypairId() {
        return this.keypairId;
    }
    /**
     * Display name of the server. The only field updatable in place.
     * 
     */
    @Export(name="label", refs={String.class}, tree="[0]")
    private Output<String> label;

    /**
     * @return Display name of the server. The only field updatable in place.
     * 
     */
    public Output<String> label() {
        return this.label;
    }
    /**
     * Order id from the creation response.
     * 
     */
    @Export(name="orderId", refs={String.class}, tree="[0]")
    private Output<String> orderId;

    /**
     * @return Order id from the creation response.
     * 
     */
    public Output<String> orderId() {
        return this.orderId;
    }
    /**
     * Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
     * 
     */
    @Export(name="payWithCreditCard", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> payWithCreditCard;

    /**
     * @return Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
     * 
     */
    public Output<Optional<Boolean>> payWithCreditCard() {
        return Codegen.optional(this.payWithCreditCard);
    }
    /**
     * Power state of the server: `on` or `off`. Only fires an API call when the value changes.
     * 
     */
    @Export(name="powerState", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> powerState;

    /**
     * @return Power state of the server: `on` or `off`. Only fires an API call when the value changes.
     * 
     */
    public Output<Optional<String>> powerState() {
        return Codegen.optional(this.powerState);
    }
    /**
     * Product id from the baremetal products function.
     * 
     */
    @Export(name="productId", refs={Integer.class}, tree="[0]")
    private Output<Integer> productId;

    /**
     * @return Product id from the baremetal products function.
     * 
     */
    public Output<Integer> productId() {
        return this.productId;
    }
    /**
     * Promo code to apply at creation.
     * 
     */
    @Export(name="promocode", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> promocode;

    /**
     * @return Promo code to apply at creation.
     * 
     */
    public Output<Optional<String>> promocode() {
        return Codegen.optional(this.promocode);
    }
    /**
     * Number of public IPs to request (1 = with public IP). Defaults to 1. Create-only, changing it replaces the instance.
     * 
     */
    @Export(name="publicIp", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> publicIp;

    /**
     * @return Number of public IPs to request (1 = with public IP). Defaults to 1. Create-only, changing it replaces the instance.
     * 
     */
    public Output<Optional<Integer>> publicIp() {
        return Codegen.optional(this.publicIp);
    }
    /**
     * Raw JSON of the last read response, for anything not modeled yet.
     * 
     */
    @Export(name="raw", refs={String.class}, tree="[0]")
    private Output<String> raw;

    /**
     * @return Raw JSON of the last read response, for anything not modeled yet.
     * 
     */
    public Output<String> raw() {
        return this.raw;
    }
    /**
     * Change this value to rebuild the instance (destructive, wipes the OS) via `PUT /baremetals/{account_id}/rebuild`. Valid OS list comes from the rebuildOsList function.
     * 
     */
    @Export(name="rebuildOs", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> rebuildOs;

    /**
     * @return Change this value to rebuild the instance (destructive, wipes the OS) via `PUT /baremetals/{account_id}/rebuild`. Valid OS list comes from the rebuildOsList function.
     * 
     */
    public Output<Optional<String>> rebuildOs() {
        return Codegen.optional(this.rebuildOs);
    }
    /**
     * Change this value to trigger a one-shot reset/reboot. The reset is an action, not a stable state.
     * 
     */
    @Export(name="resetTrigger", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> resetTrigger;

    /**
     * @return Change this value to trigger a one-shot reset/reboot. The reset is an action, not a stable state.
     * 
     */
    public Output<Optional<String>> resetTrigger() {
        return Codegen.optional(this.resetTrigger);
    }
    /**
     * OS to install at creation, from `GET /baremetals/products/{product_id}/oss`. Defaults to `ubuntu-22`. Create-only, changing it replaces the instance.
     * 
     */
    @Export(name="selectOs", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> selectOs;

    /**
     * @return OS to install at creation, from `GET /baremetals/products/{product_id}/oss`. Defaults to `ubuntu-22`. Create-only, changing it replaces the instance.
     * 
     */
    public Output<Optional<String>> selectOs() {
        return Codegen.optional(this.selectOs);
    }
    /**
     * Current status of the server.
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    /**
     * @return Current status of the server.
     * 
     */
    public Output<String> status() {
        return this.status;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Baremetal(java.lang.String name) {
        this(name, BaremetalArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Baremetal(java.lang.String name, BaremetalArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Baremetal(java.lang.String name, BaremetalArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("biznetgio:index:Baremetal", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Baremetal(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("biznetgio:index:Baremetal", name, null, makeResourceOptions(options, id), false);
    }

    private static BaremetalArgs makeArgs(BaremetalArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? BaremetalArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/shirasakaren/pulumi-biznetgio")
            .additionalSecretOutputs(List.of(
                "raw"
            ))
            .replaceOnChanges(List.of(
                "cycle",
                "keypairId",
                "payWithCreditCard",
                "productId",
                "promocode",
                "publicIp",
                "selectOs"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Baremetal get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Baremetal(name, id, options);
    }
}
