// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio.ren.shirasaka_biznetgio;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;
import ren.shirasaka.biznetgio.ren.shirasaka_biznetgio.inputs.GpuOnDemandArgsArgs;
import ren.shirasaka.biznetgio.ren.shirasaka_biznetgio.inputs.GpuSubscriptionArgsArgs;


public final class GpuInstanceArgs extends com.pulumi.resources.ResourceArgs {

    public static final GpuInstanceArgs Empty = new GpuInstanceArgs();

    /**
     * Console password. Create-only, changing it replaces the instance.
     * 
     */
    @Import(name="consolePassword", required=true)
    private Output<String> consolePassword;

    /**
     * @return Console password. Create-only, changing it replaces the instance.
     * 
     */
    public Output<String> consolePassword() {
        return this.consolePassword;
    }

    /**
     * GPU keypair id, from GpuKeypair.
     * 
     */
    @Import(name="keypairId", required=true)
    private Output<Integer> keypairId;

    /**
     * @return GPU keypair id, from GpuKeypair.
     * 
     */
    public Output<Integer> keypairId() {
        return this.keypairId;
    }

    /**
     * On-demand billing mode (hourly). Exactly one of `subscription` or `onDemand` must be set.
     * 
     */
    @Import(name="onDemand")
    private @Nullable Output<GpuOnDemandArgsArgs> onDemand;

    /**
     * @return On-demand billing mode (hourly). Exactly one of `subscription` or `onDemand` must be set.
     * 
     */
    public Optional<Output<GpuOnDemandArgsArgs>> onDemand() {
        return Optional.ofNullable(this.onDemand);
    }

    /**
     * Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
     * 
     */
    @Import(name="payWithCreditCard")
    private @Nullable Output<Boolean> payWithCreditCard;

    /**
     * @return Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
     * 
     */
    public Optional<Output<Boolean>> payWithCreditCard() {
        return Optional.ofNullable(this.payWithCreditCard);
    }

    /**
     * GPU product id from the gpu products function.
     * 
     */
    @Import(name="productId", required=true)
    private Output<Integer> productId;

    /**
     * @return GPU product id from the gpu products function.
     * 
     */
    public Output<Integer> productId() {
        return this.productId;
    }

    /**
     * Promo code to apply at creation.
     * 
     */
    @Import(name="promocode")
    private @Nullable Output<String> promocode;

    /**
     * @return Promo code to apply at creation.
     * 
     */
    public Optional<Output<String>> promocode() {
        return Optional.ofNullable(this.promocode);
    }

    /**
     * Change this value to rebuild the instance (destructive, reinstalls the OS).
     * 
     */
    @Import(name="rebuildTrigger")
    private @Nullable Output<String> rebuildTrigger;

    /**
     * @return Change this value to rebuild the instance (destructive, reinstalls the OS).
     * 
     */
    public Optional<Output<String>> rebuildTrigger() {
        return Optional.ofNullable(this.rebuildTrigger);
    }

    /**
     * Change this value to reserve 1 additional hour on an on-demand instance.
     * 
     */
    @Import(name="reserveAdditionalHoursTrigger")
    private @Nullable Output<String> reserveAdditionalHoursTrigger;

    /**
     * @return Change this value to reserve 1 additional hour on an on-demand instance.
     * 
     */
    public Optional<Output<String>> reserveAdditionalHoursTrigger() {
        return Optional.ofNullable(this.reserveAdditionalHoursTrigger);
    }

    /**
     * OS to install, from the product&#39;s select-os catalog.
     * 
     */
    @Import(name="selectOs", required=true)
    private Output<String> selectOs;

    /**
     * @return OS to install, from the product&#39;s select-os catalog.
     * 
     */
    public Output<String> selectOs() {
        return this.selectOs;
    }

    /**
     * Display name of the instance. Create-only, changing it replaces the instance.
     * 
     */
    @Import(name="serviceName")
    private @Nullable Output<String> serviceName;

    /**
     * @return Display name of the instance. Create-only, changing it replaces the instance.
     * 
     */
    public Optional<Output<String>> serviceName() {
        return Optional.ofNullable(this.serviceName);
    }

    /**
     * SSH and console user for the instance.
     * 
     */
    @Import(name="sshAndConsoleUser", required=true)
    private Output<String> sshAndConsoleUser;

    /**
     * @return SSH and console user for the instance.
     * 
     */
    public Output<String> sshAndConsoleUser() {
        return this.sshAndConsoleUser;
    }

    /**
     * Subscription billing mode (cycle-based). Exactly one of `subscription` or `onDemand` must be set.
     * 
     */
    @Import(name="subscription")
    private @Nullable Output<GpuSubscriptionArgsArgs> subscription;

    /**
     * @return Subscription billing mode (cycle-based). Exactly one of `subscription` or `onDemand` must be set.
     * 
     */
    public Optional<Output<GpuSubscriptionArgsArgs>> subscription() {
        return Optional.ofNullable(this.subscription);
    }

    private GpuInstanceArgs() {}

    private GpuInstanceArgs(GpuInstanceArgs $) {
        this.consolePassword = $.consolePassword;
        this.keypairId = $.keypairId;
        this.onDemand = $.onDemand;
        this.payWithCreditCard = $.payWithCreditCard;
        this.productId = $.productId;
        this.promocode = $.promocode;
        this.rebuildTrigger = $.rebuildTrigger;
        this.reserveAdditionalHoursTrigger = $.reserveAdditionalHoursTrigger;
        this.selectOs = $.selectOs;
        this.serviceName = $.serviceName;
        this.sshAndConsoleUser = $.sshAndConsoleUser;
        this.subscription = $.subscription;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GpuInstanceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GpuInstanceArgs $;

        public Builder() {
            $ = new GpuInstanceArgs();
        }

        public Builder(GpuInstanceArgs defaults) {
            $ = new GpuInstanceArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param consolePassword Console password. Create-only, changing it replaces the instance.
         * 
         * @return builder
         * 
         */
        public Builder consolePassword(Output<String> consolePassword) {
            $.consolePassword = consolePassword;
            return this;
        }

        /**
         * @param consolePassword Console password. Create-only, changing it replaces the instance.
         * 
         * @return builder
         * 
         */
        public Builder consolePassword(String consolePassword) {
            return consolePassword(Output.of(consolePassword));
        }

        /**
         * @param keypairId GPU keypair id, from GpuKeypair.
         * 
         * @return builder
         * 
         */
        public Builder keypairId(Output<Integer> keypairId) {
            $.keypairId = keypairId;
            return this;
        }

        /**
         * @param keypairId GPU keypair id, from GpuKeypair.
         * 
         * @return builder
         * 
         */
        public Builder keypairId(Integer keypairId) {
            return keypairId(Output.of(keypairId));
        }

        /**
         * @param onDemand On-demand billing mode (hourly). Exactly one of `subscription` or `onDemand` must be set.
         * 
         * @return builder
         * 
         */
        public Builder onDemand(@Nullable Output<GpuOnDemandArgsArgs> onDemand) {
            $.onDemand = onDemand;
            return this;
        }

        /**
         * @param onDemand On-demand billing mode (hourly). Exactly one of `subscription` or `onDemand` must be set.
         * 
         * @return builder
         * 
         */
        public Builder onDemand(GpuOnDemandArgsArgs onDemand) {
            return onDemand(Output.of(onDemand));
        }

        /**
         * @param payWithCreditCard Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
         * 
         * @return builder
         * 
         */
        public Builder payWithCreditCard(@Nullable Output<Boolean> payWithCreditCard) {
            $.payWithCreditCard = payWithCreditCard;
            return this;
        }

        /**
         * @param payWithCreditCard Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
         * 
         * @return builder
         * 
         */
        public Builder payWithCreditCard(Boolean payWithCreditCard) {
            return payWithCreditCard(Output.of(payWithCreditCard));
        }

        /**
         * @param productId GPU product id from the gpu products function.
         * 
         * @return builder
         * 
         */
        public Builder productId(Output<Integer> productId) {
            $.productId = productId;
            return this;
        }

        /**
         * @param productId GPU product id from the gpu products function.
         * 
         * @return builder
         * 
         */
        public Builder productId(Integer productId) {
            return productId(Output.of(productId));
        }

        /**
         * @param promocode Promo code to apply at creation.
         * 
         * @return builder
         * 
         */
        public Builder promocode(@Nullable Output<String> promocode) {
            $.promocode = promocode;
            return this;
        }

        /**
         * @param promocode Promo code to apply at creation.
         * 
         * @return builder
         * 
         */
        public Builder promocode(String promocode) {
            return promocode(Output.of(promocode));
        }

        /**
         * @param rebuildTrigger Change this value to rebuild the instance (destructive, reinstalls the OS).
         * 
         * @return builder
         * 
         */
        public Builder rebuildTrigger(@Nullable Output<String> rebuildTrigger) {
            $.rebuildTrigger = rebuildTrigger;
            return this;
        }

        /**
         * @param rebuildTrigger Change this value to rebuild the instance (destructive, reinstalls the OS).
         * 
         * @return builder
         * 
         */
        public Builder rebuildTrigger(String rebuildTrigger) {
            return rebuildTrigger(Output.of(rebuildTrigger));
        }

        /**
         * @param reserveAdditionalHoursTrigger Change this value to reserve 1 additional hour on an on-demand instance.
         * 
         * @return builder
         * 
         */
        public Builder reserveAdditionalHoursTrigger(@Nullable Output<String> reserveAdditionalHoursTrigger) {
            $.reserveAdditionalHoursTrigger = reserveAdditionalHoursTrigger;
            return this;
        }

        /**
         * @param reserveAdditionalHoursTrigger Change this value to reserve 1 additional hour on an on-demand instance.
         * 
         * @return builder
         * 
         */
        public Builder reserveAdditionalHoursTrigger(String reserveAdditionalHoursTrigger) {
            return reserveAdditionalHoursTrigger(Output.of(reserveAdditionalHoursTrigger));
        }

        /**
         * @param selectOs OS to install, from the product&#39;s select-os catalog.
         * 
         * @return builder
         * 
         */
        public Builder selectOs(Output<String> selectOs) {
            $.selectOs = selectOs;
            return this;
        }

        /**
         * @param selectOs OS to install, from the product&#39;s select-os catalog.
         * 
         * @return builder
         * 
         */
        public Builder selectOs(String selectOs) {
            return selectOs(Output.of(selectOs));
        }

        /**
         * @param serviceName Display name of the instance. Create-only, changing it replaces the instance.
         * 
         * @return builder
         * 
         */
        public Builder serviceName(@Nullable Output<String> serviceName) {
            $.serviceName = serviceName;
            return this;
        }

        /**
         * @param serviceName Display name of the instance. Create-only, changing it replaces the instance.
         * 
         * @return builder
         * 
         */
        public Builder serviceName(String serviceName) {
            return serviceName(Output.of(serviceName));
        }

        /**
         * @param sshAndConsoleUser SSH and console user for the instance.
         * 
         * @return builder
         * 
         */
        public Builder sshAndConsoleUser(Output<String> sshAndConsoleUser) {
            $.sshAndConsoleUser = sshAndConsoleUser;
            return this;
        }

        /**
         * @param sshAndConsoleUser SSH and console user for the instance.
         * 
         * @return builder
         * 
         */
        public Builder sshAndConsoleUser(String sshAndConsoleUser) {
            return sshAndConsoleUser(Output.of(sshAndConsoleUser));
        }

        /**
         * @param subscription Subscription billing mode (cycle-based). Exactly one of `subscription` or `onDemand` must be set.
         * 
         * @return builder
         * 
         */
        public Builder subscription(@Nullable Output<GpuSubscriptionArgsArgs> subscription) {
            $.subscription = subscription;
            return this;
        }

        /**
         * @param subscription Subscription billing mode (cycle-based). Exactly one of `subscription` or `onDemand` must be set.
         * 
         * @return builder
         * 
         */
        public Builder subscription(GpuSubscriptionArgsArgs subscription) {
            return subscription(Output.of(subscription));
        }

        public GpuInstanceArgs build() {
            if ($.consolePassword == null) {
                throw new MissingRequiredPropertyException("GpuInstanceArgs", "consolePassword");
            }
            if ($.keypairId == null) {
                throw new MissingRequiredPropertyException("GpuInstanceArgs", "keypairId");
            }
            $.payWithCreditCard = Codegen.booleanProp("payWithCreditCard").output().arg($.payWithCreditCard).def(true).getNullable();
            if ($.productId == null) {
                throw new MissingRequiredPropertyException("GpuInstanceArgs", "productId");
            }
            if ($.selectOs == null) {
                throw new MissingRequiredPropertyException("GpuInstanceArgs", "selectOs");
            }
            if ($.sshAndConsoleUser == null) {
                throw new MissingRequiredPropertyException("GpuInstanceArgs", "sshAndConsoleUser");
            }
            return $;
        }
    }

}
