// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio.ren.shirasaka_biznetgio;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;
import ren.shirasaka.biznetgio.ren.shirasaka_biznetgio.GpuKeypairArgs;
import ren.shirasaka.biznetgio.ren.shirasaka_biznetgio.Utilities;

@ResourceType(type="biznetgio:index:GpuKeypair")
public class GpuKeypair extends com.pulumi.resources.CustomResource {
    /**
     * Name of the keypair. Create-only, changing it replaces the keypair.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Name of the keypair. Create-only, changing it replaces the keypair.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Generated private key. Only returned at creation.
     * 
     */
    @Export(name="privateKey", refs={String.class}, tree="[0]")
    private Output<String> privateKey;

    /**
     * @return Generated private key. Only returned at creation.
     * 
     */
    public Output<String> privateKey() {
        return this.privateKey;
    }
    /**
     * Generated public key.
     * 
     */
    @Export(name="publicKey", refs={String.class}, tree="[0]")
    private Output<String> publicKey;

    /**
     * @return Generated public key.
     * 
     */
    public Output<String> publicKey() {
        return this.publicKey;
    }
    /**
     * Raw JSON of the keypair item from the list API.
     * 
     */
    @Export(name="raw", refs={String.class}, tree="[0]")
    private Output<String> raw;

    /**
     * @return Raw JSON of the keypair item from the list API.
     * 
     */
    public Output<String> raw() {
        return this.raw;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public GpuKeypair(java.lang.String name) {
        this(name, GpuKeypairArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public GpuKeypair(java.lang.String name, GpuKeypairArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public GpuKeypair(java.lang.String name, GpuKeypairArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("biznetgio:index:GpuKeypair", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private GpuKeypair(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("biznetgio:index:GpuKeypair", name, null, makeResourceOptions(options, id), false);
    }

    private static GpuKeypairArgs makeArgs(GpuKeypairArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? GpuKeypairArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/shirasakaren/pulumi-biznetgio")
            .additionalSecretOutputs(List.of(
                "privateKey",
                "raw"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static GpuKeypair get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new GpuKeypair(name, id, options);
    }
}
