// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio.ren.shirasaka_biznetgio;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NeoliteVmFromSnapshotArgs extends com.pulumi.resources.ResourceArgs {

    public static final NeoliteVmFromSnapshotArgs Empty = new NeoliteVmFromSnapshotArgs();

    /**
     * Password console saat create. Write-only: ga pernah di-refetch dari API.
     * 
     */
    @Import(name="consolePassword", required=true)
    private Output<String> consolePassword;

    /**
     * @return Password console saat create. Write-only: ga pernah di-refetch dari API.
     * 
     */
    public Output<String> consolePassword() {
        return this.consolePassword;
    }

    /**
     * Siklus billing: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
     * 
     */
    @Import(name="cycle", required=true)
    private Output<String> cycle;

    /**
     * @return Siklus billing: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
     * 
     */
    public Output<String> cycle() {
        return this.cycle;
    }

    /**
     * Deskripsi VM.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Deskripsi VM.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Id keypair dari `NeoliteKeypair`.
     * 
     */
    @Import(name="keypairId", required=true)
    private Output<Integer> keypairId;

    /**
     * @return Id keypair dari `NeoliteKeypair`.
     * 
     */
    public Output<Integer> keypairId() {
        return this.keypairId;
    }

    /**
     * Nama VM hasil restore.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Nama VM hasil restore.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * Bayar invoice pake kartu kredit saat order. Default true (auto-charge). Set false kalau mau ninggalin invoice unpaid di portal — resource bakal stuck Pending sampai dibayar.
     * 
     */
    @Import(name="payWithCreditCard")
    private @Nullable Output<Boolean> payWithCreditCard;

    /**
     * @return Bayar invoice pake kartu kredit saat order. Default true (auto-charge). Set false kalau mau ninggalin invoice unpaid di portal — resource bakal stuck Pending sampai dibayar.
     * 
     */
    public Optional<Output<Boolean>> payWithCreditCard() {
        return Optional.ofNullable(this.payWithCreditCard);
    }

    /**
     * Product id dari function `getProducts` atau portal.
     * 
     */
    @Import(name="productId", required=true)
    private Output<Integer> productId;

    /**
     * @return Product id dari function `getProducts` atau portal.
     * 
     */
    public Output<Integer> productId() {
        return this.productId;
    }

    /**
     * Kode promo saat order.
     * 
     */
    @Import(name="promocode")
    private @Nullable Output<String> promocode;

    /**
     * @return Kode promo saat order.
     * 
     */
    public Optional<Output<String>> promocode() {
        return Optional.ofNullable(this.promocode);
    }

    /**
     * Account id snapshot sumber, dari `NeoliteSnapshot`.
     * 
     */
    @Import(name="snapshotId", required=true)
    private Output<Integer> snapshotId;

    /**
     * @return Account id snapshot sumber, dari `NeoliteSnapshot`.
     * 
     */
    public Output<Integer> snapshotId() {
        return this.snapshotId;
    }

    /**
     * User SSH &amp; console yang dipasang saat create.
     * 
     */
    @Import(name="sshAndConsoleUser", required=true)
    private Output<String> sshAndConsoleUser;

    /**
     * @return User SSH &amp; console yang dipasang saat create.
     * 
     */
    public Output<String> sshAndConsoleUser() {
        return this.sshAndConsoleUser;
    }

    private NeoliteVmFromSnapshotArgs() {}

    private NeoliteVmFromSnapshotArgs(NeoliteVmFromSnapshotArgs $) {
        this.consolePassword = $.consolePassword;
        this.cycle = $.cycle;
        this.description = $.description;
        this.keypairId = $.keypairId;
        this.name = $.name;
        this.payWithCreditCard = $.payWithCreditCard;
        this.productId = $.productId;
        this.promocode = $.promocode;
        this.snapshotId = $.snapshotId;
        this.sshAndConsoleUser = $.sshAndConsoleUser;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NeoliteVmFromSnapshotArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NeoliteVmFromSnapshotArgs $;

        public Builder() {
            $ = new NeoliteVmFromSnapshotArgs();
        }

        public Builder(NeoliteVmFromSnapshotArgs defaults) {
            $ = new NeoliteVmFromSnapshotArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param consolePassword Password console saat create. Write-only: ga pernah di-refetch dari API.
         * 
         * @return builder
         * 
         */
        public Builder consolePassword(Output<String> consolePassword) {
            $.consolePassword = consolePassword;
            return this;
        }

        /**
         * @param consolePassword Password console saat create. Write-only: ga pernah di-refetch dari API.
         * 
         * @return builder
         * 
         */
        public Builder consolePassword(String consolePassword) {
            return consolePassword(Output.of(consolePassword));
        }

        /**
         * @param cycle Siklus billing: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
         * 
         * @return builder
         * 
         */
        public Builder cycle(Output<String> cycle) {
            $.cycle = cycle;
            return this;
        }

        /**
         * @param cycle Siklus billing: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
         * 
         * @return builder
         * 
         */
        public Builder cycle(String cycle) {
            return cycle(Output.of(cycle));
        }

        /**
         * @param description Deskripsi VM.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Deskripsi VM.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param keypairId Id keypair dari `NeoliteKeypair`.
         * 
         * @return builder
         * 
         */
        public Builder keypairId(Output<Integer> keypairId) {
            $.keypairId = keypairId;
            return this;
        }

        /**
         * @param keypairId Id keypair dari `NeoliteKeypair`.
         * 
         * @return builder
         * 
         */
        public Builder keypairId(Integer keypairId) {
            return keypairId(Output.of(keypairId));
        }

        /**
         * @param name Nama VM hasil restore.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Nama VM hasil restore.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param payWithCreditCard Bayar invoice pake kartu kredit saat order. Default true (auto-charge). Set false kalau mau ninggalin invoice unpaid di portal — resource bakal stuck Pending sampai dibayar.
         * 
         * @return builder
         * 
         */
        public Builder payWithCreditCard(@Nullable Output<Boolean> payWithCreditCard) {
            $.payWithCreditCard = payWithCreditCard;
            return this;
        }

        /**
         * @param payWithCreditCard Bayar invoice pake kartu kredit saat order. Default true (auto-charge). Set false kalau mau ninggalin invoice unpaid di portal — resource bakal stuck Pending sampai dibayar.
         * 
         * @return builder
         * 
         */
        public Builder payWithCreditCard(Boolean payWithCreditCard) {
            return payWithCreditCard(Output.of(payWithCreditCard));
        }

        /**
         * @param productId Product id dari function `getProducts` atau portal.
         * 
         * @return builder
         * 
         */
        public Builder productId(Output<Integer> productId) {
            $.productId = productId;
            return this;
        }

        /**
         * @param productId Product id dari function `getProducts` atau portal.
         * 
         * @return builder
         * 
         */
        public Builder productId(Integer productId) {
            return productId(Output.of(productId));
        }

        /**
         * @param promocode Kode promo saat order.
         * 
         * @return builder
         * 
         */
        public Builder promocode(@Nullable Output<String> promocode) {
            $.promocode = promocode;
            return this;
        }

        /**
         * @param promocode Kode promo saat order.
         * 
         * @return builder
         * 
         */
        public Builder promocode(String promocode) {
            return promocode(Output.of(promocode));
        }

        /**
         * @param snapshotId Account id snapshot sumber, dari `NeoliteSnapshot`.
         * 
         * @return builder
         * 
         */
        public Builder snapshotId(Output<Integer> snapshotId) {
            $.snapshotId = snapshotId;
            return this;
        }

        /**
         * @param snapshotId Account id snapshot sumber, dari `NeoliteSnapshot`.
         * 
         * @return builder
         * 
         */
        public Builder snapshotId(Integer snapshotId) {
            return snapshotId(Output.of(snapshotId));
        }

        /**
         * @param sshAndConsoleUser User SSH &amp; console yang dipasang saat create.
         * 
         * @return builder
         * 
         */
        public Builder sshAndConsoleUser(Output<String> sshAndConsoleUser) {
            $.sshAndConsoleUser = sshAndConsoleUser;
            return this;
        }

        /**
         * @param sshAndConsoleUser User SSH &amp; console yang dipasang saat create.
         * 
         * @return builder
         * 
         */
        public Builder sshAndConsoleUser(String sshAndConsoleUser) {
            return sshAndConsoleUser(Output.of(sshAndConsoleUser));
        }

        public NeoliteVmFromSnapshotArgs build() {
            if ($.consolePassword == null) {
                throw new MissingRequiredPropertyException("NeoliteVmFromSnapshotArgs", "consolePassword");
            }
            if ($.cycle == null) {
                throw new MissingRequiredPropertyException("NeoliteVmFromSnapshotArgs", "cycle");
            }
            $.description = Codegen.stringProp("description").output().arg($.description).def("").getNullable();
            if ($.keypairId == null) {
                throw new MissingRequiredPropertyException("NeoliteVmFromSnapshotArgs", "keypairId");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("NeoliteVmFromSnapshotArgs", "name");
            }
            $.payWithCreditCard = Codegen.booleanProp("payWithCreditCard").output().arg($.payWithCreditCard).def(true).getNullable();
            if ($.productId == null) {
                throw new MissingRequiredPropertyException("NeoliteVmFromSnapshotArgs", "productId");
            }
            $.promocode = Codegen.stringProp("promocode").output().arg($.promocode).def("").getNullable();
            if ($.snapshotId == null) {
                throw new MissingRequiredPropertyException("NeoliteVmFromSnapshotArgs", "snapshotId");
            }
            if ($.sshAndConsoleUser == null) {
                throw new MissingRequiredPropertyException("NeoliteVmFromSnapshotArgs", "sshAndConsoleUser");
            }
            return $;
        }
    }

}
