// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;


public final class NeoliteStorageUpgradeOptionsArgs extends com.pulumi.resources.InvokeArgs {

    public static final NeoliteStorageUpgradeOptionsArgs Empty = new NeoliteStorageUpgradeOptionsArgs();

    /**
     * Account id of the NEO Lite VM.
     * 
     */
    @Import(name="accountId", required=true)
    private Output<Integer> accountId;

    /**
     * @return Account id of the NEO Lite VM.
     * 
     */
    public Output<Integer> accountId() {
        return this.accountId;
    }

    private NeoliteStorageUpgradeOptionsArgs() {}

    private NeoliteStorageUpgradeOptionsArgs(NeoliteStorageUpgradeOptionsArgs $) {
        this.accountId = $.accountId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NeoliteStorageUpgradeOptionsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NeoliteStorageUpgradeOptionsArgs $;

        public Builder() {
            $ = new NeoliteStorageUpgradeOptionsArgs();
        }

        public Builder(NeoliteStorageUpgradeOptionsArgs defaults) {
            $ = new NeoliteStorageUpgradeOptionsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accountId Account id of the NEO Lite VM.
         * 
         * @return builder
         * 
         */
        public Builder accountId(Output<Integer> accountId) {
            $.accountId = accountId;
            return this;
        }

        /**
         * @param accountId Account id of the NEO Lite VM.
         * 
         * @return builder
         * 
         */
        public Builder accountId(Integer accountId) {
            return accountId(Output.of(accountId));
        }

        public NeoliteStorageUpgradeOptionsArgs build() {
            if ($.accountId == null) {
                throw new MissingRequiredPropertyException("NeoliteStorageUpgradeOptionsArgs", "accountId");
            }
            return $;
        }
    }

}
