// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Shirasakaren.Biznetgio.Outputs
{

    [OutputType]
    public sealed class NeolitePlanOptions
    {
        public readonly int AllowDowngrade;
        public readonly int Cores;
        public readonly int Memory;
        public readonly string Type;

        [OutputConstructor]
        private NeolitePlanOptions(
            int allowDowngrade,

            int cores,

            int memory,

            string type)
        {
            AllowDowngrade = allowDowngrade;
            Cores = cores;
            Memory = memory;
            Type = type;
        }
    }
}
