// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.biznetgio.biznetgio.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class BaremetalRebuildOsListResult {
    /**
     * @return Valid OS values for the `rebuildOs` input of Baremetal, from `GET /baremetals/{account_id}/rebuild/oss`.
     * 
     */
    private List<String> oss;
    /**
     * @return Raw JSON of the full list response.
     * 
     */
    private String raw;

    private BaremetalRebuildOsListResult() {}
    /**
     * @return Valid OS values for the `rebuildOs` input of Baremetal, from `GET /baremetals/{account_id}/rebuild/oss`.
     * 
     */
    public List<String> oss() {
        return this.oss;
    }
    /**
     * @return Raw JSON of the full list response.
     * 
     */
    public String raw() {
        return this.raw;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(BaremetalRebuildOsListResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> oss;
        private String raw;
        public Builder() {}
        public Builder(BaremetalRebuildOsListResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.oss = defaults.oss;
    	      this.raw = defaults.raw;
        }

        @CustomType.Setter
        public Builder oss(List<String> oss) {
            if (oss == null) {
              throw new MissingRequiredPropertyException("BaremetalRebuildOsListResult", "oss");
            }
            this.oss = oss;
            return this;
        }
        public Builder oss(String... oss) {
            return oss(List.of(oss));
        }
        @CustomType.Setter
        public Builder raw(String raw) {
            if (raw == null) {
              throw new MissingRequiredPropertyException("BaremetalRebuildOsListResult", "raw");
            }
            this.raw = raw;
            return this;
        }
        public BaremetalRebuildOsListResult build() {
            final var _resultValue = new BaremetalRebuildOsListResult();
            _resultValue.oss = oss;
            _resultValue.raw = raw;
            return _resultValue;
        }
    }
}
