// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.biznetgio.biznetgio.outputs;

import com.biznetgio.biznetgio.outputs.NeolitePlanComponent;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class NeolitePlanBilling {
    private List<NeolitePlanComponent> components;
    private String cycle;
    private String label;
    private Integer price;

    private NeolitePlanBilling() {}
    public List<NeolitePlanComponent> components() {
        return this.components;
    }
    public String cycle() {
        return this.cycle;
    }
    public String label() {
        return this.label;
    }
    public Integer price() {
        return this.price;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NeolitePlanBilling defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<NeolitePlanComponent> components;
        private String cycle;
        private String label;
        private Integer price;
        public Builder() {}
        public Builder(NeolitePlanBilling defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.components = defaults.components;
    	      this.cycle = defaults.cycle;
    	      this.label = defaults.label;
    	      this.price = defaults.price;
        }

        @CustomType.Setter
        public Builder components(List<NeolitePlanComponent> components) {
            if (components == null) {
              throw new MissingRequiredPropertyException("NeolitePlanBilling", "components");
            }
            this.components = components;
            return this;
        }
        public Builder components(NeolitePlanComponent... components) {
            return components(List.of(components));
        }
        @CustomType.Setter
        public Builder cycle(String cycle) {
            if (cycle == null) {
              throw new MissingRequiredPropertyException("NeolitePlanBilling", "cycle");
            }
            this.cycle = cycle;
            return this;
        }
        @CustomType.Setter
        public Builder label(String label) {
            if (label == null) {
              throw new MissingRequiredPropertyException("NeolitePlanBilling", "label");
            }
            this.label = label;
            return this;
        }
        @CustomType.Setter
        public Builder price(Integer price) {
            if (price == null) {
              throw new MissingRequiredPropertyException("NeolitePlanBilling", "price");
            }
            this.price = price;
            return this;
        }
        public NeolitePlanBilling build() {
            final var _resultValue = new NeolitePlanBilling();
            _resultValue.components = components;
            _resultValue.cycle = cycle;
            _resultValue.label = label;
            _resultValue.price = price;
            return _resultValue;
        }
    }
}
