// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumibiznetgio

import (
	"context"
	"reflect"

	"errors"
	"github.com/biznetgio/pulumi-biznetgio/sdk/go/pulumi-biznetgio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type BaremetalAdditionalIp struct {
	pulumi.CustomResourceState

	// Creation timestamp (alias of created_at/date_created).
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Billing cycle, e.g. `m` for monthly or `a` for annual.
	Cycle pulumi.StringOutput `pulumi:"cycle"`
	// Assigned IP address, when present in the response.
	IpAddress pulumi.StringOutput `pulumi:"ipAddress"`
	// Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
	PayWithCreditCard pulumi.BoolPtrOutput `pulumi:"payWithCreditCard"`
	// Product id from `GET /baremetal-additional-ips/products`.
	ProductId pulumi.IntOutput `pulumi:"productId"`
	// Promo code to apply at creation.
	Promocode pulumi.StringPtrOutput `pulumi:"promocode"`
	// Raw JSON of the last read response, for anything not modeled yet.
	Raw pulumi.StringOutput `pulumi:"raw"`
	// Datacenter region; valid list from `GET /baremetal-additional-ips/regions`. Defaults to `wjv-1`. Create-only, changing it replaces the IP.
	Region pulumi.StringPtrOutput `pulumi:"region"`
	// Current status of the IP (e.g. Active, Pending, Suspended, Terminated).
	Status pulumi.StringOutput `pulumi:"status"`
}

// NewBaremetalAdditionalIp registers a new resource with the given unique name, arguments, and options.
func NewBaremetalAdditionalIp(ctx *pulumi.Context,
	name string, args *BaremetalAdditionalIpArgs, opts ...pulumi.ResourceOption) (*BaremetalAdditionalIp, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Cycle == nil {
		return nil, errors.New("invalid value for required argument 'Cycle'")
	}
	if args.ProductId == nil {
		return nil, errors.New("invalid value for required argument 'ProductId'")
	}
	if args.PayWithCreditCard == nil {
		args.PayWithCreditCard = pulumi.BoolPtr(true)
	}
	if args.Region == nil {
		args.Region = pulumi.StringPtr("wjv-1")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"raw",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource BaremetalAdditionalIp
	err := ctx.RegisterResource("biznetgio:index:BaremetalAdditionalIp", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBaremetalAdditionalIp gets an existing BaremetalAdditionalIp resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBaremetalAdditionalIp(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *BaremetalAdditionalIpState, opts ...pulumi.ResourceOption) (*BaremetalAdditionalIp, error) {
	var resource BaremetalAdditionalIp
	err := ctx.ReadResource("biznetgio:index:BaremetalAdditionalIp", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering BaremetalAdditionalIp resources.
type baremetalAdditionalIpState struct {
}

type BaremetalAdditionalIpState struct {
}

func (BaremetalAdditionalIpState) ElementType() reflect.Type {
	return reflect.TypeOf((*baremetalAdditionalIpState)(nil)).Elem()
}

type baremetalAdditionalIpArgs struct {
	// Billing cycle, e.g. `m` for monthly or `a` for annual.
	Cycle string `pulumi:"cycle"`
	// Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
	PayWithCreditCard *bool `pulumi:"payWithCreditCard"`
	// Product id from `GET /baremetal-additional-ips/products`.
	ProductId int `pulumi:"productId"`
	// Promo code to apply at creation.
	Promocode *string `pulumi:"promocode"`
	// Datacenter region; valid list from `GET /baremetal-additional-ips/regions`. Defaults to `wjv-1`. Create-only, changing it replaces the IP.
	Region *string `pulumi:"region"`
}

// The set of arguments for constructing a BaremetalAdditionalIp resource.
type BaremetalAdditionalIpArgs struct {
	// Billing cycle, e.g. `m` for monthly or `a` for annual.
	Cycle pulumi.StringInput
	// Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
	PayWithCreditCard pulumi.BoolPtrInput
	// Product id from `GET /baremetal-additional-ips/products`.
	ProductId pulumi.IntInput
	// Promo code to apply at creation.
	Promocode pulumi.StringPtrInput
	// Datacenter region; valid list from `GET /baremetal-additional-ips/regions`. Defaults to `wjv-1`. Create-only, changing it replaces the IP.
	Region pulumi.StringPtrInput
}

func (BaremetalAdditionalIpArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*baremetalAdditionalIpArgs)(nil)).Elem()
}

type BaremetalAdditionalIpInput interface {
	pulumi.Input

	ToBaremetalAdditionalIpOutput() BaremetalAdditionalIpOutput
	ToBaremetalAdditionalIpOutputWithContext(ctx context.Context) BaremetalAdditionalIpOutput
}

func (*BaremetalAdditionalIp) ElementType() reflect.Type {
	return reflect.TypeOf((**BaremetalAdditionalIp)(nil)).Elem()
}

func (i *BaremetalAdditionalIp) ToBaremetalAdditionalIpOutput() BaremetalAdditionalIpOutput {
	return i.ToBaremetalAdditionalIpOutputWithContext(context.Background())
}

func (i *BaremetalAdditionalIp) ToBaremetalAdditionalIpOutputWithContext(ctx context.Context) BaremetalAdditionalIpOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BaremetalAdditionalIpOutput)
}

type BaremetalAdditionalIpOutput struct{ *pulumi.OutputState }

func (BaremetalAdditionalIpOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**BaremetalAdditionalIp)(nil)).Elem()
}

func (o BaremetalAdditionalIpOutput) ToBaremetalAdditionalIpOutput() BaremetalAdditionalIpOutput {
	return o
}

func (o BaremetalAdditionalIpOutput) ToBaremetalAdditionalIpOutputWithContext(ctx context.Context) BaremetalAdditionalIpOutput {
	return o
}

// Creation timestamp (alias of created_at/date_created).
func (o BaremetalAdditionalIpOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *BaremetalAdditionalIp) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Billing cycle, e.g. `m` for monthly or `a` for annual.
func (o BaremetalAdditionalIpOutput) Cycle() pulumi.StringOutput {
	return o.ApplyT(func(v *BaremetalAdditionalIp) pulumi.StringOutput { return v.Cycle }).(pulumi.StringOutput)
}

// Assigned IP address, when present in the response.
func (o BaremetalAdditionalIpOutput) IpAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *BaremetalAdditionalIp) pulumi.StringOutput { return v.IpAddress }).(pulumi.StringOutput)
}

// Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
func (o BaremetalAdditionalIpOutput) PayWithCreditCard() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *BaremetalAdditionalIp) pulumi.BoolPtrOutput { return v.PayWithCreditCard }).(pulumi.BoolPtrOutput)
}

// Product id from `GET /baremetal-additional-ips/products`.
func (o BaremetalAdditionalIpOutput) ProductId() pulumi.IntOutput {
	return o.ApplyT(func(v *BaremetalAdditionalIp) pulumi.IntOutput { return v.ProductId }).(pulumi.IntOutput)
}

// Promo code to apply at creation.
func (o BaremetalAdditionalIpOutput) Promocode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BaremetalAdditionalIp) pulumi.StringPtrOutput { return v.Promocode }).(pulumi.StringPtrOutput)
}

// Raw JSON of the last read response, for anything not modeled yet.
func (o BaremetalAdditionalIpOutput) Raw() pulumi.StringOutput {
	return o.ApplyT(func(v *BaremetalAdditionalIp) pulumi.StringOutput { return v.Raw }).(pulumi.StringOutput)
}

// Datacenter region; valid list from `GET /baremetal-additional-ips/regions`. Defaults to `wjv-1`. Create-only, changing it replaces the IP.
func (o BaremetalAdditionalIpOutput) Region() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BaremetalAdditionalIp) pulumi.StringPtrOutput { return v.Region }).(pulumi.StringPtrOutput)
}

// Current status of the IP (e.g. Active, Pending, Suspended, Terminated).
func (o BaremetalAdditionalIpOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *BaremetalAdditionalIp) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BaremetalAdditionalIpInput)(nil)).Elem(), &BaremetalAdditionalIp{})
	pulumi.RegisterOutputType(BaremetalAdditionalIpOutput{})
}
