// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumibiznetgio

import (
	"context"
	"reflect"

	"github.com/biznetgio/pulumi-biznetgio/sdk/go/pulumi-biznetgio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func BaremetalRebuildOsList(ctx *pulumi.Context, args *BaremetalRebuildOsListArgs, opts ...pulumi.InvokeOption) (*BaremetalRebuildOsListResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv BaremetalRebuildOsListResult
	err := ctx.Invoke("biznetgio:index:baremetalRebuildOsList", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type BaremetalRebuildOsListArgs struct {
	// Account id of the baremetal to list rebuild OS options for.
	AccountId int `pulumi:"accountId"`
}

type BaremetalRebuildOsListResult struct {
	// Valid OS values for the `rebuildOs` input of Baremetal, from `GET /baremetals/{account_id}/rebuild/oss`.
	Oss []string `pulumi:"oss"`
	// Raw JSON of the full list response.
	Raw string `pulumi:"raw"`
}

func BaremetalRebuildOsListOutput(ctx *pulumi.Context, args BaremetalRebuildOsListOutputArgs, opts ...pulumi.InvokeOption) BaremetalRebuildOsListResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (BaremetalRebuildOsListResultOutput, error) {
			args := v.(BaremetalRebuildOsListArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("biznetgio:index:baremetalRebuildOsList", args, BaremetalRebuildOsListResultOutput{}, options).(BaremetalRebuildOsListResultOutput), nil
		}).(BaremetalRebuildOsListResultOutput)
}

type BaremetalRebuildOsListOutputArgs struct {
	// Account id of the baremetal to list rebuild OS options for.
	AccountId pulumi.IntInput `pulumi:"accountId"`
}

func (BaremetalRebuildOsListOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*BaremetalRebuildOsListArgs)(nil)).Elem()
}

type BaremetalRebuildOsListResultOutput struct{ *pulumi.OutputState }

func (BaremetalRebuildOsListResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*BaremetalRebuildOsListResult)(nil)).Elem()
}

func (o BaremetalRebuildOsListResultOutput) ToBaremetalRebuildOsListResultOutput() BaremetalRebuildOsListResultOutput {
	return o
}

func (o BaremetalRebuildOsListResultOutput) ToBaremetalRebuildOsListResultOutputWithContext(ctx context.Context) BaremetalRebuildOsListResultOutput {
	return o
}

// Valid OS values for the `rebuildOs` input of Baremetal, from `GET /baremetals/{account_id}/rebuild/oss`.
func (o BaremetalRebuildOsListResultOutput) Oss() pulumi.StringArrayOutput {
	return o.ApplyT(func(v BaremetalRebuildOsListResult) []string { return v.Oss }).(pulumi.StringArrayOutput)
}

// Raw JSON of the full list response.
func (o BaremetalRebuildOsListResultOutput) Raw() pulumi.StringOutput {
	return o.ApplyT(func(v BaremetalRebuildOsListResult) string { return v.Raw }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(BaremetalRebuildOsListResultOutput{})
}
