// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumibiznetgio

import (
	"context"
	"reflect"

	"github.com/biznetgio/pulumi-biznetgio/sdk/go/pulumi-biznetgio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func BaremetalProducts(ctx *pulumi.Context, args *BaremetalProductsArgs, opts ...pulumi.InvokeOption) (*BaremetalProductsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv BaremetalProductsResult
	err := ctx.Invoke("biznetgio:index:baremetalProducts", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type BaremetalProductsArgs struct {
}

type BaremetalProductsResult struct {
	// Available baremetal products from `GET /baremetals/products`.
	Products []BaremetalProduct `pulumi:"products"`
	// Raw JSON of the full list response.
	Raw string `pulumi:"raw"`
}

func BaremetalProductsOutput(ctx *pulumi.Context, args BaremetalProductsOutputArgs, opts ...pulumi.InvokeOption) BaremetalProductsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (BaremetalProductsResultOutput, error) {
			args := v.(BaremetalProductsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("biznetgio:index:baremetalProducts", args, BaremetalProductsResultOutput{}, options).(BaremetalProductsResultOutput), nil
		}).(BaremetalProductsResultOutput)
}

type BaremetalProductsOutputArgs struct {
}

func (BaremetalProductsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*BaremetalProductsArgs)(nil)).Elem()
}

type BaremetalProductsResultOutput struct{ *pulumi.OutputState }

func (BaremetalProductsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*BaremetalProductsResult)(nil)).Elem()
}

func (o BaremetalProductsResultOutput) ToBaremetalProductsResultOutput() BaremetalProductsResultOutput {
	return o
}

func (o BaremetalProductsResultOutput) ToBaremetalProductsResultOutputWithContext(ctx context.Context) BaremetalProductsResultOutput {
	return o
}

// Available baremetal products from `GET /baremetals/products`.
func (o BaremetalProductsResultOutput) Products() BaremetalProductArrayOutput {
	return o.ApplyT(func(v BaremetalProductsResult) []BaremetalProduct { return v.Products }).(BaremetalProductArrayOutput)
}

// Raw JSON of the full list response.
func (o BaremetalProductsResultOutput) Raw() pulumi.StringOutput {
	return o.ApplyT(func(v BaremetalProductsResult) string { return v.Raw }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(BaremetalProductsResultOutput{})
}
