// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumibiznetgio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/shirasakaren/pulumi-biznetgio/sdk/go/pulumi-biznetgio/internal"
)

type BaremetalElasticStorage struct {
	pulumi.CustomResourceState

	// Creation timestamp (alias of created_at/date_created).
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Billing cycle, e.g. `m` for monthly or `a` for annual. Create-only, changing it replaces the storage.
	Cycle pulumi.StringOutput `pulumi:"cycle"`
	// Account id of the target baremetal. Can only be set at creation (no re-attach endpoint).
	MetalAccountId pulumi.IntOutput `pulumi:"metalAccountId"`
	// Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
	PayWithCreditCard pulumi.BoolPtrOutput `pulumi:"payWithCreditCard"`
	// Product id from `GET /baremetal-neo-elastic-storages/products`. Changing it triggers change-package (`POST .../{account_id}`).
	ProductId pulumi.IntOutput `pulumi:"productId"`
	// Promo code to apply at creation.
	Promocode pulumi.StringPtrOutput `pulumi:"promocode"`
	// Raw JSON of the last read response, for anything not modeled yet.
	Raw pulumi.StringOutput `pulumi:"raw"`
	// Storage size in GB. Defaults to 100. Changing it triggers upgrade (`PUT .../{account_id}`) - grow-only, shrinking is rejected by the API.
	Size pulumi.IntPtrOutput `pulumi:"size"`
	// Current status of the storage (e.g. Active, Pending, Suspended, Terminated).
	Status pulumi.StringOutput `pulumi:"status"`
	// Name of the storage. Create-only, changing it replaces the storage.
	StorageName pulumi.StringOutput `pulumi:"storageName"`
}

// NewBaremetalElasticStorage registers a new resource with the given unique name, arguments, and options.
func NewBaremetalElasticStorage(ctx *pulumi.Context,
	name string, args *BaremetalElasticStorageArgs, opts ...pulumi.ResourceOption) (*BaremetalElasticStorage, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Cycle == nil {
		return nil, errors.New("invalid value for required argument 'Cycle'")
	}
	if args.MetalAccountId == nil {
		return nil, errors.New("invalid value for required argument 'MetalAccountId'")
	}
	if args.ProductId == nil {
		return nil, errors.New("invalid value for required argument 'ProductId'")
	}
	if args.StorageName == nil {
		return nil, errors.New("invalid value for required argument 'StorageName'")
	}
	if args.PayWithCreditCard == nil {
		args.PayWithCreditCard = pulumi.BoolPtr(true)
	}
	if args.Size == nil {
		args.Size = pulumi.IntPtr(100)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"raw",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource BaremetalElasticStorage
	err := ctx.RegisterResource("biznetgio:index:BaremetalElasticStorage", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBaremetalElasticStorage gets an existing BaremetalElasticStorage resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBaremetalElasticStorage(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *BaremetalElasticStorageState, opts ...pulumi.ResourceOption) (*BaremetalElasticStorage, error) {
	var resource BaremetalElasticStorage
	err := ctx.ReadResource("biznetgio:index:BaremetalElasticStorage", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering BaremetalElasticStorage resources.
type baremetalElasticStorageState struct {
}

type BaremetalElasticStorageState struct {
}

func (BaremetalElasticStorageState) ElementType() reflect.Type {
	return reflect.TypeOf((*baremetalElasticStorageState)(nil)).Elem()
}

type baremetalElasticStorageArgs struct {
	// Billing cycle, e.g. `m` for monthly or `a` for annual. Create-only, changing it replaces the storage.
	Cycle string `pulumi:"cycle"`
	// Account id of the target baremetal. Can only be set at creation (no re-attach endpoint).
	MetalAccountId int `pulumi:"metalAccountId"`
	// Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
	PayWithCreditCard *bool `pulumi:"payWithCreditCard"`
	// Product id from `GET /baremetal-neo-elastic-storages/products`. Changing it triggers change-package (`POST .../{account_id}`).
	ProductId int `pulumi:"productId"`
	// Promo code to apply at creation.
	Promocode *string `pulumi:"promocode"`
	// Storage size in GB. Defaults to 100. Changing it triggers upgrade (`PUT .../{account_id}`) - grow-only, shrinking is rejected by the API.
	Size *int `pulumi:"size"`
	// Name of the storage. Create-only, changing it replaces the storage.
	StorageName string `pulumi:"storageName"`
}

// The set of arguments for constructing a BaremetalElasticStorage resource.
type BaremetalElasticStorageArgs struct {
	// Billing cycle, e.g. `m` for monthly or `a` for annual. Create-only, changing it replaces the storage.
	Cycle pulumi.StringInput
	// Account id of the target baremetal. Can only be set at creation (no re-attach endpoint).
	MetalAccountId pulumi.IntInput
	// Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
	PayWithCreditCard pulumi.BoolPtrInput
	// Product id from `GET /baremetal-neo-elastic-storages/products`. Changing it triggers change-package (`POST .../{account_id}`).
	ProductId pulumi.IntInput
	// Promo code to apply at creation.
	Promocode pulumi.StringPtrInput
	// Storage size in GB. Defaults to 100. Changing it triggers upgrade (`PUT .../{account_id}`) - grow-only, shrinking is rejected by the API.
	Size pulumi.IntPtrInput
	// Name of the storage. Create-only, changing it replaces the storage.
	StorageName pulumi.StringInput
}

func (BaremetalElasticStorageArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*baremetalElasticStorageArgs)(nil)).Elem()
}

type BaremetalElasticStorageInput interface {
	pulumi.Input

	ToBaremetalElasticStorageOutput() BaremetalElasticStorageOutput
	ToBaremetalElasticStorageOutputWithContext(ctx context.Context) BaremetalElasticStorageOutput
}

func (*BaremetalElasticStorage) ElementType() reflect.Type {
	return reflect.TypeOf((**BaremetalElasticStorage)(nil)).Elem()
}

func (i *BaremetalElasticStorage) ToBaremetalElasticStorageOutput() BaremetalElasticStorageOutput {
	return i.ToBaremetalElasticStorageOutputWithContext(context.Background())
}

func (i *BaremetalElasticStorage) ToBaremetalElasticStorageOutputWithContext(ctx context.Context) BaremetalElasticStorageOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BaremetalElasticStorageOutput)
}

type BaremetalElasticStorageOutput struct{ *pulumi.OutputState }

func (BaremetalElasticStorageOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**BaremetalElasticStorage)(nil)).Elem()
}

func (o BaremetalElasticStorageOutput) ToBaremetalElasticStorageOutput() BaremetalElasticStorageOutput {
	return o
}

func (o BaremetalElasticStorageOutput) ToBaremetalElasticStorageOutputWithContext(ctx context.Context) BaremetalElasticStorageOutput {
	return o
}

// Creation timestamp (alias of created_at/date_created).
func (o BaremetalElasticStorageOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *BaremetalElasticStorage) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Billing cycle, e.g. `m` for monthly or `a` for annual. Create-only, changing it replaces the storage.
func (o BaremetalElasticStorageOutput) Cycle() pulumi.StringOutput {
	return o.ApplyT(func(v *BaremetalElasticStorage) pulumi.StringOutput { return v.Cycle }).(pulumi.StringOutput)
}

// Account id of the target baremetal. Can only be set at creation (no re-attach endpoint).
func (o BaremetalElasticStorageOutput) MetalAccountId() pulumi.IntOutput {
	return o.ApplyT(func(v *BaremetalElasticStorage) pulumi.IntOutput { return v.MetalAccountId }).(pulumi.IntOutput)
}

// Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
func (o BaremetalElasticStorageOutput) PayWithCreditCard() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *BaremetalElasticStorage) pulumi.BoolPtrOutput { return v.PayWithCreditCard }).(pulumi.BoolPtrOutput)
}

// Product id from `GET /baremetal-neo-elastic-storages/products`. Changing it triggers change-package (`POST .../{account_id}`).
func (o BaremetalElasticStorageOutput) ProductId() pulumi.IntOutput {
	return o.ApplyT(func(v *BaremetalElasticStorage) pulumi.IntOutput { return v.ProductId }).(pulumi.IntOutput)
}

// Promo code to apply at creation.
func (o BaremetalElasticStorageOutput) Promocode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BaremetalElasticStorage) pulumi.StringPtrOutput { return v.Promocode }).(pulumi.StringPtrOutput)
}

// Raw JSON of the last read response, for anything not modeled yet.
func (o BaremetalElasticStorageOutput) Raw() pulumi.StringOutput {
	return o.ApplyT(func(v *BaremetalElasticStorage) pulumi.StringOutput { return v.Raw }).(pulumi.StringOutput)
}

// Storage size in GB. Defaults to 100. Changing it triggers upgrade (`PUT .../{account_id}`) - grow-only, shrinking is rejected by the API.
func (o BaremetalElasticStorageOutput) Size() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *BaremetalElasticStorage) pulumi.IntPtrOutput { return v.Size }).(pulumi.IntPtrOutput)
}

// Current status of the storage (e.g. Active, Pending, Suspended, Terminated).
func (o BaremetalElasticStorageOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *BaremetalElasticStorage) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Name of the storage. Create-only, changing it replaces the storage.
func (o BaremetalElasticStorageOutput) StorageName() pulumi.StringOutput {
	return o.ApplyT(func(v *BaremetalElasticStorage) pulumi.StringOutput { return v.StorageName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BaremetalElasticStorageInput)(nil)).Elem(), &BaremetalElasticStorage{})
	pulumi.RegisterOutputType(BaremetalElasticStorageOutput{})
}
