// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumibiznetgio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/shirasakaren/pulumi-biznetgio/sdk/go/pulumi-biznetgio/internal"
)

type Baremetal struct {
	pulumi.CustomResourceState

	// Creation timestamp (alias of created_at/date_created).
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Billing cycle, e.g. `m` for monthly or `a` for annual.
	Cycle pulumi.StringOutput `pulumi:"cycle"`
	// Public IP address of the server, when present.
	IpAddress pulumi.StringOutput `pulumi:"ipAddress"`
	// Baremetal keypair id, from BaremetalKeypair. The baremetal keypair pool is separate from neolite/gpu.
	KeypairId pulumi.IntOutput `pulumi:"keypairId"`
	// Display name of the server. The only field updatable in place.
	Label pulumi.StringOutput `pulumi:"label"`
	// Order id from the creation response.
	OrderId pulumi.StringOutput `pulumi:"orderId"`
	// Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
	PayWithCreditCard pulumi.BoolPtrOutput `pulumi:"payWithCreditCard"`
	// Power state of the server: `on` or `off`. Only fires an API call when the value changes.
	PowerState pulumi.StringPtrOutput `pulumi:"powerState"`
	// Product id from the baremetal products function.
	ProductId pulumi.IntOutput `pulumi:"productId"`
	// Promo code to apply at creation.
	Promocode pulumi.StringPtrOutput `pulumi:"promocode"`
	// Number of public IPs to request (1 = with public IP). Defaults to 1. Create-only, changing it replaces the instance.
	PublicIp pulumi.IntPtrOutput `pulumi:"publicIp"`
	// Raw JSON of the last read response, for anything not modeled yet.
	Raw pulumi.StringOutput `pulumi:"raw"`
	// Change this value to rebuild the instance (destructive, wipes the OS) via `PUT /baremetals/{account_id}/rebuild`. Valid OS list comes from the rebuildOsList function.
	RebuildOs pulumi.StringPtrOutput `pulumi:"rebuildOs"`
	// Change this value to trigger a one-shot reset/reboot. The reset is an action, not a stable state.
	ResetTrigger pulumi.StringPtrOutput `pulumi:"resetTrigger"`
	// OS to install at creation, from `GET /baremetals/products/{product_id}/oss`. Defaults to `ubuntu-22`. Create-only, changing it replaces the instance.
	SelectOs pulumi.StringPtrOutput `pulumi:"selectOs"`
	// Current status of the server.
	Status pulumi.StringOutput `pulumi:"status"`
}

// NewBaremetal registers a new resource with the given unique name, arguments, and options.
func NewBaremetal(ctx *pulumi.Context,
	name string, args *BaremetalArgs, opts ...pulumi.ResourceOption) (*Baremetal, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Cycle == nil {
		return nil, errors.New("invalid value for required argument 'Cycle'")
	}
	if args.KeypairId == nil {
		return nil, errors.New("invalid value for required argument 'KeypairId'")
	}
	if args.Label == nil {
		return nil, errors.New("invalid value for required argument 'Label'")
	}
	if args.ProductId == nil {
		return nil, errors.New("invalid value for required argument 'ProductId'")
	}
	if args.PayWithCreditCard == nil {
		args.PayWithCreditCard = pulumi.BoolPtr(true)
	}
	if args.PublicIp == nil {
		args.PublicIp = pulumi.IntPtr(1)
	}
	if args.SelectOs == nil {
		args.SelectOs = pulumi.StringPtr("ubuntu-22")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"raw",
	})
	opts = append(opts, secrets)
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"cycle",
		"keypairId",
		"payWithCreditCard",
		"productId",
		"promocode",
		"publicIp",
		"selectOs",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Baremetal
	err := ctx.RegisterResource("biznetgio:index:Baremetal", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBaremetal gets an existing Baremetal resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBaremetal(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *BaremetalState, opts ...pulumi.ResourceOption) (*Baremetal, error) {
	var resource Baremetal
	err := ctx.ReadResource("biznetgio:index:Baremetal", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Baremetal resources.
type baremetalState struct {
}

type BaremetalState struct {
}

func (BaremetalState) ElementType() reflect.Type {
	return reflect.TypeOf((*baremetalState)(nil)).Elem()
}

type baremetalArgs struct {
	// Billing cycle, e.g. `m` for monthly or `a` for annual.
	Cycle string `pulumi:"cycle"`
	// Baremetal keypair id, from BaremetalKeypair. The baremetal keypair pool is separate from neolite/gpu.
	KeypairId int `pulumi:"keypairId"`
	// Display name of the server. The only field updatable in place.
	Label string `pulumi:"label"`
	// Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
	PayWithCreditCard *bool `pulumi:"payWithCreditCard"`
	// Power state of the server: `on` or `off`. Only fires an API call when the value changes.
	PowerState *string `pulumi:"powerState"`
	// Product id from the baremetal products function.
	ProductId int `pulumi:"productId"`
	// Promo code to apply at creation.
	Promocode *string `pulumi:"promocode"`
	// Number of public IPs to request (1 = with public IP). Defaults to 1. Create-only, changing it replaces the instance.
	PublicIp *int `pulumi:"publicIp"`
	// Change this value to rebuild the instance (destructive, wipes the OS) via `PUT /baremetals/{account_id}/rebuild`. Valid OS list comes from the rebuildOsList function.
	RebuildOs *string `pulumi:"rebuildOs"`
	// Change this value to trigger a one-shot reset/reboot. The reset is an action, not a stable state.
	ResetTrigger *string `pulumi:"resetTrigger"`
	// OS to install at creation, from `GET /baremetals/products/{product_id}/oss`. Defaults to `ubuntu-22`. Create-only, changing it replaces the instance.
	SelectOs *string `pulumi:"selectOs"`
}

// The set of arguments for constructing a Baremetal resource.
type BaremetalArgs struct {
	// Billing cycle, e.g. `m` for monthly or `a` for annual.
	Cycle pulumi.StringInput
	// Baremetal keypair id, from BaremetalKeypair. The baremetal keypair pool is separate from neolite/gpu.
	KeypairId pulumi.IntInput
	// Display name of the server. The only field updatable in place.
	Label pulumi.StringInput
	// Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
	PayWithCreditCard pulumi.BoolPtrInput
	// Power state of the server: `on` or `off`. Only fires an API call when the value changes.
	PowerState pulumi.StringPtrInput
	// Product id from the baremetal products function.
	ProductId pulumi.IntInput
	// Promo code to apply at creation.
	Promocode pulumi.StringPtrInput
	// Number of public IPs to request (1 = with public IP). Defaults to 1. Create-only, changing it replaces the instance.
	PublicIp pulumi.IntPtrInput
	// Change this value to rebuild the instance (destructive, wipes the OS) via `PUT /baremetals/{account_id}/rebuild`. Valid OS list comes from the rebuildOsList function.
	RebuildOs pulumi.StringPtrInput
	// Change this value to trigger a one-shot reset/reboot. The reset is an action, not a stable state.
	ResetTrigger pulumi.StringPtrInput
	// OS to install at creation, from `GET /baremetals/products/{product_id}/oss`. Defaults to `ubuntu-22`. Create-only, changing it replaces the instance.
	SelectOs pulumi.StringPtrInput
}

func (BaremetalArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*baremetalArgs)(nil)).Elem()
}

type BaremetalInput interface {
	pulumi.Input

	ToBaremetalOutput() BaremetalOutput
	ToBaremetalOutputWithContext(ctx context.Context) BaremetalOutput
}

func (*Baremetal) ElementType() reflect.Type {
	return reflect.TypeOf((**Baremetal)(nil)).Elem()
}

func (i *Baremetal) ToBaremetalOutput() BaremetalOutput {
	return i.ToBaremetalOutputWithContext(context.Background())
}

func (i *Baremetal) ToBaremetalOutputWithContext(ctx context.Context) BaremetalOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BaremetalOutput)
}

type BaremetalOutput struct{ *pulumi.OutputState }

func (BaremetalOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Baremetal)(nil)).Elem()
}

func (o BaremetalOutput) ToBaremetalOutput() BaremetalOutput {
	return o
}

func (o BaremetalOutput) ToBaremetalOutputWithContext(ctx context.Context) BaremetalOutput {
	return o
}

// Creation timestamp (alias of created_at/date_created).
func (o BaremetalOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Baremetal) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Billing cycle, e.g. `m` for monthly or `a` for annual.
func (o BaremetalOutput) Cycle() pulumi.StringOutput {
	return o.ApplyT(func(v *Baremetal) pulumi.StringOutput { return v.Cycle }).(pulumi.StringOutput)
}

// Public IP address of the server, when present.
func (o BaremetalOutput) IpAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *Baremetal) pulumi.StringOutput { return v.IpAddress }).(pulumi.StringOutput)
}

// Baremetal keypair id, from BaremetalKeypair. The baremetal keypair pool is separate from neolite/gpu.
func (o BaremetalOutput) KeypairId() pulumi.IntOutput {
	return o.ApplyT(func(v *Baremetal) pulumi.IntOutput { return v.KeypairId }).(pulumi.IntOutput)
}

// Display name of the server. The only field updatable in place.
func (o BaremetalOutput) Label() pulumi.StringOutput {
	return o.ApplyT(func(v *Baremetal) pulumi.StringOutput { return v.Label }).(pulumi.StringOutput)
}

// Order id from the creation response.
func (o BaremetalOutput) OrderId() pulumi.StringOutput {
	return o.ApplyT(func(v *Baremetal) pulumi.StringOutput { return v.OrderId }).(pulumi.StringOutput)
}

// Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
func (o BaremetalOutput) PayWithCreditCard() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Baremetal) pulumi.BoolPtrOutput { return v.PayWithCreditCard }).(pulumi.BoolPtrOutput)
}

// Power state of the server: `on` or `off`. Only fires an API call when the value changes.
func (o BaremetalOutput) PowerState() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Baremetal) pulumi.StringPtrOutput { return v.PowerState }).(pulumi.StringPtrOutput)
}

// Product id from the baremetal products function.
func (o BaremetalOutput) ProductId() pulumi.IntOutput {
	return o.ApplyT(func(v *Baremetal) pulumi.IntOutput { return v.ProductId }).(pulumi.IntOutput)
}

// Promo code to apply at creation.
func (o BaremetalOutput) Promocode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Baremetal) pulumi.StringPtrOutput { return v.Promocode }).(pulumi.StringPtrOutput)
}

// Number of public IPs to request (1 = with public IP). Defaults to 1. Create-only, changing it replaces the instance.
func (o BaremetalOutput) PublicIp() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Baremetal) pulumi.IntPtrOutput { return v.PublicIp }).(pulumi.IntPtrOutput)
}

// Raw JSON of the last read response, for anything not modeled yet.
func (o BaremetalOutput) Raw() pulumi.StringOutput {
	return o.ApplyT(func(v *Baremetal) pulumi.StringOutput { return v.Raw }).(pulumi.StringOutput)
}

// Change this value to rebuild the instance (destructive, wipes the OS) via `PUT /baremetals/{account_id}/rebuild`. Valid OS list comes from the rebuildOsList function.
func (o BaremetalOutput) RebuildOs() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Baremetal) pulumi.StringPtrOutput { return v.RebuildOs }).(pulumi.StringPtrOutput)
}

// Change this value to trigger a one-shot reset/reboot. The reset is an action, not a stable state.
func (o BaremetalOutput) ResetTrigger() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Baremetal) pulumi.StringPtrOutput { return v.ResetTrigger }).(pulumi.StringPtrOutput)
}

// OS to install at creation, from `GET /baremetals/products/{product_id}/oss`. Defaults to `ubuntu-22`. Create-only, changing it replaces the instance.
func (o BaremetalOutput) SelectOs() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Baremetal) pulumi.StringPtrOutput { return v.SelectOs }).(pulumi.StringPtrOutput)
}

// Current status of the server.
func (o BaremetalOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Baremetal) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BaremetalInput)(nil)).Elem(), &Baremetal{})
	pulumi.RegisterOutputType(BaremetalOutput{})
}
