// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumibiznetgio

import (
	"context"
	"reflect"

	"github.com/biznetgio/pulumi-biznetgio/sdk/go/pulumi-biznetgio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GpuGraph(ctx *pulumi.Context, args *GpuGraphArgs, opts ...pulumi.InvokeOption) (*GpuGraphResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GpuGraphResult
	err := ctx.Invoke("biznetgio:index:gpuGraph", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GpuGraphArgs struct {
	// Account id of the GPU instance to get the monitoring graph for.
	AccountId string `pulumi:"accountId"`
	// Timeframe of the graph: `hour`, `day`, `week`, `month`, or `year`. Defaults to `hour`.
	Timeframe *string `pulumi:"timeframe"`
}

type GpuGraphResult struct {
	// Monitoring graph payload from `GET /neo-gpus/accounts/{account_id}/graph-monitor`, falls back to the raw JSON when no graph field is present.
	Graph string `pulumi:"graph"`
	// Raw JSON of the full response.
	Raw string `pulumi:"raw"`
}

func GpuGraphOutput(ctx *pulumi.Context, args GpuGraphOutputArgs, opts ...pulumi.InvokeOption) GpuGraphResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GpuGraphResultOutput, error) {
			args := v.(GpuGraphArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("biznetgio:index:gpuGraph", args, GpuGraphResultOutput{}, options).(GpuGraphResultOutput), nil
		}).(GpuGraphResultOutput)
}

type GpuGraphOutputArgs struct {
	// Account id of the GPU instance to get the monitoring graph for.
	AccountId pulumi.StringInput `pulumi:"accountId"`
	// Timeframe of the graph: `hour`, `day`, `week`, `month`, or `year`. Defaults to `hour`.
	Timeframe pulumi.StringPtrInput `pulumi:"timeframe"`
}

func (GpuGraphOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GpuGraphArgs)(nil)).Elem()
}

type GpuGraphResultOutput struct{ *pulumi.OutputState }

func (GpuGraphResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GpuGraphResult)(nil)).Elem()
}

func (o GpuGraphResultOutput) ToGpuGraphResultOutput() GpuGraphResultOutput {
	return o
}

func (o GpuGraphResultOutput) ToGpuGraphResultOutputWithContext(ctx context.Context) GpuGraphResultOutput {
	return o
}

// Monitoring graph payload from `GET /neo-gpus/accounts/{account_id}/graph-monitor`, falls back to the raw JSON when no graph field is present.
func (o GpuGraphResultOutput) Graph() pulumi.StringOutput {
	return o.ApplyT(func(v GpuGraphResult) string { return v.Graph }).(pulumi.StringOutput)
}

// Raw JSON of the full response.
func (o GpuGraphResultOutput) Raw() pulumi.StringOutput {
	return o.ApplyT(func(v GpuGraphResult) string { return v.Raw }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GpuGraphResultOutput{})
}
