// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumibiznetgio

import (
	"context"
	"reflect"

	"github.com/biznetgio/pulumi-biznetgio/sdk/go/pulumi-biznetgio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func NeoliteChangePackageOptions(ctx *pulumi.Context, args *NeoliteChangePackageOptionsArgs, opts ...pulumi.InvokeOption) (*NeoliteChangePackageOptionsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv NeoliteChangePackageOptionsResult
	err := ctx.Invoke("biznetgio:index:neoliteChangePackageOptions", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type NeoliteChangePackageOptionsArgs struct {
	// Account id VM NEO Lite.
	AccountId int `pulumi:"accountId"`
}

type NeoliteChangePackageOptionsResult struct {
	Raw string `pulumi:"raw"`
}

func NeoliteChangePackageOptionsOutput(ctx *pulumi.Context, args NeoliteChangePackageOptionsOutputArgs, opts ...pulumi.InvokeOption) NeoliteChangePackageOptionsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (NeoliteChangePackageOptionsResultOutput, error) {
			args := v.(NeoliteChangePackageOptionsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("biznetgio:index:neoliteChangePackageOptions", args, NeoliteChangePackageOptionsResultOutput{}, options).(NeoliteChangePackageOptionsResultOutput), nil
		}).(NeoliteChangePackageOptionsResultOutput)
}

type NeoliteChangePackageOptionsOutputArgs struct {
	// Account id VM NEO Lite.
	AccountId pulumi.IntInput `pulumi:"accountId"`
}

func (NeoliteChangePackageOptionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*NeoliteChangePackageOptionsArgs)(nil)).Elem()
}

type NeoliteChangePackageOptionsResultOutput struct{ *pulumi.OutputState }

func (NeoliteChangePackageOptionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NeoliteChangePackageOptionsResult)(nil)).Elem()
}

func (o NeoliteChangePackageOptionsResultOutput) ToNeoliteChangePackageOptionsResultOutput() NeoliteChangePackageOptionsResultOutput {
	return o
}

func (o NeoliteChangePackageOptionsResultOutput) ToNeoliteChangePackageOptionsResultOutputWithContext(ctx context.Context) NeoliteChangePackageOptionsResultOutput {
	return o
}

func (o NeoliteChangePackageOptionsResultOutput) Raw() pulumi.StringOutput {
	return o.ApplyT(func(v NeoliteChangePackageOptionsResult) string { return v.Raw }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(NeoliteChangePackageOptionsResultOutput{})
}
