// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumibiznetgio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/shirasakaren/pulumi-biznetgio/sdk/go/pulumi-biznetgio/internal"
)

type NeoliteDisk struct {
	pulumi.CustomResourceState

	// Billing cycle: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
	Cycle pulumi.StringOutput `pulumi:"cycle"`
	// Account id of the NEO Lite VM the disk is attached to.
	NeoliteAccountId pulumi.IntOutput `pulumi:"neoliteAccountId"`
	// Order id from the creation response.
	OrderId pulumi.StringOutput `pulumi:"orderId"`
	// Pay the invoice with the registered credit card at order time. Defaults to true (auto-charge); set false to leave it unpaid in the portal until settled.
	PayWithCreditCard pulumi.BoolPtrOutput `pulumi:"payWithCreditCard"`
	// Disk product id from the `/neolites/disks/products` endpoint.
	ProductId pulumi.IntOutput `pulumi:"productId"`
	// Promo code to apply at order.
	Promocode pulumi.StringPtrOutput `pulumi:"promocode"`
	// Raw JSON of the last-read disk response, for accessing fields not yet modeled.
	Raw pulumi.StringOutput `pulumi:"raw"`
	// Disk service name. Defaults to `service-name`.
	ServiceName pulumi.StringPtrOutput `pulumi:"serviceName"`
	// Disk size (GB). Defaults to 60. Can only go up, never down.
	Size pulumi.IntPtrOutput `pulumi:"size"`
	// Disk status (Active, Pending, Suspended, Terminated).
	Status pulumi.StringOutput `pulumi:"status"`
}

// NewNeoliteDisk registers a new resource with the given unique name, arguments, and options.
func NewNeoliteDisk(ctx *pulumi.Context,
	name string, args *NeoliteDiskArgs, opts ...pulumi.ResourceOption) (*NeoliteDisk, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Cycle == nil {
		return nil, errors.New("invalid value for required argument 'Cycle'")
	}
	if args.NeoliteAccountId == nil {
		return nil, errors.New("invalid value for required argument 'NeoliteAccountId'")
	}
	if args.ProductId == nil {
		return nil, errors.New("invalid value for required argument 'ProductId'")
	}
	if args.PayWithCreditCard == nil {
		args.PayWithCreditCard = pulumi.BoolPtr(true)
	}
	if args.Promocode == nil {
		args.Promocode = pulumi.StringPtr("")
	}
	if args.ServiceName == nil {
		args.ServiceName = pulumi.StringPtr("service-name")
	}
	if args.Size == nil {
		args.Size = pulumi.IntPtr(60)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"raw",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NeoliteDisk
	err := ctx.RegisterResource("biznetgio:index:NeoliteDisk", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNeoliteDisk gets an existing NeoliteDisk resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNeoliteDisk(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NeoliteDiskState, opts ...pulumi.ResourceOption) (*NeoliteDisk, error) {
	var resource NeoliteDisk
	err := ctx.ReadResource("biznetgio:index:NeoliteDisk", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NeoliteDisk resources.
type neoliteDiskState struct {
}

type NeoliteDiskState struct {
}

func (NeoliteDiskState) ElementType() reflect.Type {
	return reflect.TypeOf((*neoliteDiskState)(nil)).Elem()
}

type neoliteDiskArgs struct {
	// Billing cycle: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
	Cycle string `pulumi:"cycle"`
	// Account id of the NEO Lite VM the disk is attached to.
	NeoliteAccountId int `pulumi:"neoliteAccountId"`
	// Pay the invoice with the registered credit card at order time. Defaults to true (auto-charge); set false to leave it unpaid in the portal until settled.
	PayWithCreditCard *bool `pulumi:"payWithCreditCard"`
	// Disk product id from the `/neolites/disks/products` endpoint.
	ProductId int `pulumi:"productId"`
	// Promo code to apply at order.
	Promocode *string `pulumi:"promocode"`
	// Disk service name. Defaults to `service-name`.
	ServiceName *string `pulumi:"serviceName"`
	// Disk size (GB). Defaults to 60. Can only go up, never down.
	Size *int `pulumi:"size"`
}

// The set of arguments for constructing a NeoliteDisk resource.
type NeoliteDiskArgs struct {
	// Billing cycle: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
	Cycle pulumi.StringInput
	// Account id of the NEO Lite VM the disk is attached to.
	NeoliteAccountId pulumi.IntInput
	// Pay the invoice with the registered credit card at order time. Defaults to true (auto-charge); set false to leave it unpaid in the portal until settled.
	PayWithCreditCard pulumi.BoolPtrInput
	// Disk product id from the `/neolites/disks/products` endpoint.
	ProductId pulumi.IntInput
	// Promo code to apply at order.
	Promocode pulumi.StringPtrInput
	// Disk service name. Defaults to `service-name`.
	ServiceName pulumi.StringPtrInput
	// Disk size (GB). Defaults to 60. Can only go up, never down.
	Size pulumi.IntPtrInput
}

func (NeoliteDiskArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*neoliteDiskArgs)(nil)).Elem()
}

type NeoliteDiskInput interface {
	pulumi.Input

	ToNeoliteDiskOutput() NeoliteDiskOutput
	ToNeoliteDiskOutputWithContext(ctx context.Context) NeoliteDiskOutput
}

func (*NeoliteDisk) ElementType() reflect.Type {
	return reflect.TypeOf((**NeoliteDisk)(nil)).Elem()
}

func (i *NeoliteDisk) ToNeoliteDiskOutput() NeoliteDiskOutput {
	return i.ToNeoliteDiskOutputWithContext(context.Background())
}

func (i *NeoliteDisk) ToNeoliteDiskOutputWithContext(ctx context.Context) NeoliteDiskOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NeoliteDiskOutput)
}

type NeoliteDiskOutput struct{ *pulumi.OutputState }

func (NeoliteDiskOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NeoliteDisk)(nil)).Elem()
}

func (o NeoliteDiskOutput) ToNeoliteDiskOutput() NeoliteDiskOutput {
	return o
}

func (o NeoliteDiskOutput) ToNeoliteDiskOutputWithContext(ctx context.Context) NeoliteDiskOutput {
	return o
}

// Billing cycle: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
func (o NeoliteDiskOutput) Cycle() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteDisk) pulumi.StringOutput { return v.Cycle }).(pulumi.StringOutput)
}

// Account id of the NEO Lite VM the disk is attached to.
func (o NeoliteDiskOutput) NeoliteAccountId() pulumi.IntOutput {
	return o.ApplyT(func(v *NeoliteDisk) pulumi.IntOutput { return v.NeoliteAccountId }).(pulumi.IntOutput)
}

// Order id from the creation response.
func (o NeoliteDiskOutput) OrderId() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteDisk) pulumi.StringOutput { return v.OrderId }).(pulumi.StringOutput)
}

// Pay the invoice with the registered credit card at order time. Defaults to true (auto-charge); set false to leave it unpaid in the portal until settled.
func (o NeoliteDiskOutput) PayWithCreditCard() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *NeoliteDisk) pulumi.BoolPtrOutput { return v.PayWithCreditCard }).(pulumi.BoolPtrOutput)
}

// Disk product id from the `/neolites/disks/products` endpoint.
func (o NeoliteDiskOutput) ProductId() pulumi.IntOutput {
	return o.ApplyT(func(v *NeoliteDisk) pulumi.IntOutput { return v.ProductId }).(pulumi.IntOutput)
}

// Promo code to apply at order.
func (o NeoliteDiskOutput) Promocode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NeoliteDisk) pulumi.StringPtrOutput { return v.Promocode }).(pulumi.StringPtrOutput)
}

// Raw JSON of the last-read disk response, for accessing fields not yet modeled.
func (o NeoliteDiskOutput) Raw() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteDisk) pulumi.StringOutput { return v.Raw }).(pulumi.StringOutput)
}

// Disk service name. Defaults to `service-name`.
func (o NeoliteDiskOutput) ServiceName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NeoliteDisk) pulumi.StringPtrOutput { return v.ServiceName }).(pulumi.StringPtrOutput)
}

// Disk size (GB). Defaults to 60. Can only go up, never down.
func (o NeoliteDiskOutput) Size() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *NeoliteDisk) pulumi.IntPtrOutput { return v.Size }).(pulumi.IntPtrOutput)
}

// Disk status (Active, Pending, Suspended, Terminated).
func (o NeoliteDiskOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteDisk) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NeoliteDiskInput)(nil)).Elem(), &NeoliteDisk{})
	pulumi.RegisterOutputType(NeoliteDiskOutput{})
}
