// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumibiznetgio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/shirasakaren/pulumi-biznetgio/sdk/go/pulumi-biznetgio/internal"
)

func NeoliteProStorageUpgradeOptions(ctx *pulumi.Context, args *NeoliteProStorageUpgradeOptionsArgs, opts ...pulumi.InvokeOption) (*NeoliteProStorageUpgradeOptionsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv NeoliteProStorageUpgradeOptionsResult
	err := ctx.Invoke("biznetgio:index:neoliteProStorageUpgradeOptions", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type NeoliteProStorageUpgradeOptionsArgs struct {
	// Account id VM NEO Lite Pro.
	AccountId int `pulumi:"accountId"`
}

type NeoliteProStorageUpgradeOptionsResult struct {
	Raw string `pulumi:"raw"`
}

func NeoliteProStorageUpgradeOptionsOutput(ctx *pulumi.Context, args NeoliteProStorageUpgradeOptionsOutputArgs, opts ...pulumi.InvokeOption) NeoliteProStorageUpgradeOptionsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (NeoliteProStorageUpgradeOptionsResultOutput, error) {
			args := v.(NeoliteProStorageUpgradeOptionsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("biznetgio:index:neoliteProStorageUpgradeOptions", args, NeoliteProStorageUpgradeOptionsResultOutput{}, options).(NeoliteProStorageUpgradeOptionsResultOutput), nil
		}).(NeoliteProStorageUpgradeOptionsResultOutput)
}

type NeoliteProStorageUpgradeOptionsOutputArgs struct {
	// Account id VM NEO Lite Pro.
	AccountId pulumi.IntInput `pulumi:"accountId"`
}

func (NeoliteProStorageUpgradeOptionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*NeoliteProStorageUpgradeOptionsArgs)(nil)).Elem()
}

type NeoliteProStorageUpgradeOptionsResultOutput struct{ *pulumi.OutputState }

func (NeoliteProStorageUpgradeOptionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NeoliteProStorageUpgradeOptionsResult)(nil)).Elem()
}

func (o NeoliteProStorageUpgradeOptionsResultOutput) ToNeoliteProStorageUpgradeOptionsResultOutput() NeoliteProStorageUpgradeOptionsResultOutput {
	return o
}

func (o NeoliteProStorageUpgradeOptionsResultOutput) ToNeoliteProStorageUpgradeOptionsResultOutputWithContext(ctx context.Context) NeoliteProStorageUpgradeOptionsResultOutput {
	return o
}

func (o NeoliteProStorageUpgradeOptionsResultOutput) Raw() pulumi.StringOutput {
	return o.ApplyT(func(v NeoliteProStorageUpgradeOptionsResult) string { return v.Raw }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(NeoliteProStorageUpgradeOptionsResultOutput{})
}
