// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumibiznetgio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/shirasakaren/pulumi-biznetgio/sdk/go/pulumi-biznetgio/internal"
)

type NeoliteProVm struct {
	pulumi.CustomResourceState

	// Active billing cycle.
	Billingcycle pulumi.StringOutput `pulumi:"billingcycle"`
	// VM cloud-init password (sensitive).
	CiPassword pulumi.StringOutput `pulumi:"ciPassword"`
	// VM cloud-init user.
	CiUser pulumi.StringOutput `pulumi:"ciUser"`
	// Console password at creation. Write-only: never re-fetched from the API.
	ConsolePassword pulumi.StringOutput `pulumi:"consolePassword"`
	// Number of VM CPUs.
	Cpus pulumi.IntOutput `pulumi:"cpus"`
	// Billing cycle: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
	Cycle pulumi.StringOutput `pulumi:"cycle"`
	// VM description.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Target disk size (GB, absolute - not an increment). Can only go up, never down.
	DiskSize pulumi.IntPtrOutput `pulumi:"diskSize"`
	// Keypair id from `NeoliteProKeypair`. Can be changed via change-keypair.
	KeypairId pulumi.IntOutput `pulumi:"keypairId"`
	// VM's last invoice.
	LastInvoice NeoliteLastInvoiceOutput `pulumi:"lastInvoice"`
	// Maximum VM disk size (GB).
	MaxDisk pulumi.IntOutput `pulumi:"maxDisk"`
	// Maximum VM memory (MB).
	MaxMem pulumi.IntOutput `pulumi:"maxMem"`
	// Memory used by the VM (MB).
	Mem pulumi.IntOutput `pulumi:"mem"`
	// Next billing due date.
	NextDue pulumi.StringOutput `pulumi:"nextDue"`
	// Order id from the creation response.
	OrderId pulumi.StringOutput `pulumi:"orderId"`
	// Name of the OS running on the VM.
	OsName pulumi.StringOutput `pulumi:"osName"`
	// Pay the invoice with the registered credit card at order time. Defaults to true (auto-charge); set false to leave it unpaid in the portal until settled.
	PayWithCreditCard pulumi.BoolPtrOutput `pulumi:"payWithCreditCard"`
	// VM power state: start, stop, suspend, resume, or shutdown. Update only sends an action when the value changes.
	PowerState pulumi.StringPtrOutput `pulumi:"powerState"`
	// Product id from the `getProducts` function or the portal.
	ProductId pulumi.IntOutput `pulumi:"productId"`
	// Active product name.
	ProductName pulumi.StringOutput `pulumi:"productName"`
	// Promo code to apply at order.
	Promocode pulumi.StringPtrOutput `pulumi:"promocode"`
	// Raw JSON response of the last-read account, for accessing fields not yet modeled (cipassword masked).
	Raw pulumi.StringOutput `pulumi:"raw"`
	// When changed, the VM is rebuilt (wipes the OS) with the new OS via the rebuild endpoint. Valid OS values are listed by the `getOsList` function.
	RebuildOs pulumi.StringPtrOutput `pulumi:"rebuildOs"`
	// Recurring amount per cycle.
	RecurringAmount pulumi.IntOutput `pulumi:"recurringAmount"`
	// VM region.
	Region pulumi.StringOutput `pulumi:"region"`
	// VM region label.
	RegionLabel pulumi.StringOutput `pulumi:"regionLabel"`
	// OS installed at creation, from the `getOsList` function. To change OS, use `rebuildOs`.
	SelectOs pulumi.StringOutput `pulumi:"selectOs"`
	// SSH and console user set at creation.
	SshAndConsoleUser pulumi.StringOutput `pulumi:"sshAndConsoleUser"`
	// Last known account status from the API (Active, Pending, Suspended, Terminated).
	Status pulumi.StringOutput `pulumi:"status"`
	// VM uptime in seconds.
	Uptime pulumi.IntOutput `pulumi:"uptime"`
	// VM name. Defaults to `server-name`. Can be changed via change-vm-name.
	VmName pulumi.StringPtrOutput `pulumi:"vmName"`
}

// NewNeoliteProVm registers a new resource with the given unique name, arguments, and options.
func NewNeoliteProVm(ctx *pulumi.Context,
	name string, args *NeoliteProVmArgs, opts ...pulumi.ResourceOption) (*NeoliteProVm, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ConsolePassword == nil {
		return nil, errors.New("invalid value for required argument 'ConsolePassword'")
	}
	if args.Cycle == nil {
		return nil, errors.New("invalid value for required argument 'Cycle'")
	}
	if args.KeypairId == nil {
		return nil, errors.New("invalid value for required argument 'KeypairId'")
	}
	if args.ProductId == nil {
		return nil, errors.New("invalid value for required argument 'ProductId'")
	}
	if args.SelectOs == nil {
		return nil, errors.New("invalid value for required argument 'SelectOs'")
	}
	if args.SshAndConsoleUser == nil {
		return nil, errors.New("invalid value for required argument 'SshAndConsoleUser'")
	}
	if args.Description == nil {
		args.Description = pulumi.StringPtr("")
	}
	if args.PayWithCreditCard == nil {
		args.PayWithCreditCard = pulumi.BoolPtr(true)
	}
	if args.Promocode == nil {
		args.Promocode = pulumi.StringPtr("")
	}
	if args.VmName == nil {
		args.VmName = pulumi.StringPtr("server-name")
	}
	if args.ConsolePassword != nil {
		args.ConsolePassword = pulumi.ToSecret(args.ConsolePassword).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"ciPassword",
		"consolePassword",
		"raw",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NeoliteProVm
	err := ctx.RegisterResource("biznetgio:index:NeoliteProVm", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNeoliteProVm gets an existing NeoliteProVm resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNeoliteProVm(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NeoliteProVmState, opts ...pulumi.ResourceOption) (*NeoliteProVm, error) {
	var resource NeoliteProVm
	err := ctx.ReadResource("biznetgio:index:NeoliteProVm", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NeoliteProVm resources.
type neoliteProVmState struct {
}

type NeoliteProVmState struct {
}

func (NeoliteProVmState) ElementType() reflect.Type {
	return reflect.TypeOf((*neoliteProVmState)(nil)).Elem()
}

type neoliteProVmArgs struct {
	// Console password at creation. Write-only: never re-fetched from the API.
	ConsolePassword string `pulumi:"consolePassword"`
	// Billing cycle: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
	Cycle string `pulumi:"cycle"`
	// VM description.
	Description *string `pulumi:"description"`
	// Target disk size (GB, absolute - not an increment). Can only go up, never down.
	DiskSize *int `pulumi:"diskSize"`
	// Keypair id from `NeoliteProKeypair`. Can be changed via change-keypair.
	KeypairId int `pulumi:"keypairId"`
	// Pay the invoice with the registered credit card at order time. Defaults to true (auto-charge); set false to leave it unpaid in the portal until settled.
	PayWithCreditCard *bool `pulumi:"payWithCreditCard"`
	// VM power state: start, stop, suspend, resume, or shutdown. Update only sends an action when the value changes.
	PowerState *string `pulumi:"powerState"`
	// Product id from the `getProducts` function or the portal.
	ProductId int `pulumi:"productId"`
	// Promo code to apply at order.
	Promocode *string `pulumi:"promocode"`
	// When changed, the VM is rebuilt (wipes the OS) with the new OS via the rebuild endpoint. Valid OS values are listed by the `getOsList` function.
	RebuildOs *string `pulumi:"rebuildOs"`
	// OS installed at creation, from the `getOsList` function. To change OS, use `rebuildOs`.
	SelectOs string `pulumi:"selectOs"`
	// SSH and console user set at creation.
	SshAndConsoleUser string `pulumi:"sshAndConsoleUser"`
	// VM name. Defaults to `server-name`. Can be changed via change-vm-name.
	VmName *string `pulumi:"vmName"`
}

// The set of arguments for constructing a NeoliteProVm resource.
type NeoliteProVmArgs struct {
	// Console password at creation. Write-only: never re-fetched from the API.
	ConsolePassword pulumi.StringInput
	// Billing cycle: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
	Cycle pulumi.StringInput
	// VM description.
	Description pulumi.StringPtrInput
	// Target disk size (GB, absolute - not an increment). Can only go up, never down.
	DiskSize pulumi.IntPtrInput
	// Keypair id from `NeoliteProKeypair`. Can be changed via change-keypair.
	KeypairId pulumi.IntInput
	// Pay the invoice with the registered credit card at order time. Defaults to true (auto-charge); set false to leave it unpaid in the portal until settled.
	PayWithCreditCard pulumi.BoolPtrInput
	// VM power state: start, stop, suspend, resume, or shutdown. Update only sends an action when the value changes.
	PowerState pulumi.StringPtrInput
	// Product id from the `getProducts` function or the portal.
	ProductId pulumi.IntInput
	// Promo code to apply at order.
	Promocode pulumi.StringPtrInput
	// When changed, the VM is rebuilt (wipes the OS) with the new OS via the rebuild endpoint. Valid OS values are listed by the `getOsList` function.
	RebuildOs pulumi.StringPtrInput
	// OS installed at creation, from the `getOsList` function. To change OS, use `rebuildOs`.
	SelectOs pulumi.StringInput
	// SSH and console user set at creation.
	SshAndConsoleUser pulumi.StringInput
	// VM name. Defaults to `server-name`. Can be changed via change-vm-name.
	VmName pulumi.StringPtrInput
}

func (NeoliteProVmArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*neoliteProVmArgs)(nil)).Elem()
}

type NeoliteProVmInput interface {
	pulumi.Input

	ToNeoliteProVmOutput() NeoliteProVmOutput
	ToNeoliteProVmOutputWithContext(ctx context.Context) NeoliteProVmOutput
}

func (*NeoliteProVm) ElementType() reflect.Type {
	return reflect.TypeOf((**NeoliteProVm)(nil)).Elem()
}

func (i *NeoliteProVm) ToNeoliteProVmOutput() NeoliteProVmOutput {
	return i.ToNeoliteProVmOutputWithContext(context.Background())
}

func (i *NeoliteProVm) ToNeoliteProVmOutputWithContext(ctx context.Context) NeoliteProVmOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NeoliteProVmOutput)
}

type NeoliteProVmOutput struct{ *pulumi.OutputState }

func (NeoliteProVmOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NeoliteProVm)(nil)).Elem()
}

func (o NeoliteProVmOutput) ToNeoliteProVmOutput() NeoliteProVmOutput {
	return o
}

func (o NeoliteProVmOutput) ToNeoliteProVmOutputWithContext(ctx context.Context) NeoliteProVmOutput {
	return o
}

// Active billing cycle.
func (o NeoliteProVmOutput) Billingcycle() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringOutput { return v.Billingcycle }).(pulumi.StringOutput)
}

// VM cloud-init password (sensitive).
func (o NeoliteProVmOutput) CiPassword() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringOutput { return v.CiPassword }).(pulumi.StringOutput)
}

// VM cloud-init user.
func (o NeoliteProVmOutput) CiUser() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringOutput { return v.CiUser }).(pulumi.StringOutput)
}

// Console password at creation. Write-only: never re-fetched from the API.
func (o NeoliteProVmOutput) ConsolePassword() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringOutput { return v.ConsolePassword }).(pulumi.StringOutput)
}

// Number of VM CPUs.
func (o NeoliteProVmOutput) Cpus() pulumi.IntOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.IntOutput { return v.Cpus }).(pulumi.IntOutput)
}

// Billing cycle: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
func (o NeoliteProVmOutput) Cycle() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringOutput { return v.Cycle }).(pulumi.StringOutput)
}

// VM description.
func (o NeoliteProVmOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Target disk size (GB, absolute - not an increment). Can only go up, never down.
func (o NeoliteProVmOutput) DiskSize() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.IntPtrOutput { return v.DiskSize }).(pulumi.IntPtrOutput)
}

// Keypair id from `NeoliteProKeypair`. Can be changed via change-keypair.
func (o NeoliteProVmOutput) KeypairId() pulumi.IntOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.IntOutput { return v.KeypairId }).(pulumi.IntOutput)
}

// VM's last invoice.
func (o NeoliteProVmOutput) LastInvoice() NeoliteLastInvoiceOutput {
	return o.ApplyT(func(v *NeoliteProVm) NeoliteLastInvoiceOutput { return v.LastInvoice }).(NeoliteLastInvoiceOutput)
}

// Maximum VM disk size (GB).
func (o NeoliteProVmOutput) MaxDisk() pulumi.IntOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.IntOutput { return v.MaxDisk }).(pulumi.IntOutput)
}

// Maximum VM memory (MB).
func (o NeoliteProVmOutput) MaxMem() pulumi.IntOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.IntOutput { return v.MaxMem }).(pulumi.IntOutput)
}

// Memory used by the VM (MB).
func (o NeoliteProVmOutput) Mem() pulumi.IntOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.IntOutput { return v.Mem }).(pulumi.IntOutput)
}

// Next billing due date.
func (o NeoliteProVmOutput) NextDue() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringOutput { return v.NextDue }).(pulumi.StringOutput)
}

// Order id from the creation response.
func (o NeoliteProVmOutput) OrderId() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringOutput { return v.OrderId }).(pulumi.StringOutput)
}

// Name of the OS running on the VM.
func (o NeoliteProVmOutput) OsName() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringOutput { return v.OsName }).(pulumi.StringOutput)
}

// Pay the invoice with the registered credit card at order time. Defaults to true (auto-charge); set false to leave it unpaid in the portal until settled.
func (o NeoliteProVmOutput) PayWithCreditCard() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.BoolPtrOutput { return v.PayWithCreditCard }).(pulumi.BoolPtrOutput)
}

// VM power state: start, stop, suspend, resume, or shutdown. Update only sends an action when the value changes.
func (o NeoliteProVmOutput) PowerState() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringPtrOutput { return v.PowerState }).(pulumi.StringPtrOutput)
}

// Product id from the `getProducts` function or the portal.
func (o NeoliteProVmOutput) ProductId() pulumi.IntOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.IntOutput { return v.ProductId }).(pulumi.IntOutput)
}

// Active product name.
func (o NeoliteProVmOutput) ProductName() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringOutput { return v.ProductName }).(pulumi.StringOutput)
}

// Promo code to apply at order.
func (o NeoliteProVmOutput) Promocode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringPtrOutput { return v.Promocode }).(pulumi.StringPtrOutput)
}

// Raw JSON response of the last-read account, for accessing fields not yet modeled (cipassword masked).
func (o NeoliteProVmOutput) Raw() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringOutput { return v.Raw }).(pulumi.StringOutput)
}

// When changed, the VM is rebuilt (wipes the OS) with the new OS via the rebuild endpoint. Valid OS values are listed by the `getOsList` function.
func (o NeoliteProVmOutput) RebuildOs() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringPtrOutput { return v.RebuildOs }).(pulumi.StringPtrOutput)
}

// Recurring amount per cycle.
func (o NeoliteProVmOutput) RecurringAmount() pulumi.IntOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.IntOutput { return v.RecurringAmount }).(pulumi.IntOutput)
}

// VM region.
func (o NeoliteProVmOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// VM region label.
func (o NeoliteProVmOutput) RegionLabel() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringOutput { return v.RegionLabel }).(pulumi.StringOutput)
}

// OS installed at creation, from the `getOsList` function. To change OS, use `rebuildOs`.
func (o NeoliteProVmOutput) SelectOs() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringOutput { return v.SelectOs }).(pulumi.StringOutput)
}

// SSH and console user set at creation.
func (o NeoliteProVmOutput) SshAndConsoleUser() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringOutput { return v.SshAndConsoleUser }).(pulumi.StringOutput)
}

// Last known account status from the API (Active, Pending, Suspended, Terminated).
func (o NeoliteProVmOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// VM uptime in seconds.
func (o NeoliteProVmOutput) Uptime() pulumi.IntOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.IntOutput { return v.Uptime }).(pulumi.IntOutput)
}

// VM name. Defaults to `server-name`. Can be changed via change-vm-name.
func (o NeoliteProVmOutput) VmName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NeoliteProVm) pulumi.StringPtrOutput { return v.VmName }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NeoliteProVmInput)(nil)).Elem(), &NeoliteProVm{})
	pulumi.RegisterOutputType(NeoliteProVmOutput{})
}
