// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumibiznetgio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/shirasakaren/pulumi-biznetgio/sdk/go/pulumi-biznetgio/internal"
)

func NeoliteProducts(ctx *pulumi.Context, args *NeoliteProductsArgs, opts ...pulumi.InvokeOption) (*NeoliteProductsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv NeoliteProductsResult
	err := ctx.Invoke("biznetgio:index:neoliteProducts", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type NeoliteProductsArgs struct {
}

type NeoliteProductsResult struct {
	Products []NeolitePlanItem `pulumi:"products"`
}

func NeoliteProductsOutput(ctx *pulumi.Context, args NeoliteProductsOutputArgs, opts ...pulumi.InvokeOption) NeoliteProductsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (NeoliteProductsResultOutput, error) {
			args := v.(NeoliteProductsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("biznetgio:index:neoliteProducts", args, NeoliteProductsResultOutput{}, options).(NeoliteProductsResultOutput), nil
		}).(NeoliteProductsResultOutput)
}

type NeoliteProductsOutputArgs struct {
}

func (NeoliteProductsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*NeoliteProductsArgs)(nil)).Elem()
}

type NeoliteProductsResultOutput struct{ *pulumi.OutputState }

func (NeoliteProductsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NeoliteProductsResult)(nil)).Elem()
}

func (o NeoliteProductsResultOutput) ToNeoliteProductsResultOutput() NeoliteProductsResultOutput {
	return o
}

func (o NeoliteProductsResultOutput) ToNeoliteProductsResultOutputWithContext(ctx context.Context) NeoliteProductsResultOutput {
	return o
}

func (o NeoliteProductsResultOutput) Products() NeolitePlanItemArrayOutput {
	return o.ApplyT(func(v NeoliteProductsResult) []NeolitePlanItem { return v.Products }).(NeolitePlanItemArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(NeoliteProductsResultOutput{})
}
