// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumibiznetgio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/shirasakaren/pulumi-biznetgio/sdk/go/pulumi-biznetgio/internal"
)

func NeoliteProIPAvailability(ctx *pulumi.Context, args *NeoliteProIPAvailabilityArgs, opts ...pulumi.InvokeOption) (*NeoliteProIPAvailabilityResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv NeoliteProIPAvailabilityResult
	err := ctx.Invoke("biznetgio:index:neoliteProIPAvailability", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type NeoliteProIPAvailabilityArgs struct {
	// Product id NEO Lite Pro.
	ProductId int `pulumi:"productId"`
}

type NeoliteProIPAvailabilityResult struct {
	Available bool `pulumi:"available"`
}

func NeoliteProIPAvailabilityOutput(ctx *pulumi.Context, args NeoliteProIPAvailabilityOutputArgs, opts ...pulumi.InvokeOption) NeoliteProIPAvailabilityResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (NeoliteProIPAvailabilityResultOutput, error) {
			args := v.(NeoliteProIPAvailabilityArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("biznetgio:index:neoliteProIPAvailability", args, NeoliteProIPAvailabilityResultOutput{}, options).(NeoliteProIPAvailabilityResultOutput), nil
		}).(NeoliteProIPAvailabilityResultOutput)
}

type NeoliteProIPAvailabilityOutputArgs struct {
	// Product id NEO Lite Pro.
	ProductId pulumi.IntInput `pulumi:"productId"`
}

func (NeoliteProIPAvailabilityOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*NeoliteProIPAvailabilityArgs)(nil)).Elem()
}

type NeoliteProIPAvailabilityResultOutput struct{ *pulumi.OutputState }

func (NeoliteProIPAvailabilityResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NeoliteProIPAvailabilityResult)(nil)).Elem()
}

func (o NeoliteProIPAvailabilityResultOutput) ToNeoliteProIPAvailabilityResultOutput() NeoliteProIPAvailabilityResultOutput {
	return o
}

func (o NeoliteProIPAvailabilityResultOutput) ToNeoliteProIPAvailabilityResultOutputWithContext(ctx context.Context) NeoliteProIPAvailabilityResultOutput {
	return o
}

func (o NeoliteProIPAvailabilityResultOutput) Available() pulumi.BoolOutput {
	return o.ApplyT(func(v NeoliteProIPAvailabilityResult) bool { return v.Available }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(NeoliteProIPAvailabilityResultOutput{})
}
