// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumibiznetgio

import (
	"context"
	"reflect"

	"errors"
	"github.com/biznetgio/pulumi-biznetgio/sdk/go/pulumi-biznetgio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ObjectStorageBucket struct {
	pulumi.CustomResourceState

	// Object storage instance account id. Create-only.
	AccountId pulumi.StringOutput `pulumi:"accountId"`
	// S3-style canned ACL: empty (default private), private, public-read, public-read-write, authenticated-read, log-delivery-write. Defaults to empty.
	Acl pulumi.StringPtrOutput `pulumi:"acl"`
	// Bucket name, minimum 3 chars, `[a-zA-Z0-9-_]`. Immutable, changing it replaces the bucket.
	Name pulumi.StringOutput `pulumi:"name"`
	// Raw JSON of the last read response, for anything not modeled yet.
	Raw pulumi.StringOutput `pulumi:"raw"`
}

// NewObjectStorageBucket registers a new resource with the given unique name, arguments, and options.
func NewObjectStorageBucket(ctx *pulumi.Context,
	name string, args *ObjectStorageBucketArgs, opts ...pulumi.ResourceOption) (*ObjectStorageBucket, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AccountId == nil {
		return nil, errors.New("invalid value for required argument 'AccountId'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Acl == nil {
		args.Acl = pulumi.StringPtr("")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"raw",
	})
	opts = append(opts, secrets)
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"accountId",
		"name",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ObjectStorageBucket
	err := ctx.RegisterResource("biznetgio:index:ObjectStorageBucket", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetObjectStorageBucket gets an existing ObjectStorageBucket resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetObjectStorageBucket(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ObjectStorageBucketState, opts ...pulumi.ResourceOption) (*ObjectStorageBucket, error) {
	var resource ObjectStorageBucket
	err := ctx.ReadResource("biznetgio:index:ObjectStorageBucket", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ObjectStorageBucket resources.
type objectStorageBucketState struct {
}

type ObjectStorageBucketState struct {
}

func (ObjectStorageBucketState) ElementType() reflect.Type {
	return reflect.TypeOf((*objectStorageBucketState)(nil)).Elem()
}

type objectStorageBucketArgs struct {
	// Object storage instance account id. Create-only.
	AccountId string `pulumi:"accountId"`
	// S3-style canned ACL: empty (default private), private, public-read, public-read-write, authenticated-read, log-delivery-write. Defaults to empty.
	Acl *string `pulumi:"acl"`
	// Bucket name, minimum 3 chars, `[a-zA-Z0-9-_]`. Immutable, changing it replaces the bucket.
	Name string `pulumi:"name"`
}

// The set of arguments for constructing a ObjectStorageBucket resource.
type ObjectStorageBucketArgs struct {
	// Object storage instance account id. Create-only.
	AccountId pulumi.StringInput
	// S3-style canned ACL: empty (default private), private, public-read, public-read-write, authenticated-read, log-delivery-write. Defaults to empty.
	Acl pulumi.StringPtrInput
	// Bucket name, minimum 3 chars, `[a-zA-Z0-9-_]`. Immutable, changing it replaces the bucket.
	Name pulumi.StringInput
}

func (ObjectStorageBucketArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*objectStorageBucketArgs)(nil)).Elem()
}

type ObjectStorageBucketInput interface {
	pulumi.Input

	ToObjectStorageBucketOutput() ObjectStorageBucketOutput
	ToObjectStorageBucketOutputWithContext(ctx context.Context) ObjectStorageBucketOutput
}

func (*ObjectStorageBucket) ElementType() reflect.Type {
	return reflect.TypeOf((**ObjectStorageBucket)(nil)).Elem()
}

func (i *ObjectStorageBucket) ToObjectStorageBucketOutput() ObjectStorageBucketOutput {
	return i.ToObjectStorageBucketOutputWithContext(context.Background())
}

func (i *ObjectStorageBucket) ToObjectStorageBucketOutputWithContext(ctx context.Context) ObjectStorageBucketOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ObjectStorageBucketOutput)
}

type ObjectStorageBucketOutput struct{ *pulumi.OutputState }

func (ObjectStorageBucketOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ObjectStorageBucket)(nil)).Elem()
}

func (o ObjectStorageBucketOutput) ToObjectStorageBucketOutput() ObjectStorageBucketOutput {
	return o
}

func (o ObjectStorageBucketOutput) ToObjectStorageBucketOutputWithContext(ctx context.Context) ObjectStorageBucketOutput {
	return o
}

// Object storage instance account id. Create-only.
func (o ObjectStorageBucketOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *ObjectStorageBucket) pulumi.StringOutput { return v.AccountId }).(pulumi.StringOutput)
}

// S3-style canned ACL: empty (default private), private, public-read, public-read-write, authenticated-read, log-delivery-write. Defaults to empty.
func (o ObjectStorageBucketOutput) Acl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ObjectStorageBucket) pulumi.StringPtrOutput { return v.Acl }).(pulumi.StringPtrOutput)
}

// Bucket name, minimum 3 chars, `[a-zA-Z0-9-_]`. Immutable, changing it replaces the bucket.
func (o ObjectStorageBucketOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ObjectStorageBucket) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Raw JSON of the last read response, for anything not modeled yet.
func (o ObjectStorageBucketOutput) Raw() pulumi.StringOutput {
	return o.ApplyT(func(v *ObjectStorageBucket) pulumi.StringOutput { return v.Raw }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ObjectStorageBucketInput)(nil)).Elem(), &ObjectStorageBucket{})
	pulumi.RegisterOutputType(ObjectStorageBucketOutput{})
}
