// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumibiznetgio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/shirasakaren/pulumi-biznetgio/sdk/go/pulumi-biznetgio/internal"
)

func ObjectStorageInstances(ctx *pulumi.Context, args *ObjectStorageInstancesArgs, opts ...pulumi.InvokeOption) (*ObjectStorageInstancesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ObjectStorageInstancesResult
	err := ctx.Invoke("biznetgio:index:objectStorageInstances", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ObjectStorageInstancesArgs struct {
	// Filter by status (Active, Pending, Suspended, Terminated).
	Status *string `pulumi:"status"`
}

type ObjectStorageInstancesResult struct {
	// List of object storage instances.
	Instances []ObjectStorageInstancesInstance `pulumi:"instances"`
}

func ObjectStorageInstancesOutput(ctx *pulumi.Context, args ObjectStorageInstancesOutputArgs, opts ...pulumi.InvokeOption) ObjectStorageInstancesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (ObjectStorageInstancesResultOutput, error) {
			args := v.(ObjectStorageInstancesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("biznetgio:index:objectStorageInstances", args, ObjectStorageInstancesResultOutput{}, options).(ObjectStorageInstancesResultOutput), nil
		}).(ObjectStorageInstancesResultOutput)
}

type ObjectStorageInstancesOutputArgs struct {
	// Filter by status (Active, Pending, Suspended, Terminated).
	Status pulumi.StringPtrInput `pulumi:"status"`
}

func (ObjectStorageInstancesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ObjectStorageInstancesArgs)(nil)).Elem()
}

type ObjectStorageInstancesResultOutput struct{ *pulumi.OutputState }

func (ObjectStorageInstancesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ObjectStorageInstancesResult)(nil)).Elem()
}

func (o ObjectStorageInstancesResultOutput) ToObjectStorageInstancesResultOutput() ObjectStorageInstancesResultOutput {
	return o
}

func (o ObjectStorageInstancesResultOutput) ToObjectStorageInstancesResultOutputWithContext(ctx context.Context) ObjectStorageInstancesResultOutput {
	return o
}

// List of object storage instances.
func (o ObjectStorageInstancesResultOutput) Instances() ObjectStorageInstancesInstanceArrayOutput {
	return o.ApplyT(func(v ObjectStorageInstancesResult) []ObjectStorageInstancesInstance { return v.Instances }).(ObjectStorageInstancesInstanceArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(ObjectStorageInstancesResultOutput{})
}
