// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumibiznetgio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/shirasakaren/pulumi-biznetgio/sdk/go/pulumi-biznetgio/internal"
)

type Provider struct {
	pulumi.ProviderResourceState

	// BiznetGIO API token (x-token header). Falls back to BIZNETGIO_API_KEY.
	ApiToken pulumi.StringPtrOutput `pulumi:"apiToken"`
	// BiznetGIO API base URL. Falls back to BIZNETGIO_BASE_URL.
	BaseUrl pulumi.StringPtrOutput `pulumi:"baseUrl"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.ApiToken == nil {
		if d := internal.GetEnvOrDefault(nil, nil, "BIZNETGIO_API_KEY"); d != nil {
			args.ApiToken = pulumi.StringPtr(d.(string))
		}
	}
	if args.BaseUrl == nil {
		if d := internal.GetEnvOrDefault("https://api.portal.biznetgio.com/v1", nil, "BIZNETGIO_BASE_URL"); d != nil {
			args.BaseUrl = pulumi.StringPtr(d.(string))
		}
	}
	if args.ApiToken != nil {
		args.ApiToken = pulumi.ToSecret(args.ApiToken).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiToken",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:biznetgio", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// BiznetGIO API token (x-token header). Falls back to BIZNETGIO_API_KEY.
	ApiToken *string `pulumi:"apiToken"`
	// BiznetGIO API base URL. Falls back to BIZNETGIO_BASE_URL.
	BaseUrl *string `pulumi:"baseUrl"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// BiznetGIO API token (x-token header). Falls back to BIZNETGIO_API_KEY.
	ApiToken pulumi.StringPtrInput
	// BiznetGIO API base URL. Falls back to BIZNETGIO_BASE_URL.
	BaseUrl pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// BiznetGIO API token (x-token header). Falls back to BIZNETGIO_API_KEY.
func (o ProviderOutput) ApiToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ApiToken }).(pulumi.StringPtrOutput)
}

// BiznetGIO API base URL. Falls back to BIZNETGIO_BASE_URL.
func (o ProviderOutput) BaseUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.BaseUrl }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
