// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumibiznetgio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/shirasakaren/pulumi-biznetgio/sdk/go/pulumi-biznetgio/internal"
)

var _ = internal.GetEnvOrDefault

type BaremetalProduct struct {
	// Product description, when present.
	Description string `pulumi:"description"`
	// Product name (alias of name/product_name/label).
	Name string `pulumi:"name"`
	// Product id, for the `productId` input of Baremetal.
	ProductId int `pulumi:"productId"`
	// Raw JSON of the product item, for anything not modeled yet.
	Raw string `pulumi:"raw"`
}

type BaremetalProductOutput struct{ *pulumi.OutputState }

func (BaremetalProductOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*BaremetalProduct)(nil)).Elem()
}

func (o BaremetalProductOutput) ToBaremetalProductOutput() BaremetalProductOutput {
	return o
}

func (o BaremetalProductOutput) ToBaremetalProductOutputWithContext(ctx context.Context) BaremetalProductOutput {
	return o
}

// Product description, when present.
func (o BaremetalProductOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v BaremetalProduct) string { return v.Description }).(pulumi.StringOutput)
}

// Product name (alias of name/product_name/label).
func (o BaremetalProductOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v BaremetalProduct) string { return v.Name }).(pulumi.StringOutput)
}

// Product id, for the `productId` input of Baremetal.
func (o BaremetalProductOutput) ProductId() pulumi.IntOutput {
	return o.ApplyT(func(v BaremetalProduct) int { return v.ProductId }).(pulumi.IntOutput)
}

// Raw JSON of the product item, for anything not modeled yet.
func (o BaremetalProductOutput) Raw() pulumi.StringOutput {
	return o.ApplyT(func(v BaremetalProduct) string { return v.Raw }).(pulumi.StringOutput)
}

type BaremetalProductArrayOutput struct{ *pulumi.OutputState }

func (BaremetalProductArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]BaremetalProduct)(nil)).Elem()
}

func (o BaremetalProductArrayOutput) ToBaremetalProductArrayOutput() BaremetalProductArrayOutput {
	return o
}

func (o BaremetalProductArrayOutput) ToBaremetalProductArrayOutputWithContext(ctx context.Context) BaremetalProductArrayOutput {
	return o
}

func (o BaremetalProductArrayOutput) Index(i pulumi.IntInput) BaremetalProductOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) BaremetalProduct {
		return vs[0].([]BaremetalProduct)[vs[1].(int)]
	}).(BaremetalProductOutput)
}

type GpuFlavor struct {
	// Flavor id.
	FlavorId int `pulumi:"flavorId"`
	// Flavor name.
	Name string `pulumi:"name"`
	// Raw JSON of the flavor response.
	Raw string `pulumi:"raw"`
}

type GpuFlavorOutput struct{ *pulumi.OutputState }

func (GpuFlavorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GpuFlavor)(nil)).Elem()
}

func (o GpuFlavorOutput) ToGpuFlavorOutput() GpuFlavorOutput {
	return o
}

func (o GpuFlavorOutput) ToGpuFlavorOutputWithContext(ctx context.Context) GpuFlavorOutput {
	return o
}

// Flavor id.
func (o GpuFlavorOutput) FlavorId() pulumi.IntOutput {
	return o.ApplyT(func(v GpuFlavor) int { return v.FlavorId }).(pulumi.IntOutput)
}

// Flavor name.
func (o GpuFlavorOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GpuFlavor) string { return v.Name }).(pulumi.StringOutput)
}

// Raw JSON of the flavor response.
func (o GpuFlavorOutput) Raw() pulumi.StringOutput {
	return o.ApplyT(func(v GpuFlavor) string { return v.Raw }).(pulumi.StringOutput)
}

type GpuFlavorArrayOutput struct{ *pulumi.OutputState }

func (GpuFlavorArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GpuFlavor)(nil)).Elem()
}

func (o GpuFlavorArrayOutput) ToGpuFlavorArrayOutput() GpuFlavorArrayOutput {
	return o
}

func (o GpuFlavorArrayOutput) ToGpuFlavorArrayOutputWithContext(ctx context.Context) GpuFlavorArrayOutput {
	return o
}

func (o GpuFlavorArrayOutput) Index(i pulumi.IntInput) GpuFlavorOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GpuFlavor {
		return vs[0].([]GpuFlavor)[vs[1].(int)]
	}).(GpuFlavorOutput)
}

type GpuOnDemandArgs struct {
	// Additional hours to reserve. Defaults to 0.
	AdditionalHours *int `pulumi:"additionalHours"`
}

// GpuOnDemandArgsInput is an input type that accepts GpuOnDemandArgsArgs and GpuOnDemandArgsOutput values.
// You can construct a concrete instance of `GpuOnDemandArgsInput` via:
//
//	GpuOnDemandArgsArgs{...}
type GpuOnDemandArgsInput interface {
	pulumi.Input

	ToGpuOnDemandArgsOutput() GpuOnDemandArgsOutput
	ToGpuOnDemandArgsOutputWithContext(context.Context) GpuOnDemandArgsOutput
}

type GpuOnDemandArgsArgs struct {
	// Additional hours to reserve. Defaults to 0.
	AdditionalHours pulumi.IntPtrInput `pulumi:"additionalHours"`
}

func (GpuOnDemandArgsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GpuOnDemandArgs)(nil)).Elem()
}

func (i GpuOnDemandArgsArgs) ToGpuOnDemandArgsOutput() GpuOnDemandArgsOutput {
	return i.ToGpuOnDemandArgsOutputWithContext(context.Background())
}

func (i GpuOnDemandArgsArgs) ToGpuOnDemandArgsOutputWithContext(ctx context.Context) GpuOnDemandArgsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GpuOnDemandArgsOutput)
}

func (i GpuOnDemandArgsArgs) ToGpuOnDemandArgsPtrOutput() GpuOnDemandArgsPtrOutput {
	return i.ToGpuOnDemandArgsPtrOutputWithContext(context.Background())
}

func (i GpuOnDemandArgsArgs) ToGpuOnDemandArgsPtrOutputWithContext(ctx context.Context) GpuOnDemandArgsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GpuOnDemandArgsOutput).ToGpuOnDemandArgsPtrOutputWithContext(ctx)
}

// GpuOnDemandArgsPtrInput is an input type that accepts GpuOnDemandArgsArgs, GpuOnDemandArgsPtr and GpuOnDemandArgsPtrOutput values.
// You can construct a concrete instance of `GpuOnDemandArgsPtrInput` via:
//
//	        GpuOnDemandArgsArgs{...}
//
//	or:
//
//	        nil
type GpuOnDemandArgsPtrInput interface {
	pulumi.Input

	ToGpuOnDemandArgsPtrOutput() GpuOnDemandArgsPtrOutput
	ToGpuOnDemandArgsPtrOutputWithContext(context.Context) GpuOnDemandArgsPtrOutput
}

type gpuOnDemandArgsPtrType GpuOnDemandArgsArgs

func GpuOnDemandArgsPtr(v *GpuOnDemandArgsArgs) GpuOnDemandArgsPtrInput {
	return (*gpuOnDemandArgsPtrType)(v)
}

func (*gpuOnDemandArgsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**GpuOnDemandArgs)(nil)).Elem()
}

func (i *gpuOnDemandArgsPtrType) ToGpuOnDemandArgsPtrOutput() GpuOnDemandArgsPtrOutput {
	return i.ToGpuOnDemandArgsPtrOutputWithContext(context.Background())
}

func (i *gpuOnDemandArgsPtrType) ToGpuOnDemandArgsPtrOutputWithContext(ctx context.Context) GpuOnDemandArgsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GpuOnDemandArgsPtrOutput)
}

type GpuOnDemandArgsOutput struct{ *pulumi.OutputState }

func (GpuOnDemandArgsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GpuOnDemandArgs)(nil)).Elem()
}

func (o GpuOnDemandArgsOutput) ToGpuOnDemandArgsOutput() GpuOnDemandArgsOutput {
	return o
}

func (o GpuOnDemandArgsOutput) ToGpuOnDemandArgsOutputWithContext(ctx context.Context) GpuOnDemandArgsOutput {
	return o
}

func (o GpuOnDemandArgsOutput) ToGpuOnDemandArgsPtrOutput() GpuOnDemandArgsPtrOutput {
	return o.ToGpuOnDemandArgsPtrOutputWithContext(context.Background())
}

func (o GpuOnDemandArgsOutput) ToGpuOnDemandArgsPtrOutputWithContext(ctx context.Context) GpuOnDemandArgsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v GpuOnDemandArgs) *GpuOnDemandArgs {
		return &v
	}).(GpuOnDemandArgsPtrOutput)
}

// Additional hours to reserve. Defaults to 0.
func (o GpuOnDemandArgsOutput) AdditionalHours() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GpuOnDemandArgs) *int { return v.AdditionalHours }).(pulumi.IntPtrOutput)
}

type GpuOnDemandArgsPtrOutput struct{ *pulumi.OutputState }

func (GpuOnDemandArgsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GpuOnDemandArgs)(nil)).Elem()
}

func (o GpuOnDemandArgsPtrOutput) ToGpuOnDemandArgsPtrOutput() GpuOnDemandArgsPtrOutput {
	return o
}

func (o GpuOnDemandArgsPtrOutput) ToGpuOnDemandArgsPtrOutputWithContext(ctx context.Context) GpuOnDemandArgsPtrOutput {
	return o
}

func (o GpuOnDemandArgsPtrOutput) Elem() GpuOnDemandArgsOutput {
	return o.ApplyT(func(v *GpuOnDemandArgs) GpuOnDemandArgs {
		if v != nil {
			return *v
		}
		var ret GpuOnDemandArgs
		return ret
	}).(GpuOnDemandArgsOutput)
}

// Additional hours to reserve. Defaults to 0.
func (o GpuOnDemandArgsPtrOutput) AdditionalHours() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *GpuOnDemandArgs) *int {
		if v == nil {
			return nil
		}
		return v.AdditionalHours
	}).(pulumi.IntPtrOutput)
}

type GpuProduct struct {
	// Category of the product.
	CategoryName string `pulumi:"categoryName"`
	// Product description.
	Description string `pulumi:"description"`
	// Available flavors for this product.
	Flavors []GpuFlavor `pulumi:"flavors"`
	// Product name.
	Name string `pulumi:"name"`
	// Product id, use it as GpuInstance productId.
	ProductId int `pulumi:"productId"`
	// Raw JSON of the product response.
	Raw string `pulumi:"raw"`
}

type GpuProductOutput struct{ *pulumi.OutputState }

func (GpuProductOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GpuProduct)(nil)).Elem()
}

func (o GpuProductOutput) ToGpuProductOutput() GpuProductOutput {
	return o
}

func (o GpuProductOutput) ToGpuProductOutputWithContext(ctx context.Context) GpuProductOutput {
	return o
}

// Category of the product.
func (o GpuProductOutput) CategoryName() pulumi.StringOutput {
	return o.ApplyT(func(v GpuProduct) string { return v.CategoryName }).(pulumi.StringOutput)
}

// Product description.
func (o GpuProductOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GpuProduct) string { return v.Description }).(pulumi.StringOutput)
}

// Available flavors for this product.
func (o GpuProductOutput) Flavors() GpuFlavorArrayOutput {
	return o.ApplyT(func(v GpuProduct) []GpuFlavor { return v.Flavors }).(GpuFlavorArrayOutput)
}

// Product name.
func (o GpuProductOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GpuProduct) string { return v.Name }).(pulumi.StringOutput)
}

// Product id, use it as GpuInstance productId.
func (o GpuProductOutput) ProductId() pulumi.IntOutput {
	return o.ApplyT(func(v GpuProduct) int { return v.ProductId }).(pulumi.IntOutput)
}

// Raw JSON of the product response.
func (o GpuProductOutput) Raw() pulumi.StringOutput {
	return o.ApplyT(func(v GpuProduct) string { return v.Raw }).(pulumi.StringOutput)
}

type GpuProductArrayOutput struct{ *pulumi.OutputState }

func (GpuProductArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GpuProduct)(nil)).Elem()
}

func (o GpuProductArrayOutput) ToGpuProductArrayOutput() GpuProductArrayOutput {
	return o
}

func (o GpuProductArrayOutput) ToGpuProductArrayOutputWithContext(ctx context.Context) GpuProductArrayOutput {
	return o
}

func (o GpuProductArrayOutput) Index(i pulumi.IntInput) GpuProductOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GpuProduct {
		return vs[0].([]GpuProduct)[vs[1].(int)]
	}).(GpuProductOutput)
}

type GpuSubscriptionArgs struct {
	// Billing cycle, e.g. `m` for monthly or `a` for annual.
	Cycle string `pulumi:"cycle"`
}

// GpuSubscriptionArgsInput is an input type that accepts GpuSubscriptionArgsArgs and GpuSubscriptionArgsOutput values.
// You can construct a concrete instance of `GpuSubscriptionArgsInput` via:
//
//	GpuSubscriptionArgsArgs{...}
type GpuSubscriptionArgsInput interface {
	pulumi.Input

	ToGpuSubscriptionArgsOutput() GpuSubscriptionArgsOutput
	ToGpuSubscriptionArgsOutputWithContext(context.Context) GpuSubscriptionArgsOutput
}

type GpuSubscriptionArgsArgs struct {
	// Billing cycle, e.g. `m` for monthly or `a` for annual.
	Cycle pulumi.StringInput `pulumi:"cycle"`
}

func (GpuSubscriptionArgsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GpuSubscriptionArgs)(nil)).Elem()
}

func (i GpuSubscriptionArgsArgs) ToGpuSubscriptionArgsOutput() GpuSubscriptionArgsOutput {
	return i.ToGpuSubscriptionArgsOutputWithContext(context.Background())
}

func (i GpuSubscriptionArgsArgs) ToGpuSubscriptionArgsOutputWithContext(ctx context.Context) GpuSubscriptionArgsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GpuSubscriptionArgsOutput)
}

func (i GpuSubscriptionArgsArgs) ToGpuSubscriptionArgsPtrOutput() GpuSubscriptionArgsPtrOutput {
	return i.ToGpuSubscriptionArgsPtrOutputWithContext(context.Background())
}

func (i GpuSubscriptionArgsArgs) ToGpuSubscriptionArgsPtrOutputWithContext(ctx context.Context) GpuSubscriptionArgsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GpuSubscriptionArgsOutput).ToGpuSubscriptionArgsPtrOutputWithContext(ctx)
}

// GpuSubscriptionArgsPtrInput is an input type that accepts GpuSubscriptionArgsArgs, GpuSubscriptionArgsPtr and GpuSubscriptionArgsPtrOutput values.
// You can construct a concrete instance of `GpuSubscriptionArgsPtrInput` via:
//
//	        GpuSubscriptionArgsArgs{...}
//
//	or:
//
//	        nil
type GpuSubscriptionArgsPtrInput interface {
	pulumi.Input

	ToGpuSubscriptionArgsPtrOutput() GpuSubscriptionArgsPtrOutput
	ToGpuSubscriptionArgsPtrOutputWithContext(context.Context) GpuSubscriptionArgsPtrOutput
}

type gpuSubscriptionArgsPtrType GpuSubscriptionArgsArgs

func GpuSubscriptionArgsPtr(v *GpuSubscriptionArgsArgs) GpuSubscriptionArgsPtrInput {
	return (*gpuSubscriptionArgsPtrType)(v)
}

func (*gpuSubscriptionArgsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**GpuSubscriptionArgs)(nil)).Elem()
}

func (i *gpuSubscriptionArgsPtrType) ToGpuSubscriptionArgsPtrOutput() GpuSubscriptionArgsPtrOutput {
	return i.ToGpuSubscriptionArgsPtrOutputWithContext(context.Background())
}

func (i *gpuSubscriptionArgsPtrType) ToGpuSubscriptionArgsPtrOutputWithContext(ctx context.Context) GpuSubscriptionArgsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GpuSubscriptionArgsPtrOutput)
}

type GpuSubscriptionArgsOutput struct{ *pulumi.OutputState }

func (GpuSubscriptionArgsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GpuSubscriptionArgs)(nil)).Elem()
}

func (o GpuSubscriptionArgsOutput) ToGpuSubscriptionArgsOutput() GpuSubscriptionArgsOutput {
	return o
}

func (o GpuSubscriptionArgsOutput) ToGpuSubscriptionArgsOutputWithContext(ctx context.Context) GpuSubscriptionArgsOutput {
	return o
}

func (o GpuSubscriptionArgsOutput) ToGpuSubscriptionArgsPtrOutput() GpuSubscriptionArgsPtrOutput {
	return o.ToGpuSubscriptionArgsPtrOutputWithContext(context.Background())
}

func (o GpuSubscriptionArgsOutput) ToGpuSubscriptionArgsPtrOutputWithContext(ctx context.Context) GpuSubscriptionArgsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v GpuSubscriptionArgs) *GpuSubscriptionArgs {
		return &v
	}).(GpuSubscriptionArgsPtrOutput)
}

// Billing cycle, e.g. `m` for monthly or `a` for annual.
func (o GpuSubscriptionArgsOutput) Cycle() pulumi.StringOutput {
	return o.ApplyT(func(v GpuSubscriptionArgs) string { return v.Cycle }).(pulumi.StringOutput)
}

type GpuSubscriptionArgsPtrOutput struct{ *pulumi.OutputState }

func (GpuSubscriptionArgsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GpuSubscriptionArgs)(nil)).Elem()
}

func (o GpuSubscriptionArgsPtrOutput) ToGpuSubscriptionArgsPtrOutput() GpuSubscriptionArgsPtrOutput {
	return o
}

func (o GpuSubscriptionArgsPtrOutput) ToGpuSubscriptionArgsPtrOutputWithContext(ctx context.Context) GpuSubscriptionArgsPtrOutput {
	return o
}

func (o GpuSubscriptionArgsPtrOutput) Elem() GpuSubscriptionArgsOutput {
	return o.ApplyT(func(v *GpuSubscriptionArgs) GpuSubscriptionArgs {
		if v != nil {
			return *v
		}
		var ret GpuSubscriptionArgs
		return ret
	}).(GpuSubscriptionArgsOutput)
}

// Billing cycle, e.g. `m` for monthly or `a` for annual.
func (o GpuSubscriptionArgsPtrOutput) Cycle() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GpuSubscriptionArgs) *string {
		if v == nil {
			return nil
		}
		return &v.Cycle
	}).(pulumi.StringPtrOutput)
}

type NeoliteLastInvoice struct {
	Date        string `pulumi:"date"`
	Datepaid    string `pulumi:"datepaid"`
	Duedate     string `pulumi:"duedate"`
	Id          int    `pulumi:"id"`
	InvoiceType string `pulumi:"invoiceType"`
	PaidId      int    `pulumi:"paidId"`
	Paybefore   string `pulumi:"paybefore"`
	Status      string `pulumi:"status"`
}

type NeoliteLastInvoiceOutput struct{ *pulumi.OutputState }

func (NeoliteLastInvoiceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NeoliteLastInvoice)(nil)).Elem()
}

func (o NeoliteLastInvoiceOutput) ToNeoliteLastInvoiceOutput() NeoliteLastInvoiceOutput {
	return o
}

func (o NeoliteLastInvoiceOutput) ToNeoliteLastInvoiceOutputWithContext(ctx context.Context) NeoliteLastInvoiceOutput {
	return o
}

func (o NeoliteLastInvoiceOutput) Date() pulumi.StringOutput {
	return o.ApplyT(func(v NeoliteLastInvoice) string { return v.Date }).(pulumi.StringOutput)
}

func (o NeoliteLastInvoiceOutput) Datepaid() pulumi.StringOutput {
	return o.ApplyT(func(v NeoliteLastInvoice) string { return v.Datepaid }).(pulumi.StringOutput)
}

func (o NeoliteLastInvoiceOutput) Duedate() pulumi.StringOutput {
	return o.ApplyT(func(v NeoliteLastInvoice) string { return v.Duedate }).(pulumi.StringOutput)
}

func (o NeoliteLastInvoiceOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v NeoliteLastInvoice) int { return v.Id }).(pulumi.IntOutput)
}

func (o NeoliteLastInvoiceOutput) InvoiceType() pulumi.StringOutput {
	return o.ApplyT(func(v NeoliteLastInvoice) string { return v.InvoiceType }).(pulumi.StringOutput)
}

func (o NeoliteLastInvoiceOutput) PaidId() pulumi.IntOutput {
	return o.ApplyT(func(v NeoliteLastInvoice) int { return v.PaidId }).(pulumi.IntOutput)
}

func (o NeoliteLastInvoiceOutput) Paybefore() pulumi.StringOutput {
	return o.ApplyT(func(v NeoliteLastInvoice) string { return v.Paybefore }).(pulumi.StringOutput)
}

func (o NeoliteLastInvoiceOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v NeoliteLastInvoice) string { return v.Status }).(pulumi.StringOutput)
}

type NeoliteOsItem struct {
	Maxcpu int    `pulumi:"maxcpu"`
	Maxmem int    `pulumi:"maxmem"`
	Name   string `pulumi:"name"`
	Node   string `pulumi:"node"`
	Vmid   int    `pulumi:"vmid"`
}

type NeoliteOsItemOutput struct{ *pulumi.OutputState }

func (NeoliteOsItemOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NeoliteOsItem)(nil)).Elem()
}

func (o NeoliteOsItemOutput) ToNeoliteOsItemOutput() NeoliteOsItemOutput {
	return o
}

func (o NeoliteOsItemOutput) ToNeoliteOsItemOutputWithContext(ctx context.Context) NeoliteOsItemOutput {
	return o
}

func (o NeoliteOsItemOutput) Maxcpu() pulumi.IntOutput {
	return o.ApplyT(func(v NeoliteOsItem) int { return v.Maxcpu }).(pulumi.IntOutput)
}

func (o NeoliteOsItemOutput) Maxmem() pulumi.IntOutput {
	return o.ApplyT(func(v NeoliteOsItem) int { return v.Maxmem }).(pulumi.IntOutput)
}

func (o NeoliteOsItemOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v NeoliteOsItem) string { return v.Name }).(pulumi.StringOutput)
}

func (o NeoliteOsItemOutput) Node() pulumi.StringOutput {
	return o.ApplyT(func(v NeoliteOsItem) string { return v.Node }).(pulumi.StringOutput)
}

func (o NeoliteOsItemOutput) Vmid() pulumi.IntOutput {
	return o.ApplyT(func(v NeoliteOsItem) int { return v.Vmid }).(pulumi.IntOutput)
}

type NeoliteOsItemArrayOutput struct{ *pulumi.OutputState }

func (NeoliteOsItemArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]NeoliteOsItem)(nil)).Elem()
}

func (o NeoliteOsItemArrayOutput) ToNeoliteOsItemArrayOutput() NeoliteOsItemArrayOutput {
	return o
}

func (o NeoliteOsItemArrayOutput) ToNeoliteOsItemArrayOutputWithContext(ctx context.Context) NeoliteOsItemArrayOutput {
	return o
}

func (o NeoliteOsItemArrayOutput) Index(i pulumi.IntInput) NeoliteOsItemOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) NeoliteOsItem {
		return vs[0].([]NeoliteOsItem)[vs[1].(int)]
	}).(NeoliteOsItemOutput)
}

type NeolitePlanBilling struct {
	Components []NeolitePlanComponent `pulumi:"components"`
	Cycle      string                 `pulumi:"cycle"`
	Label      string                 `pulumi:"label"`
	Price      int                    `pulumi:"price"`
}

type NeolitePlanBillingOutput struct{ *pulumi.OutputState }

func (NeolitePlanBillingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NeolitePlanBilling)(nil)).Elem()
}

func (o NeolitePlanBillingOutput) ToNeolitePlanBillingOutput() NeolitePlanBillingOutput {
	return o
}

func (o NeolitePlanBillingOutput) ToNeolitePlanBillingOutputWithContext(ctx context.Context) NeolitePlanBillingOutput {
	return o
}

func (o NeolitePlanBillingOutput) Components() NeolitePlanComponentArrayOutput {
	return o.ApplyT(func(v NeolitePlanBilling) []NeolitePlanComponent { return v.Components }).(NeolitePlanComponentArrayOutput)
}

func (o NeolitePlanBillingOutput) Cycle() pulumi.StringOutput {
	return o.ApplyT(func(v NeolitePlanBilling) string { return v.Cycle }).(pulumi.StringOutput)
}

func (o NeolitePlanBillingOutput) Label() pulumi.StringOutput {
	return o.ApplyT(func(v NeolitePlanBilling) string { return v.Label }).(pulumi.StringOutput)
}

func (o NeolitePlanBillingOutput) Price() pulumi.IntOutput {
	return o.ApplyT(func(v NeolitePlanBilling) int { return v.Price }).(pulumi.IntOutput)
}

type NeolitePlanBillingArrayOutput struct{ *pulumi.OutputState }

func (NeolitePlanBillingArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]NeolitePlanBilling)(nil)).Elem()
}

func (o NeolitePlanBillingArrayOutput) ToNeolitePlanBillingArrayOutput() NeolitePlanBillingArrayOutput {
	return o
}

func (o NeolitePlanBillingArrayOutput) ToNeolitePlanBillingArrayOutputWithContext(ctx context.Context) NeolitePlanBillingArrayOutput {
	return o
}

func (o NeolitePlanBillingArrayOutput) Index(i pulumi.IntInput) NeolitePlanBillingOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) NeolitePlanBilling {
		return vs[0].([]NeolitePlanBilling)[vs[1].(int)]
	}).(NeolitePlanBillingOutput)
}

type NeolitePlanComponent struct {
	Field  string             `pulumi:"field"`
	Label  string             `pulumi:"label"`
	Prices []NeolitePlanPrice `pulumi:"prices"`
}

type NeolitePlanComponentOutput struct{ *pulumi.OutputState }

func (NeolitePlanComponentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NeolitePlanComponent)(nil)).Elem()
}

func (o NeolitePlanComponentOutput) ToNeolitePlanComponentOutput() NeolitePlanComponentOutput {
	return o
}

func (o NeolitePlanComponentOutput) ToNeolitePlanComponentOutputWithContext(ctx context.Context) NeolitePlanComponentOutput {
	return o
}

func (o NeolitePlanComponentOutput) Field() pulumi.StringOutput {
	return o.ApplyT(func(v NeolitePlanComponent) string { return v.Field }).(pulumi.StringOutput)
}

func (o NeolitePlanComponentOutput) Label() pulumi.StringOutput {
	return o.ApplyT(func(v NeolitePlanComponent) string { return v.Label }).(pulumi.StringOutput)
}

func (o NeolitePlanComponentOutput) Prices() NeolitePlanPriceArrayOutput {
	return o.ApplyT(func(v NeolitePlanComponent) []NeolitePlanPrice { return v.Prices }).(NeolitePlanPriceArrayOutput)
}

type NeolitePlanComponentArrayOutput struct{ *pulumi.OutputState }

func (NeolitePlanComponentArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]NeolitePlanComponent)(nil)).Elem()
}

func (o NeolitePlanComponentArrayOutput) ToNeolitePlanComponentArrayOutput() NeolitePlanComponentArrayOutput {
	return o
}

func (o NeolitePlanComponentArrayOutput) ToNeolitePlanComponentArrayOutputWithContext(ctx context.Context) NeolitePlanComponentArrayOutput {
	return o
}

func (o NeolitePlanComponentArrayOutput) Index(i pulumi.IntInput) NeolitePlanComponentOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) NeolitePlanComponent {
		return vs[0].([]NeolitePlanComponent)[vs[1].(int)]
	}).(NeolitePlanComponentOutput)
}

type NeolitePlanItem struct {
	Billing      []NeolitePlanBilling `pulumi:"billing"`
	CategoryId   int                  `pulumi:"categoryId"`
	CategoryName string               `pulumi:"categoryName"`
	Description  string               `pulumi:"description"`
	Name         string               `pulumi:"name"`
	Options      NeolitePlanOptions   `pulumi:"options"`
	ProductId    int                  `pulumi:"productId"`
}

type NeolitePlanItemOutput struct{ *pulumi.OutputState }

func (NeolitePlanItemOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NeolitePlanItem)(nil)).Elem()
}

func (o NeolitePlanItemOutput) ToNeolitePlanItemOutput() NeolitePlanItemOutput {
	return o
}

func (o NeolitePlanItemOutput) ToNeolitePlanItemOutputWithContext(ctx context.Context) NeolitePlanItemOutput {
	return o
}

func (o NeolitePlanItemOutput) Billing() NeolitePlanBillingArrayOutput {
	return o.ApplyT(func(v NeolitePlanItem) []NeolitePlanBilling { return v.Billing }).(NeolitePlanBillingArrayOutput)
}

func (o NeolitePlanItemOutput) CategoryId() pulumi.IntOutput {
	return o.ApplyT(func(v NeolitePlanItem) int { return v.CategoryId }).(pulumi.IntOutput)
}

func (o NeolitePlanItemOutput) CategoryName() pulumi.StringOutput {
	return o.ApplyT(func(v NeolitePlanItem) string { return v.CategoryName }).(pulumi.StringOutput)
}

func (o NeolitePlanItemOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v NeolitePlanItem) string { return v.Description }).(pulumi.StringOutput)
}

func (o NeolitePlanItemOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v NeolitePlanItem) string { return v.Name }).(pulumi.StringOutput)
}

func (o NeolitePlanItemOutput) Options() NeolitePlanOptionsOutput {
	return o.ApplyT(func(v NeolitePlanItem) NeolitePlanOptions { return v.Options }).(NeolitePlanOptionsOutput)
}

func (o NeolitePlanItemOutput) ProductId() pulumi.IntOutput {
	return o.ApplyT(func(v NeolitePlanItem) int { return v.ProductId }).(pulumi.IntOutput)
}

type NeolitePlanItemArrayOutput struct{ *pulumi.OutputState }

func (NeolitePlanItemArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]NeolitePlanItem)(nil)).Elem()
}

func (o NeolitePlanItemArrayOutput) ToNeolitePlanItemArrayOutput() NeolitePlanItemArrayOutput {
	return o
}

func (o NeolitePlanItemArrayOutput) ToNeolitePlanItemArrayOutputWithContext(ctx context.Context) NeolitePlanItemArrayOutput {
	return o
}

func (o NeolitePlanItemArrayOutput) Index(i pulumi.IntInput) NeolitePlanItemOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) NeolitePlanItem {
		return vs[0].([]NeolitePlanItem)[vs[1].(int)]
	}).(NeolitePlanItemOutput)
}

type NeolitePlanOptions struct {
	AllowDowngrade int    `pulumi:"allowDowngrade"`
	Cores          int    `pulumi:"cores"`
	Memory         int    `pulumi:"memory"`
	Type           string `pulumi:"type"`
}

type NeolitePlanOptionsOutput struct{ *pulumi.OutputState }

func (NeolitePlanOptionsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NeolitePlanOptions)(nil)).Elem()
}

func (o NeolitePlanOptionsOutput) ToNeolitePlanOptionsOutput() NeolitePlanOptionsOutput {
	return o
}

func (o NeolitePlanOptionsOutput) ToNeolitePlanOptionsOutputWithContext(ctx context.Context) NeolitePlanOptionsOutput {
	return o
}

func (o NeolitePlanOptionsOutput) AllowDowngrade() pulumi.IntOutput {
	return o.ApplyT(func(v NeolitePlanOptions) int { return v.AllowDowngrade }).(pulumi.IntOutput)
}

func (o NeolitePlanOptionsOutput) Cores() pulumi.IntOutput {
	return o.ApplyT(func(v NeolitePlanOptions) int { return v.Cores }).(pulumi.IntOutput)
}

func (o NeolitePlanOptionsOutput) Memory() pulumi.IntOutput {
	return o.ApplyT(func(v NeolitePlanOptions) int { return v.Memory }).(pulumi.IntOutput)
}

func (o NeolitePlanOptionsOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v NeolitePlanOptions) string { return v.Type }).(pulumi.StringOutput)
}

type NeolitePlanPrice struct {
	Price  int `pulumi:"price"`
	QtyMax int `pulumi:"qtyMax"`
	QtyMin int `pulumi:"qtyMin"`
}

type NeolitePlanPriceOutput struct{ *pulumi.OutputState }

func (NeolitePlanPriceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NeolitePlanPrice)(nil)).Elem()
}

func (o NeolitePlanPriceOutput) ToNeolitePlanPriceOutput() NeolitePlanPriceOutput {
	return o
}

func (o NeolitePlanPriceOutput) ToNeolitePlanPriceOutputWithContext(ctx context.Context) NeolitePlanPriceOutput {
	return o
}

func (o NeolitePlanPriceOutput) Price() pulumi.IntOutput {
	return o.ApplyT(func(v NeolitePlanPrice) int { return v.Price }).(pulumi.IntOutput)
}

func (o NeolitePlanPriceOutput) QtyMax() pulumi.IntOutput {
	return o.ApplyT(func(v NeolitePlanPrice) int { return v.QtyMax }).(pulumi.IntOutput)
}

func (o NeolitePlanPriceOutput) QtyMin() pulumi.IntOutput {
	return o.ApplyT(func(v NeolitePlanPrice) int { return v.QtyMin }).(pulumi.IntOutput)
}

type NeolitePlanPriceArrayOutput struct{ *pulumi.OutputState }

func (NeolitePlanPriceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]NeolitePlanPrice)(nil)).Elem()
}

func (o NeolitePlanPriceArrayOutput) ToNeolitePlanPriceArrayOutput() NeolitePlanPriceArrayOutput {
	return o
}

func (o NeolitePlanPriceArrayOutput) ToNeolitePlanPriceArrayOutputWithContext(ctx context.Context) NeolitePlanPriceArrayOutput {
	return o
}

func (o NeolitePlanPriceArrayOutput) Index(i pulumi.IntInput) NeolitePlanPriceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) NeolitePlanPrice {
		return vs[0].([]NeolitePlanPrice)[vs[1].(int)]
	}).(NeolitePlanPriceOutput)
}

type ObjectStorageBucketsBucket struct {
	Acl  string `pulumi:"acl"`
	Name string `pulumi:"name"`
	Raw  string `pulumi:"raw"`
}

type ObjectStorageBucketsBucketOutput struct{ *pulumi.OutputState }

func (ObjectStorageBucketsBucketOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ObjectStorageBucketsBucket)(nil)).Elem()
}

func (o ObjectStorageBucketsBucketOutput) ToObjectStorageBucketsBucketOutput() ObjectStorageBucketsBucketOutput {
	return o
}

func (o ObjectStorageBucketsBucketOutput) ToObjectStorageBucketsBucketOutputWithContext(ctx context.Context) ObjectStorageBucketsBucketOutput {
	return o
}

func (o ObjectStorageBucketsBucketOutput) Acl() pulumi.StringOutput {
	return o.ApplyT(func(v ObjectStorageBucketsBucket) string { return v.Acl }).(pulumi.StringOutput)
}

func (o ObjectStorageBucketsBucketOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v ObjectStorageBucketsBucket) string { return v.Name }).(pulumi.StringOutput)
}

func (o ObjectStorageBucketsBucketOutput) Raw() pulumi.StringOutput {
	return o.ApplyT(func(v ObjectStorageBucketsBucket) string { return v.Raw }).(pulumi.StringOutput)
}

type ObjectStorageBucketsBucketArrayOutput struct{ *pulumi.OutputState }

func (ObjectStorageBucketsBucketArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ObjectStorageBucketsBucket)(nil)).Elem()
}

func (o ObjectStorageBucketsBucketArrayOutput) ToObjectStorageBucketsBucketArrayOutput() ObjectStorageBucketsBucketArrayOutput {
	return o
}

func (o ObjectStorageBucketsBucketArrayOutput) ToObjectStorageBucketsBucketArrayOutputWithContext(ctx context.Context) ObjectStorageBucketsBucketArrayOutput {
	return o
}

func (o ObjectStorageBucketsBucketArrayOutput) Index(i pulumi.IntInput) ObjectStorageBucketsBucketOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ObjectStorageBucketsBucket {
		return vs[0].([]ObjectStorageBucketsBucket)[vs[1].(int)]
	}).(ObjectStorageBucketsBucketOutput)
}

type ObjectStorageCredentialsCredential struct {
	AccessKey string `pulumi:"accessKey"`
	Active    bool   `pulumi:"active"`
}

type ObjectStorageCredentialsCredentialOutput struct{ *pulumi.OutputState }

func (ObjectStorageCredentialsCredentialOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ObjectStorageCredentialsCredential)(nil)).Elem()
}

func (o ObjectStorageCredentialsCredentialOutput) ToObjectStorageCredentialsCredentialOutput() ObjectStorageCredentialsCredentialOutput {
	return o
}

func (o ObjectStorageCredentialsCredentialOutput) ToObjectStorageCredentialsCredentialOutputWithContext(ctx context.Context) ObjectStorageCredentialsCredentialOutput {
	return o
}

func (o ObjectStorageCredentialsCredentialOutput) AccessKey() pulumi.StringOutput {
	return o.ApplyT(func(v ObjectStorageCredentialsCredential) string { return v.AccessKey }).(pulumi.StringOutput)
}

func (o ObjectStorageCredentialsCredentialOutput) Active() pulumi.BoolOutput {
	return o.ApplyT(func(v ObjectStorageCredentialsCredential) bool { return v.Active }).(pulumi.BoolOutput)
}

type ObjectStorageCredentialsCredentialArrayOutput struct{ *pulumi.OutputState }

func (ObjectStorageCredentialsCredentialArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ObjectStorageCredentialsCredential)(nil)).Elem()
}

func (o ObjectStorageCredentialsCredentialArrayOutput) ToObjectStorageCredentialsCredentialArrayOutput() ObjectStorageCredentialsCredentialArrayOutput {
	return o
}

func (o ObjectStorageCredentialsCredentialArrayOutput) ToObjectStorageCredentialsCredentialArrayOutputWithContext(ctx context.Context) ObjectStorageCredentialsCredentialArrayOutput {
	return o
}

func (o ObjectStorageCredentialsCredentialArrayOutput) Index(i pulumi.IntInput) ObjectStorageCredentialsCredentialOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ObjectStorageCredentialsCredential {
		return vs[0].([]ObjectStorageCredentialsCredential)[vs[1].(int)]
	}).(ObjectStorageCredentialsCredentialOutput)
}

type ObjectStorageInstancesInstance struct {
	Id        string `pulumi:"id"`
	Label     string `pulumi:"label"`
	ProductId int    `pulumi:"productId"`
	Quota     int    `pulumi:"quota"`
	Raw       string `pulumi:"raw"`
	Status    string `pulumi:"status"`
}

type ObjectStorageInstancesInstanceOutput struct{ *pulumi.OutputState }

func (ObjectStorageInstancesInstanceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ObjectStorageInstancesInstance)(nil)).Elem()
}

func (o ObjectStorageInstancesInstanceOutput) ToObjectStorageInstancesInstanceOutput() ObjectStorageInstancesInstanceOutput {
	return o
}

func (o ObjectStorageInstancesInstanceOutput) ToObjectStorageInstancesInstanceOutputWithContext(ctx context.Context) ObjectStorageInstancesInstanceOutput {
	return o
}

func (o ObjectStorageInstancesInstanceOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v ObjectStorageInstancesInstance) string { return v.Id }).(pulumi.StringOutput)
}

func (o ObjectStorageInstancesInstanceOutput) Label() pulumi.StringOutput {
	return o.ApplyT(func(v ObjectStorageInstancesInstance) string { return v.Label }).(pulumi.StringOutput)
}

func (o ObjectStorageInstancesInstanceOutput) ProductId() pulumi.IntOutput {
	return o.ApplyT(func(v ObjectStorageInstancesInstance) int { return v.ProductId }).(pulumi.IntOutput)
}

func (o ObjectStorageInstancesInstanceOutput) Quota() pulumi.IntOutput {
	return o.ApplyT(func(v ObjectStorageInstancesInstance) int { return v.Quota }).(pulumi.IntOutput)
}

func (o ObjectStorageInstancesInstanceOutput) Raw() pulumi.StringOutput {
	return o.ApplyT(func(v ObjectStorageInstancesInstance) string { return v.Raw }).(pulumi.StringOutput)
}

func (o ObjectStorageInstancesInstanceOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v ObjectStorageInstancesInstance) string { return v.Status }).(pulumi.StringOutput)
}

type ObjectStorageInstancesInstanceArrayOutput struct{ *pulumi.OutputState }

func (ObjectStorageInstancesInstanceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ObjectStorageInstancesInstance)(nil)).Elem()
}

func (o ObjectStorageInstancesInstanceArrayOutput) ToObjectStorageInstancesInstanceArrayOutput() ObjectStorageInstancesInstanceArrayOutput {
	return o
}

func (o ObjectStorageInstancesInstanceArrayOutput) ToObjectStorageInstancesInstanceArrayOutputWithContext(ctx context.Context) ObjectStorageInstancesInstanceArrayOutput {
	return o
}

func (o ObjectStorageInstancesInstanceArrayOutput) Index(i pulumi.IntInput) ObjectStorageInstancesInstanceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ObjectStorageInstancesInstance {
		return vs[0].([]ObjectStorageInstancesInstance)[vs[1].(int)]
	}).(ObjectStorageInstancesInstanceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GpuOnDemandArgsInput)(nil)).Elem(), GpuOnDemandArgsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GpuOnDemandArgsPtrInput)(nil)).Elem(), GpuOnDemandArgsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GpuSubscriptionArgsInput)(nil)).Elem(), GpuSubscriptionArgsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GpuSubscriptionArgsPtrInput)(nil)).Elem(), GpuSubscriptionArgsArgs{})
	pulumi.RegisterOutputType(BaremetalProductOutput{})
	pulumi.RegisterOutputType(BaremetalProductArrayOutput{})
	pulumi.RegisterOutputType(GpuFlavorOutput{})
	pulumi.RegisterOutputType(GpuFlavorArrayOutput{})
	pulumi.RegisterOutputType(GpuOnDemandArgsOutput{})
	pulumi.RegisterOutputType(GpuOnDemandArgsPtrOutput{})
	pulumi.RegisterOutputType(GpuProductOutput{})
	pulumi.RegisterOutputType(GpuProductArrayOutput{})
	pulumi.RegisterOutputType(GpuSubscriptionArgsOutput{})
	pulumi.RegisterOutputType(GpuSubscriptionArgsPtrOutput{})
	pulumi.RegisterOutputType(NeoliteLastInvoiceOutput{})
	pulumi.RegisterOutputType(NeoliteOsItemOutput{})
	pulumi.RegisterOutputType(NeoliteOsItemArrayOutput{})
	pulumi.RegisterOutputType(NeolitePlanBillingOutput{})
	pulumi.RegisterOutputType(NeolitePlanBillingArrayOutput{})
	pulumi.RegisterOutputType(NeolitePlanComponentOutput{})
	pulumi.RegisterOutputType(NeolitePlanComponentArrayOutput{})
	pulumi.RegisterOutputType(NeolitePlanItemOutput{})
	pulumi.RegisterOutputType(NeolitePlanItemArrayOutput{})
	pulumi.RegisterOutputType(NeolitePlanOptionsOutput{})
	pulumi.RegisterOutputType(NeolitePlanPriceOutput{})
	pulumi.RegisterOutputType(NeolitePlanPriceArrayOutput{})
	pulumi.RegisterOutputType(ObjectStorageBucketsBucketOutput{})
	pulumi.RegisterOutputType(ObjectStorageBucketsBucketArrayOutput{})
	pulumi.RegisterOutputType(ObjectStorageCredentialsCredentialOutput{})
	pulumi.RegisterOutputType(ObjectStorageCredentialsCredentialArrayOutput{})
	pulumi.RegisterOutputType(ObjectStorageInstancesInstanceOutput{})
	pulumi.RegisterOutputType(ObjectStorageInstancesInstanceArrayOutput{})
}
