# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GpuOnDemandArgsArgs',
    'GpuOnDemandArgsArgsDict',
    'GpuSubscriptionArgsArgs',
    'GpuSubscriptionArgsArgsDict',
]

class GpuOnDemandArgsArgsDict(TypedDict):
    additional_hours: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    Additional hours to reserve. Defaults to 0.
    """

@pulumi.input_type
class GpuOnDemandArgsArgs:
    def __init__(__self__, *,
                 additional_hours: pulumi.Input[Optional[_builtins.int]] = None):
        """
        :param pulumi.Input[_builtins.int] additional_hours: Additional hours to reserve. Defaults to 0.
        """
        if additional_hours is not None:
            pulumi.set(__self__, "additional_hours", additional_hours)

    @_builtins.property
    @pulumi.getter(name="additionalHours")
    def additional_hours(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Additional hours to reserve. Defaults to 0.
        """
        return pulumi.get(self, "additional_hours")

    @additional_hours.setter
    def additional_hours(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "additional_hours", value)


class GpuSubscriptionArgsArgsDict(TypedDict):
    cycle: pulumi.Input[_builtins.str]
    """
    Billing cycle, e.g. `m` for monthly or `a` for annual.
    """

@pulumi.input_type
class GpuSubscriptionArgsArgs:
    def __init__(__self__, *,
                 cycle: pulumi.Input[_builtins.str]):
        """
        :param pulumi.Input[_builtins.str] cycle: Billing cycle, e.g. `m` for monthly or `a` for annual.
        """
        pulumi.set(__self__, "cycle", cycle)

    @_builtins.property
    @pulumi.getter
    def cycle(self) -> pulumi.Input[_builtins.str]:
        """
        Billing cycle, e.g. `m` for monthly or `a` for annual.
        """
        return pulumi.get(self, "cycle")

    @cycle.setter
    def cycle(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "cycle", value)


