# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'BaremetalOpenvpnResult',
    'AwaitableBaremetalOpenvpnResult',
    'baremetal_openvpn',
    'baremetal_openvpn_output',
]

@pulumi.output_type
class BaremetalOpenvpnResult:
    def __init__(__self__, config=None, raw=None):
        if config and not isinstance(config, str):
            raise TypeError("Expected argument 'config' to be a str")
        pulumi.set(__self__, "config", config)
        if raw and not isinstance(raw, str):
            raise TypeError("Expected argument 'raw' to be a str")
        pulumi.set(__self__, "raw", raw)

    @_builtins.property
    @pulumi.getter
    def config(self) -> _builtins.str:
        """
        OpenVPN client config from `GET /baremetals/openvpn`.
        """
        return pulumi.get(self, "config")

    @_builtins.property
    @pulumi.getter
    def raw(self) -> _builtins.str:
        """
        Raw JSON of the full response.
        """
        return pulumi.get(self, "raw")


class AwaitableBaremetalOpenvpnResult(BaremetalOpenvpnResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return BaremetalOpenvpnResult(
            config=self.config,
            raw=self.raw)


def baremetal_openvpn(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableBaremetalOpenvpnResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('biznetgio:index:baremetalOpenvpn', __args__, opts=opts, typ=BaremetalOpenvpnResult).value

    return AwaitableBaremetalOpenvpnResult(
        config=pulumi.get(__ret__, 'config'),
        raw=pulumi.get(__ret__, 'raw'))
def baremetal_openvpn_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[BaremetalOpenvpnResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('biznetgio:index:baremetalOpenvpn', __args__, opts=opts, typ=BaremetalOpenvpnResult)
    return __ret__.apply(lambda __response__: BaremetalOpenvpnResult(
        config=pulumi.get(__response__, 'config'),
        raw=pulumi.get(__response__, 'raw')))
