# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'NeoliteProOsListResult',
    'AwaitableNeoliteProOsListResult',
    'neolite_pro_os_list',
    'neolite_pro_os_list_output',
]

@pulumi.output_type
class NeoliteProOsListResult:
    def __init__(__self__, oss=None):
        if oss and not isinstance(oss, list):
            raise TypeError("Expected argument 'oss' to be a list")
        pulumi.set(__self__, "oss", oss)

    @_builtins.property
    @pulumi.getter
    def oss(self) -> Sequence['outputs.NeoliteOsItem']:
        return pulumi.get(self, "oss")


class AwaitableNeoliteProOsListResult(NeoliteProOsListResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return NeoliteProOsListResult(
            oss=self.oss)


def neolite_pro_os_list(product_id: Optional[_builtins.int] = None,
                        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableNeoliteProOsListResult:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.int product_id: Product id NEO Lite Pro.
    """
    __args__ = dict()
    __args__['productId'] = product_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('biznetgio:index:neoliteProOsList', __args__, opts=opts, typ=NeoliteProOsListResult).value

    return AwaitableNeoliteProOsListResult(
        oss=pulumi.get(__ret__, 'oss'))
def neolite_pro_os_list_output(product_id: pulumi.Input[Optional[_builtins.int]] = None,
                               opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[NeoliteProOsListResult]:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.int product_id: Product id NEO Lite Pro.
    """
    __args__ = dict()
    __args__['productId'] = product_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('biznetgio:index:neoliteProOsList', __args__, opts=opts, typ=NeoliteProOsListResult)
    return __ret__.apply(lambda __response__: NeoliteProOsListResult(
        oss=pulumi.get(__response__, 'oss')))
