# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'NeoliteProStorageUpgradeOptionsResult',
    'AwaitableNeoliteProStorageUpgradeOptionsResult',
    'neolite_pro_storage_upgrade_options',
    'neolite_pro_storage_upgrade_options_output',
]

@pulumi.output_type
class NeoliteProStorageUpgradeOptionsResult:
    def __init__(__self__, raw=None):
        if raw and not isinstance(raw, str):
            raise TypeError("Expected argument 'raw' to be a str")
        pulumi.set(__self__, "raw", raw)

    @_builtins.property
    @pulumi.getter
    def raw(self) -> _builtins.str:
        return pulumi.get(self, "raw")


class AwaitableNeoliteProStorageUpgradeOptionsResult(NeoliteProStorageUpgradeOptionsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return NeoliteProStorageUpgradeOptionsResult(
            raw=self.raw)


def neolite_pro_storage_upgrade_options(account_id: Optional[_builtins.int] = None,
                                        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableNeoliteProStorageUpgradeOptionsResult:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.int account_id: Account id VM NEO Lite Pro.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('biznetgio:index:neoliteProStorageUpgradeOptions', __args__, opts=opts, typ=NeoliteProStorageUpgradeOptionsResult).value

    return AwaitableNeoliteProStorageUpgradeOptionsResult(
        raw=pulumi.get(__ret__, 'raw'))
def neolite_pro_storage_upgrade_options_output(account_id: pulumi.Input[Optional[_builtins.int]] = None,
                                               opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[NeoliteProStorageUpgradeOptionsResult]:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.int account_id: Account id VM NEO Lite Pro.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('biznetgio:index:neoliteProStorageUpgradeOptions', __args__, opts=opts, typ=NeoliteProStorageUpgradeOptionsResult)
    return __ret__.apply(lambda __response__: NeoliteProStorageUpgradeOptionsResult(
        raw=pulumi.get(__response__, 'raw')))
