# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['NeoliteProDiskArgs', 'NeoliteProDisk']

@pulumi.input_type
class NeoliteProDiskArgs:
    def __init__(__self__, *,
                 cycle: pulumi.Input[_builtins.str],
                 neolite_account_id: pulumi.Input[_builtins.int],
                 product_id: pulumi.Input[_builtins.int],
                 pay_with_credit_card: pulumi.Input[Optional[_builtins.bool]] = None,
                 promocode: pulumi.Input[Optional[_builtins.str]] = None,
                 service_name: pulumi.Input[Optional[_builtins.str]] = None,
                 size: pulumi.Input[Optional[_builtins.int]] = None):
        """
        The set of arguments for constructing a NeoliteProDisk resource.

        :param pulumi.Input[_builtins.str] cycle: Billing cycle: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
        :param pulumi.Input[_builtins.int] neolite_account_id: Account id of the NEO Lite Pro VM the disk is attached to.
        :param pulumi.Input[_builtins.int] product_id: Disk product id from the `/neolite-pros/disks/products` endpoint.
        :param pulumi.Input[_builtins.bool] pay_with_credit_card: Pay the invoice with the registered credit card at order time. Defaults to true (auto-charge); set false to leave it unpaid in the portal until settled.
        :param pulumi.Input[_builtins.str] promocode: Promo code to apply at order.
        :param pulumi.Input[_builtins.str] service_name: Disk service name. Defaults to `service-name`.
        :param pulumi.Input[_builtins.int] size: Disk size (GB). Defaults to 30 (minimum disk-pro product). Can only go up, never down.
        """
        pulumi.set(__self__, "cycle", cycle)
        pulumi.set(__self__, "neolite_account_id", neolite_account_id)
        pulumi.set(__self__, "product_id", product_id)
        if pay_with_credit_card is None:
            pay_with_credit_card = True
        if pay_with_credit_card is not None:
            pulumi.set(__self__, "pay_with_credit_card", pay_with_credit_card)
        if promocode is None:
            promocode = ''
        if promocode is not None:
            pulumi.set(__self__, "promocode", promocode)
        if service_name is None:
            service_name = 'service-name'
        if service_name is not None:
            pulumi.set(__self__, "service_name", service_name)
        if size is None:
            size = 30
        if size is not None:
            pulumi.set(__self__, "size", size)

    @_builtins.property
    @pulumi.getter
    def cycle(self) -> pulumi.Input[_builtins.str]:
        """
        Billing cycle: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
        """
        return pulumi.get(self, "cycle")

    @cycle.setter
    def cycle(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "cycle", value)

    @_builtins.property
    @pulumi.getter(name="neoliteAccountId")
    def neolite_account_id(self) -> pulumi.Input[_builtins.int]:
        """
        Account id of the NEO Lite Pro VM the disk is attached to.
        """
        return pulumi.get(self, "neolite_account_id")

    @neolite_account_id.setter
    def neolite_account_id(self, value: pulumi.Input[_builtins.int]):
        pulumi.set(self, "neolite_account_id", value)

    @_builtins.property
    @pulumi.getter(name="productId")
    def product_id(self) -> pulumi.Input[_builtins.int]:
        """
        Disk product id from the `/neolite-pros/disks/products` endpoint.
        """
        return pulumi.get(self, "product_id")

    @product_id.setter
    def product_id(self, value: pulumi.Input[_builtins.int]):
        pulumi.set(self, "product_id", value)

    @_builtins.property
    @pulumi.getter(name="payWithCreditCard")
    def pay_with_credit_card(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Pay the invoice with the registered credit card at order time. Defaults to true (auto-charge); set false to leave it unpaid in the portal until settled.
        """
        return pulumi.get(self, "pay_with_credit_card")

    @pay_with_credit_card.setter
    def pay_with_credit_card(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "pay_with_credit_card", value)

    @_builtins.property
    @pulumi.getter
    def promocode(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Promo code to apply at order.
        """
        return pulumi.get(self, "promocode")

    @promocode.setter
    def promocode(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "promocode", value)

    @_builtins.property
    @pulumi.getter(name="serviceName")
    def service_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Disk service name. Defaults to `service-name`.
        """
        return pulumi.get(self, "service_name")

    @service_name.setter
    def service_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "service_name", value)

    @_builtins.property
    @pulumi.getter
    def size(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Disk size (GB). Defaults to 30 (minimum disk-pro product). Can only go up, never down.
        """
        return pulumi.get(self, "size")

    @size.setter
    def size(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "size", value)


@pulumi.type_token("biznetgio:index:NeoliteProDisk")
class NeoliteProDisk(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cycle: pulumi.Input[Optional[_builtins.str]] = None,
                 neolite_account_id: pulumi.Input[Optional[_builtins.int]] = None,
                 pay_with_credit_card: pulumi.Input[Optional[_builtins.bool]] = None,
                 product_id: pulumi.Input[Optional[_builtins.int]] = None,
                 promocode: pulumi.Input[Optional[_builtins.str]] = None,
                 service_name: pulumi.Input[Optional[_builtins.str]] = None,
                 size: pulumi.Input[Optional[_builtins.int]] = None,
                 __props__=None):
        """
        Create a NeoliteProDisk resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] cycle: Billing cycle: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
        :param pulumi.Input[_builtins.int] neolite_account_id: Account id of the NEO Lite Pro VM the disk is attached to.
        :param pulumi.Input[_builtins.bool] pay_with_credit_card: Pay the invoice with the registered credit card at order time. Defaults to true (auto-charge); set false to leave it unpaid in the portal until settled.
        :param pulumi.Input[_builtins.int] product_id: Disk product id from the `/neolite-pros/disks/products` endpoint.
        :param pulumi.Input[_builtins.str] promocode: Promo code to apply at order.
        :param pulumi.Input[_builtins.str] service_name: Disk service name. Defaults to `service-name`.
        :param pulumi.Input[_builtins.int] size: Disk size (GB). Defaults to 30 (minimum disk-pro product). Can only go up, never down.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: NeoliteProDiskArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a NeoliteProDisk resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param NeoliteProDiskArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(NeoliteProDiskArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cycle: pulumi.Input[Optional[_builtins.str]] = None,
                 neolite_account_id: pulumi.Input[Optional[_builtins.int]] = None,
                 pay_with_credit_card: pulumi.Input[Optional[_builtins.bool]] = None,
                 product_id: pulumi.Input[Optional[_builtins.int]] = None,
                 promocode: pulumi.Input[Optional[_builtins.str]] = None,
                 service_name: pulumi.Input[Optional[_builtins.str]] = None,
                 size: pulumi.Input[Optional[_builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = NeoliteProDiskArgs.__new__(NeoliteProDiskArgs)

            if cycle is None and not opts.urn:
                raise TypeError("Missing required property 'cycle'")
            __props__.__dict__["cycle"] = cycle
            if neolite_account_id is None and not opts.urn:
                raise TypeError("Missing required property 'neolite_account_id'")
            __props__.__dict__["neolite_account_id"] = neolite_account_id
            if pay_with_credit_card is None:
                pay_with_credit_card = True
            __props__.__dict__["pay_with_credit_card"] = pay_with_credit_card
            if product_id is None and not opts.urn:
                raise TypeError("Missing required property 'product_id'")
            __props__.__dict__["product_id"] = product_id
            if promocode is None:
                promocode = ''
            __props__.__dict__["promocode"] = promocode
            if service_name is None:
                service_name = 'service-name'
            __props__.__dict__["service_name"] = service_name
            if size is None:
                size = 30
            __props__.__dict__["size"] = size
            __props__.__dict__["order_id"] = None
            __props__.__dict__["raw"] = None
            __props__.__dict__["status"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["raw"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(NeoliteProDisk, __self__).__init__(
            'biznetgio:index:NeoliteProDisk',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'NeoliteProDisk':
        """
        Get an existing NeoliteProDisk resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = NeoliteProDiskArgs.__new__(NeoliteProDiskArgs)

        __props__.__dict__["cycle"] = None
        __props__.__dict__["neolite_account_id"] = None
        __props__.__dict__["order_id"] = None
        __props__.__dict__["pay_with_credit_card"] = None
        __props__.__dict__["product_id"] = None
        __props__.__dict__["promocode"] = None
        __props__.__dict__["raw"] = None
        __props__.__dict__["service_name"] = None
        __props__.__dict__["size"] = None
        __props__.__dict__["status"] = None
        return NeoliteProDisk(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def cycle(self) -> pulumi.Output[_builtins.str]:
        """
        Billing cycle: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
        """
        return pulumi.get(self, "cycle")

    @_builtins.property
    @pulumi.getter(name="neoliteAccountId")
    def neolite_account_id(self) -> pulumi.Output[_builtins.int]:
        """
        Account id of the NEO Lite Pro VM the disk is attached to.
        """
        return pulumi.get(self, "neolite_account_id")

    @_builtins.property
    @pulumi.getter(name="orderId")
    def order_id(self) -> pulumi.Output[_builtins.str]:
        """
        Order id from the creation response.
        """
        return pulumi.get(self, "order_id")

    @_builtins.property
    @pulumi.getter(name="payWithCreditCard")
    def pay_with_credit_card(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Pay the invoice with the registered credit card at order time. Defaults to true (auto-charge); set false to leave it unpaid in the portal until settled.
        """
        return pulumi.get(self, "pay_with_credit_card")

    @_builtins.property
    @pulumi.getter(name="productId")
    def product_id(self) -> pulumi.Output[_builtins.int]:
        """
        Disk product id from the `/neolite-pros/disks/products` endpoint.
        """
        return pulumi.get(self, "product_id")

    @_builtins.property
    @pulumi.getter
    def promocode(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Promo code to apply at order.
        """
        return pulumi.get(self, "promocode")

    @_builtins.property
    @pulumi.getter
    def raw(self) -> pulumi.Output[_builtins.str]:
        """
        Raw JSON of the last-read disk response, for accessing fields not yet modeled.
        """
        return pulumi.get(self, "raw")

    @_builtins.property
    @pulumi.getter(name="serviceName")
    def service_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Disk service name. Defaults to `service-name`.
        """
        return pulumi.get(self, "service_name")

    @_builtins.property
    @pulumi.getter
    def size(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Disk size (GB). Defaults to 30 (minimum disk-pro product). Can only go up, never down.
        """
        return pulumi.get(self, "size")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        Disk status (Active, Pending, Suspended, Terminated).
        """
        return pulumi.get(self, "status")

