# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'ObjectStorageCredentialsResult',
    'AwaitableObjectStorageCredentialsResult',
    'object_storage_credentials',
    'object_storage_credentials_output',
]

@pulumi.output_type
class ObjectStorageCredentialsResult:
    def __init__(__self__, credentials=None):
        if credentials and not isinstance(credentials, list):
            raise TypeError("Expected argument 'credentials' to be a list")
        pulumi.set(__self__, "credentials", credentials)

    @_builtins.property
    @pulumi.getter
    def credentials(self) -> Sequence['outputs.ObjectStorageCredentialsCredential']:
        """
        List of credentials (access key + active state only; secret keys tidak pernah dikeluarkan).
        """
        return pulumi.get(self, "credentials")


class AwaitableObjectStorageCredentialsResult(ObjectStorageCredentialsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ObjectStorageCredentialsResult(
            credentials=self.credentials)


def object_storage_credentials(account_id: Optional[_builtins.str] = None,
                               opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableObjectStorageCredentialsResult:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str account_id: Object storage instance account id.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('biznetgio:index:objectStorageCredentials', __args__, opts=opts, typ=ObjectStorageCredentialsResult).value

    return AwaitableObjectStorageCredentialsResult(
        credentials=pulumi.get(__ret__, 'credentials'))
def object_storage_credentials_output(account_id: pulumi.Input[Optional[_builtins.str]] = None,
                                      opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[ObjectStorageCredentialsResult]:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str account_id: Object storage instance account id.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('biznetgio:index:objectStorageCredentials', __args__, opts=opts, typ=ObjectStorageCredentialsResult)
    return __ret__.apply(lambda __response__: ObjectStorageCredentialsResult(
        credentials=pulumi.get(__response__, 'credentials')))
