// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GpuOnDemandArgsArgs {
    /**
     * Additional hours to reserve. Defaults to 0.
     */
    additionalHours?: pulumi.Input<number | undefined>;
}

export interface GpuSubscriptionArgsArgs {
    /**
     * Billing cycle, e.g. `m` for monthly or `a` for annual.
     */
    cycle: pulumi.Input<string>;
}

