// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio.ren.shirasaka_biznetgio.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GpuSubscriptionArgs {
    /**
     * @return Billing cycle, e.g. `m` for monthly or `a` for annual.
     * 
     */
    private String cycle;

    private GpuSubscriptionArgs() {}
    /**
     * @return Billing cycle, e.g. `m` for monthly or `a` for annual.
     * 
     */
    public String cycle() {
        return this.cycle;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GpuSubscriptionArgs defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String cycle;
        public Builder() {}
        public Builder(GpuSubscriptionArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.cycle = defaults.cycle;
        }

        @CustomType.Setter
        public Builder cycle(String cycle) {
            if (cycle == null) {
              throw new MissingRequiredPropertyException("GpuSubscriptionArgs", "cycle");
            }
            this.cycle = cycle;
            return this;
        }
        public GpuSubscriptionArgs build() {
            final var _resultValue = new GpuSubscriptionArgs();
            _resultValue.cycle = cycle;
            return _resultValue;
        }
    }
}
