// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio.ren.shirasaka_biznetgio.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import ren.shirasaka.biznetgio.ren.shirasaka_biznetgio.outputs.NeolitePlanPrice;

@CustomType
public final class NeolitePlanComponent {
    private String field;
    private String label;
    private List<NeolitePlanPrice> prices;

    private NeolitePlanComponent() {}
    public String field() {
        return this.field;
    }
    public String label() {
        return this.label;
    }
    public List<NeolitePlanPrice> prices() {
        return this.prices;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NeolitePlanComponent defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String field;
        private String label;
        private List<NeolitePlanPrice> prices;
        public Builder() {}
        public Builder(NeolitePlanComponent defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.field = defaults.field;
    	      this.label = defaults.label;
    	      this.prices = defaults.prices;
        }

        @CustomType.Setter
        public Builder field(String field) {
            if (field == null) {
              throw new MissingRequiredPropertyException("NeolitePlanComponent", "field");
            }
            this.field = field;
            return this;
        }
        @CustomType.Setter
        public Builder label(String label) {
            if (label == null) {
              throw new MissingRequiredPropertyException("NeolitePlanComponent", "label");
            }
            this.label = label;
            return this;
        }
        @CustomType.Setter
        public Builder prices(List<NeolitePlanPrice> prices) {
            if (prices == null) {
              throw new MissingRequiredPropertyException("NeolitePlanComponent", "prices");
            }
            this.prices = prices;
            return this;
        }
        public Builder prices(NeolitePlanPrice... prices) {
            return prices(List.of(prices));
        }
        public NeolitePlanComponent build() {
            final var _resultValue = new NeolitePlanComponent();
            _resultValue.field = field;
            _resultValue.label = label;
            _resultValue.prices = prices;
            return _resultValue;
        }
    }
}
