// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio.ren.shirasaka_biznetgio.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.List;
import java.util.Objects;
import ren.shirasaka.biznetgio.ren.shirasaka_biznetgio.outputs.NeolitePlanItem;

@CustomType
public final class NeoliteProProductsResult {
    private List<NeolitePlanItem> products;

    private NeoliteProProductsResult() {}
    public List<NeolitePlanItem> products() {
        return this.products;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NeoliteProProductsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<NeolitePlanItem> products;
        public Builder() {}
        public Builder(NeoliteProProductsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.products = defaults.products;
        }

        @CustomType.Setter
        public Builder products(List<NeolitePlanItem> products) {
            if (products == null) {
              throw new MissingRequiredPropertyException("NeoliteProProductsResult", "products");
            }
            this.products = products;
            return this;
        }
        public Builder products(NeolitePlanItem... products) {
            return products(List.of(products));
        }
        public NeoliteProProductsResult build() {
            final var _resultValue = new NeoliteProProductsResult();
            _resultValue.products = products;
            return _resultValue;
        }
    }
}
