// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ren.shirasaka.biznetgio.ren.shirasaka_biznetgio.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class NeoliteOsItem {
    private Integer maxcpu;
    private Integer maxmem;
    private String name;
    private String node;
    private Integer vmid;

    private NeoliteOsItem() {}
    public Integer maxcpu() {
        return this.maxcpu;
    }
    public Integer maxmem() {
        return this.maxmem;
    }
    public String name() {
        return this.name;
    }
    public String node() {
        return this.node;
    }
    public Integer vmid() {
        return this.vmid;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NeoliteOsItem defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer maxcpu;
        private Integer maxmem;
        private String name;
        private String node;
        private Integer vmid;
        public Builder() {}
        public Builder(NeoliteOsItem defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.maxcpu = defaults.maxcpu;
    	      this.maxmem = defaults.maxmem;
    	      this.name = defaults.name;
    	      this.node = defaults.node;
    	      this.vmid = defaults.vmid;
        }

        @CustomType.Setter
        public Builder maxcpu(Integer maxcpu) {
            if (maxcpu == null) {
              throw new MissingRequiredPropertyException("NeoliteOsItem", "maxcpu");
            }
            this.maxcpu = maxcpu;
            return this;
        }
        @CustomType.Setter
        public Builder maxmem(Integer maxmem) {
            if (maxmem == null) {
              throw new MissingRequiredPropertyException("NeoliteOsItem", "maxmem");
            }
            this.maxmem = maxmem;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("NeoliteOsItem", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder node(String node) {
            if (node == null) {
              throw new MissingRequiredPropertyException("NeoliteOsItem", "node");
            }
            this.node = node;
            return this;
        }
        @CustomType.Setter
        public Builder vmid(Integer vmid) {
            if (vmid == null) {
              throw new MissingRequiredPropertyException("NeoliteOsItem", "vmid");
            }
            this.vmid = vmid;
            return this;
        }
        public NeoliteOsItem build() {
            final var _resultValue = new NeoliteOsItem();
            _resultValue.maxcpu = maxcpu;
            _resultValue.maxmem = maxmem;
            _resultValue.name = name;
            _resultValue.node = node;
            _resultValue.vmid = vmid;
            return _resultValue;
        }
    }
}
