// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class BaremetalAdditionalIp extends pulumi.CustomResource {
    /**
     * Get an existing BaremetalAdditionalIp resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): BaremetalAdditionalIp {
        return new BaremetalAdditionalIp(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'biznetgio:index:BaremetalAdditionalIp';

    /**
     * Returns true if the given object is an instance of BaremetalAdditionalIp.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BaremetalAdditionalIp {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BaremetalAdditionalIp.__pulumiType;
    }

    /**
     * Creation timestamp (alias of created_at/date_created).
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Billing cycle, e.g. `m` for monthly or `a` for annual.
     */
    declare public readonly cycle: pulumi.Output<string>;
    /**
     * Assigned IP address, when present in the response.
     */
    declare public /*out*/ readonly ipAddress: pulumi.Output<string>;
    /**
     * Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
     */
    declare public readonly payWithCreditCard: pulumi.Output<boolean | undefined>;
    /**
     * Product id from `GET /baremetal-additional-ips/products`.
     */
    declare public readonly productId: pulumi.Output<number>;
    /**
     * Promo code to apply at creation.
     */
    declare public readonly promocode: pulumi.Output<string | undefined>;
    /**
     * Raw JSON of the last read response, for anything not modeled yet.
     */
    declare public /*out*/ readonly raw: pulumi.Output<string>;
    /**
     * Datacenter region; valid list from `GET /baremetal-additional-ips/regions`. Defaults to `wjv-1`. Create-only, changing it replaces the IP.
     */
    declare public readonly region: pulumi.Output<string | undefined>;
    /**
     * Current status of the IP (e.g. Active, Pending, Suspended, Terminated).
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;

    /**
     * Create a BaremetalAdditionalIp resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BaremetalAdditionalIpArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.cycle === undefined && !opts.urn) {
                throw new Error("Missing required property 'cycle'");
            }
            if (args?.productId === undefined && !opts.urn) {
                throw new Error("Missing required property 'productId'");
            }
            resourceInputs["cycle"] = args?.cycle;
            resourceInputs["payWithCreditCard"] = (args?.payWithCreditCard) ?? true;
            resourceInputs["productId"] = args?.productId;
            resourceInputs["promocode"] = args?.promocode;
            resourceInputs["region"] = (args?.region) ?? "wjv-1";
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["ipAddress"] = undefined /*out*/;
            resourceInputs["raw"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        } else {
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["cycle"] = undefined /*out*/;
            resourceInputs["ipAddress"] = undefined /*out*/;
            resourceInputs["payWithCreditCard"] = undefined /*out*/;
            resourceInputs["productId"] = undefined /*out*/;
            resourceInputs["promocode"] = undefined /*out*/;
            resourceInputs["raw"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["raw"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(BaremetalAdditionalIp.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a BaremetalAdditionalIp resource.
 */
export interface BaremetalAdditionalIpArgs {
    /**
     * Billing cycle, e.g. `m` for monthly or `a` for annual.
     */
    cycle: pulumi.Input<string>;
    /**
     * Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
     */
    payWithCreditCard?: pulumi.Input<boolean | undefined>;
    /**
     * Product id from `GET /baremetal-additional-ips/products`.
     */
    productId: pulumi.Input<number>;
    /**
     * Promo code to apply at creation.
     */
    promocode?: pulumi.Input<string | undefined>;
    /**
     * Datacenter region; valid list from `GET /baremetal-additional-ips/regions`. Defaults to `wjv-1`. Create-only, changing it replaces the IP.
     */
    region?: pulumi.Input<string | undefined>;
}
