// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Baremetal extends pulumi.CustomResource {
    /**
     * Get an existing Baremetal resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Baremetal {
        return new Baremetal(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'biznetgio:index:Baremetal';

    /**
     * Returns true if the given object is an instance of Baremetal.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Baremetal {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Baremetal.__pulumiType;
    }

    /**
     * Creation timestamp (alias of created_at/date_created).
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Billing cycle, e.g. `m` for monthly or `a` for annual.
     */
    declare public readonly cycle: pulumi.Output<string>;
    /**
     * Public IP address of the server, when present.
     */
    declare public /*out*/ readonly ipAddress: pulumi.Output<string>;
    /**
     * Baremetal keypair id, from BaremetalKeypair. The baremetal keypair pool is separate from neolite/gpu.
     */
    declare public readonly keypairId: pulumi.Output<number>;
    /**
     * Display name of the server. The only field updatable in place.
     */
    declare public readonly label: pulumi.Output<string>;
    /**
     * Order id from the creation response.
     */
    declare public /*out*/ readonly orderId: pulumi.Output<string>;
    /**
     * Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
     */
    declare public readonly payWithCreditCard: pulumi.Output<boolean | undefined>;
    /**
     * Power state of the server: `on` or `off`. Only fires an API call when the value changes.
     */
    declare public readonly powerState: pulumi.Output<string | undefined>;
    /**
     * Product id from the baremetal products function.
     */
    declare public readonly productId: pulumi.Output<number>;
    /**
     * Promo code to apply at creation.
     */
    declare public readonly promocode: pulumi.Output<string | undefined>;
    /**
     * Number of public IPs to request (1 = with public IP). Defaults to 1. Create-only, changing it replaces the instance.
     */
    declare public readonly publicIp: pulumi.Output<number | undefined>;
    /**
     * Raw JSON of the last read response, for anything not modeled yet.
     */
    declare public /*out*/ readonly raw: pulumi.Output<string>;
    /**
     * Change this value to rebuild the instance (destructive, wipes the OS) via `PUT /baremetals/{account_id}/rebuild`. Valid OS list comes from the rebuildOsList function.
     */
    declare public readonly rebuildOs: pulumi.Output<string | undefined>;
    /**
     * Change this value to trigger a one-shot reset/reboot. The reset is an action, not a stable state.
     */
    declare public readonly resetTrigger: pulumi.Output<string | undefined>;
    /**
     * OS to install at creation, from `GET /baremetals/products/{product_id}/oss`. Defaults to `ubuntu-22`. Create-only, changing it replaces the instance.
     */
    declare public readonly selectOs: pulumi.Output<string | undefined>;
    /**
     * Current status of the server.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;

    /**
     * Create a Baremetal resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BaremetalArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.cycle === undefined && !opts.urn) {
                throw new Error("Missing required property 'cycle'");
            }
            if (args?.keypairId === undefined && !opts.urn) {
                throw new Error("Missing required property 'keypairId'");
            }
            if (args?.label === undefined && !opts.urn) {
                throw new Error("Missing required property 'label'");
            }
            if (args?.productId === undefined && !opts.urn) {
                throw new Error("Missing required property 'productId'");
            }
            resourceInputs["cycle"] = args?.cycle;
            resourceInputs["keypairId"] = args?.keypairId;
            resourceInputs["label"] = args?.label;
            resourceInputs["payWithCreditCard"] = (args?.payWithCreditCard) ?? true;
            resourceInputs["powerState"] = args?.powerState;
            resourceInputs["productId"] = args?.productId;
            resourceInputs["promocode"] = args?.promocode;
            resourceInputs["publicIp"] = (args?.publicIp) ?? 1;
            resourceInputs["rebuildOs"] = args?.rebuildOs;
            resourceInputs["resetTrigger"] = args?.resetTrigger;
            resourceInputs["selectOs"] = (args?.selectOs) ?? "ubuntu-22";
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["ipAddress"] = undefined /*out*/;
            resourceInputs["orderId"] = undefined /*out*/;
            resourceInputs["raw"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        } else {
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["cycle"] = undefined /*out*/;
            resourceInputs["ipAddress"] = undefined /*out*/;
            resourceInputs["keypairId"] = undefined /*out*/;
            resourceInputs["label"] = undefined /*out*/;
            resourceInputs["orderId"] = undefined /*out*/;
            resourceInputs["payWithCreditCard"] = undefined /*out*/;
            resourceInputs["powerState"] = undefined /*out*/;
            resourceInputs["productId"] = undefined /*out*/;
            resourceInputs["promocode"] = undefined /*out*/;
            resourceInputs["publicIp"] = undefined /*out*/;
            resourceInputs["raw"] = undefined /*out*/;
            resourceInputs["rebuildOs"] = undefined /*out*/;
            resourceInputs["resetTrigger"] = undefined /*out*/;
            resourceInputs["selectOs"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["raw"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        const replaceOnChanges = { replaceOnChanges: ["cycle", "keypairId", "payWithCreditCard", "productId", "promocode", "publicIp", "selectOs"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Baremetal.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Baremetal resource.
 */
export interface BaremetalArgs {
    /**
     * Billing cycle, e.g. `m` for monthly or `a` for annual.
     */
    cycle: pulumi.Input<string>;
    /**
     * Baremetal keypair id, from BaremetalKeypair. The baremetal keypair pool is separate from neolite/gpu.
     */
    keypairId: pulumi.Input<number>;
    /**
     * Display name of the server. The only field updatable in place.
     */
    label: pulumi.Input<string>;
    /**
     * Pay the invoice with the registered credit card. Defaults to true. Set false to leave the invoice unpaid in the portal; the resource stays Pending until paid.
     */
    payWithCreditCard?: pulumi.Input<boolean | undefined>;
    /**
     * Power state of the server: `on` or `off`. Only fires an API call when the value changes.
     */
    powerState?: pulumi.Input<string | undefined>;
    /**
     * Product id from the baremetal products function.
     */
    productId: pulumi.Input<number>;
    /**
     * Promo code to apply at creation.
     */
    promocode?: pulumi.Input<string | undefined>;
    /**
     * Number of public IPs to request (1 = with public IP). Defaults to 1. Create-only, changing it replaces the instance.
     */
    publicIp?: pulumi.Input<number | undefined>;
    /**
     * Change this value to rebuild the instance (destructive, wipes the OS) via `PUT /baremetals/{account_id}/rebuild`. Valid OS list comes from the rebuildOsList function.
     */
    rebuildOs?: pulumi.Input<string | undefined>;
    /**
     * Change this value to trigger a one-shot reset/reboot. The reset is an action, not a stable state.
     */
    resetTrigger?: pulumi.Input<string | undefined>;
    /**
     * OS to install at creation, from `GET /baremetals/products/{product_id}/oss`. Defaults to `ubuntu-22`. Create-only, changing it replaces the instance.
     */
    selectOs?: pulumi.Input<string | undefined>;
}
