// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function gpuConsole(args: GpuConsoleArgs, opts?: pulumi.InvokeOptions): Promise<GpuConsoleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("biznetgio:index:gpuConsole", {
        "accountId": args.accountId,
    }, opts);
}

export interface GpuConsoleArgs {
    /**
     * Account id of the GPU instance to get console access for.
     */
    accountId: string;
}

export interface GpuConsoleResult {
    /**
     * Raw JSON of the full response.
     */
    readonly raw: string;
    /**
     * Console access URL from `POST /neo-gpus/accounts/{account_id}/console-access`. Side-effecting: each call may mint a new one-time session, do not use inside plan diffing.
     */
    readonly url: string;
}
export function gpuConsoleOutput(args: GpuConsoleOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GpuConsoleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("biznetgio:index:gpuConsole", {
        "accountId": args.accountId,
    }, opts);
}

export interface GpuConsoleOutputArgs {
    /**
     * Account id of the GPU instance to get console access for.
     */
    accountId: pulumi.Input<string>;
}
// wip 847
// wip 895
