// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { BaremetalArgs } from "./baremetal";
export type Baremetal = import("./baremetal").Baremetal;
export const Baremetal: typeof import("./baremetal").Baremetal = null as any;
utilities.lazyLoad(exports, ["Baremetal"], () => require("./baremetal"));

export { BaremetalAdditionalIpArgs } from "./baremetalAdditionalIp";
export type BaremetalAdditionalIp = import("./baremetalAdditionalIp").BaremetalAdditionalIp;
export const BaremetalAdditionalIp: typeof import("./baremetalAdditionalIp").BaremetalAdditionalIp = null as any;
utilities.lazyLoad(exports, ["BaremetalAdditionalIp"], () => require("./baremetalAdditionalIp"));

export { BaremetalAdditionalIpAssignmentArgs } from "./baremetalAdditionalIpAssignment";
export type BaremetalAdditionalIpAssignment = import("./baremetalAdditionalIpAssignment").BaremetalAdditionalIpAssignment;
export const BaremetalAdditionalIpAssignment: typeof import("./baremetalAdditionalIpAssignment").BaremetalAdditionalIpAssignment = null as any;
utilities.lazyLoad(exports, ["BaremetalAdditionalIpAssignment"], () => require("./baremetalAdditionalIpAssignment"));

export { BaremetalElasticStorageArgs } from "./baremetalElasticStorage";
export type BaremetalElasticStorage = import("./baremetalElasticStorage").BaremetalElasticStorage;
export const BaremetalElasticStorage: typeof import("./baremetalElasticStorage").BaremetalElasticStorage = null as any;
utilities.lazyLoad(exports, ["BaremetalElasticStorage"], () => require("./baremetalElasticStorage"));

export { BaremetalKeypairArgs } from "./baremetalKeypair";
export type BaremetalKeypair = import("./baremetalKeypair").BaremetalKeypair;
export const BaremetalKeypair: typeof import("./baremetalKeypair").BaremetalKeypair = null as any;
utilities.lazyLoad(exports, ["BaremetalKeypair"], () => require("./baremetalKeypair"));

export { BaremetalOpenvpnArgs, BaremetalOpenvpnResult } from "./baremetalOpenvpn";
export const baremetalOpenvpn: typeof import("./baremetalOpenvpn").baremetalOpenvpn = null as any;
export const baremetalOpenvpnOutput: typeof import("./baremetalOpenvpn").baremetalOpenvpnOutput = null as any;
utilities.lazyLoad(exports, ["baremetalOpenvpn","baremetalOpenvpnOutput"], () => require("./baremetalOpenvpn"));

export { BaremetalProductsArgs, BaremetalProductsResult } from "./baremetalProducts";
export const baremetalProducts: typeof import("./baremetalProducts").baremetalProducts = null as any;
export const baremetalProductsOutput: typeof import("./baremetalProducts").baremetalProductsOutput = null as any;
utilities.lazyLoad(exports, ["baremetalProducts","baremetalProductsOutput"], () => require("./baremetalProducts"));

export { BaremetalRebuildOsListArgs, BaremetalRebuildOsListResult, BaremetalRebuildOsListOutputArgs } from "./baremetalRebuildOsList";
export const baremetalRebuildOsList: typeof import("./baremetalRebuildOsList").baremetalRebuildOsList = null as any;
export const baremetalRebuildOsListOutput: typeof import("./baremetalRebuildOsList").baremetalRebuildOsListOutput = null as any;
utilities.lazyLoad(exports, ["baremetalRebuildOsList","baremetalRebuildOsListOutput"], () => require("./baremetalRebuildOsList"));

export { GpuConsoleArgs, GpuConsoleResult, GpuConsoleOutputArgs } from "./gpuConsole";
export const gpuConsole: typeof import("./gpuConsole").gpuConsole = null as any;
export const gpuConsoleOutput: typeof import("./gpuConsole").gpuConsoleOutput = null as any;
utilities.lazyLoad(exports, ["gpuConsole","gpuConsoleOutput"], () => require("./gpuConsole"));

export { GpuGraphArgs, GpuGraphResult, GpuGraphOutputArgs } from "./gpuGraph";
export const gpuGraph: typeof import("./gpuGraph").gpuGraph = null as any;
export const gpuGraphOutput: typeof import("./gpuGraph").gpuGraphOutput = null as any;
utilities.lazyLoad(exports, ["gpuGraph","gpuGraphOutput"], () => require("./gpuGraph"));

export { GpuInstanceArgs } from "./gpuInstance";
export type GpuInstance = import("./gpuInstance").GpuInstance;
export const GpuInstance: typeof import("./gpuInstance").GpuInstance = null as any;
utilities.lazyLoad(exports, ["GpuInstance"], () => require("./gpuInstance"));

export { GpuKeypairArgs } from "./gpuKeypair";
export type GpuKeypair = import("./gpuKeypair").GpuKeypair;
export const GpuKeypair: typeof import("./gpuKeypair").GpuKeypair = null as any;
utilities.lazyLoad(exports, ["GpuKeypair"], () => require("./gpuKeypair"));

export { GpuProductsArgs, GpuProductsResult } from "./gpuProducts";
export const gpuProducts: typeof import("./gpuProducts").gpuProducts = null as any;
export const gpuProductsOutput: typeof import("./gpuProducts").gpuProductsOutput = null as any;
utilities.lazyLoad(exports, ["gpuProducts","gpuProductsOutput"], () => require("./gpuProducts"));

export { NeoliteChangePackageOptionsArgs, NeoliteChangePackageOptionsResult, NeoliteChangePackageOptionsOutputArgs } from "./neoliteChangePackageOptions";
export const neoliteChangePackageOptions: typeof import("./neoliteChangePackageOptions").neoliteChangePackageOptions = null as any;
export const neoliteChangePackageOptionsOutput: typeof import("./neoliteChangePackageOptions").neoliteChangePackageOptionsOutput = null as any;
utilities.lazyLoad(exports, ["neoliteChangePackageOptions","neoliteChangePackageOptionsOutput"], () => require("./neoliteChangePackageOptions"));

export { NeoliteDiskArgs } from "./neoliteDisk";
export type NeoliteDisk = import("./neoliteDisk").NeoliteDisk;
export const NeoliteDisk: typeof import("./neoliteDisk").NeoliteDisk = null as any;
utilities.lazyLoad(exports, ["NeoliteDisk"], () => require("./neoliteDisk"));

export { NeoliteIPAvailabilityArgs, NeoliteIPAvailabilityResult, NeoliteIPAvailabilityOutputArgs } from "./neoliteIPAvailability";
export const neoliteIPAvailability: typeof import("./neoliteIPAvailability").neoliteIPAvailability = null as any;
export const neoliteIPAvailabilityOutput: typeof import("./neoliteIPAvailability").neoliteIPAvailabilityOutput = null as any;
utilities.lazyLoad(exports, ["neoliteIPAvailability","neoliteIPAvailabilityOutput"], () => require("./neoliteIPAvailability"));

export { NeoliteKeypairArgs } from "./neoliteKeypair";
export type NeoliteKeypair = import("./neoliteKeypair").NeoliteKeypair;
export const NeoliteKeypair: typeof import("./neoliteKeypair").NeoliteKeypair = null as any;
utilities.lazyLoad(exports, ["NeoliteKeypair"], () => require("./neoliteKeypair"));

export { NeoliteOsListArgs, NeoliteOsListResult, NeoliteOsListOutputArgs } from "./neoliteOsList";
export const neoliteOsList: typeof import("./neoliteOsList").neoliteOsList = null as any;
export const neoliteOsListOutput: typeof import("./neoliteOsList").neoliteOsListOutput = null as any;
utilities.lazyLoad(exports, ["neoliteOsList","neoliteOsListOutput"], () => require("./neoliteOsList"));

export { NeoliteProChangePackageOptionsArgs, NeoliteProChangePackageOptionsResult, NeoliteProChangePackageOptionsOutputArgs } from "./neoliteProChangePackageOptions";
export const neoliteProChangePackageOptions: typeof import("./neoliteProChangePackageOptions").neoliteProChangePackageOptions = null as any;
export const neoliteProChangePackageOptionsOutput: typeof import("./neoliteProChangePackageOptions").neoliteProChangePackageOptionsOutput = null as any;
utilities.lazyLoad(exports, ["neoliteProChangePackageOptions","neoliteProChangePackageOptionsOutput"], () => require("./neoliteProChangePackageOptions"));

export { NeoliteProDiskArgs } from "./neoliteProDisk";
export type NeoliteProDisk = import("./neoliteProDisk").NeoliteProDisk;
export const NeoliteProDisk: typeof import("./neoliteProDisk").NeoliteProDisk = null as any;
utilities.lazyLoad(exports, ["NeoliteProDisk"], () => require("./neoliteProDisk"));

export { NeoliteProIPAvailabilityArgs, NeoliteProIPAvailabilityResult, NeoliteProIPAvailabilityOutputArgs } from "./neoliteProIPAvailability";
export const neoliteProIPAvailability: typeof import("./neoliteProIPAvailability").neoliteProIPAvailability = null as any;
export const neoliteProIPAvailabilityOutput: typeof import("./neoliteProIPAvailability").neoliteProIPAvailabilityOutput = null as any;
utilities.lazyLoad(exports, ["neoliteProIPAvailability","neoliteProIPAvailabilityOutput"], () => require("./neoliteProIPAvailability"));

export { NeoliteProKeypairArgs } from "./neoliteProKeypair";
export type NeoliteProKeypair = import("./neoliteProKeypair").NeoliteProKeypair;
export const NeoliteProKeypair: typeof import("./neoliteProKeypair").NeoliteProKeypair = null as any;
utilities.lazyLoad(exports, ["NeoliteProKeypair"], () => require("./neoliteProKeypair"));

export { NeoliteProOsListArgs, NeoliteProOsListResult, NeoliteProOsListOutputArgs } from "./neoliteProOsList";
export const neoliteProOsList: typeof import("./neoliteProOsList").neoliteProOsList = null as any;
export const neoliteProOsListOutput: typeof import("./neoliteProOsList").neoliteProOsListOutput = null as any;
utilities.lazyLoad(exports, ["neoliteProOsList","neoliteProOsListOutput"], () => require("./neoliteProOsList"));

export { NeoliteProProductsArgs, NeoliteProProductsResult } from "./neoliteProProducts";
export const neoliteProProducts: typeof import("./neoliteProProducts").neoliteProProducts = null as any;
export const neoliteProProductsOutput: typeof import("./neoliteProProducts").neoliteProProductsOutput = null as any;
utilities.lazyLoad(exports, ["neoliteProProducts","neoliteProProductsOutput"], () => require("./neoliteProProducts"));

export { NeoliteProSnapshotArgs } from "./neoliteProSnapshot";
export type NeoliteProSnapshot = import("./neoliteProSnapshot").NeoliteProSnapshot;
export const NeoliteProSnapshot: typeof import("./neoliteProSnapshot").NeoliteProSnapshot = null as any;
utilities.lazyLoad(exports, ["NeoliteProSnapshot"], () => require("./neoliteProSnapshot"));

export { NeoliteProStorageUpgradeOptionsArgs, NeoliteProStorageUpgradeOptionsResult, NeoliteProStorageUpgradeOptionsOutputArgs } from "./neoliteProStorageUpgradeOptions";
export const neoliteProStorageUpgradeOptions: typeof import("./neoliteProStorageUpgradeOptions").neoliteProStorageUpgradeOptions = null as any;
export const neoliteProStorageUpgradeOptionsOutput: typeof import("./neoliteProStorageUpgradeOptions").neoliteProStorageUpgradeOptionsOutput = null as any;
utilities.lazyLoad(exports, ["neoliteProStorageUpgradeOptions","neoliteProStorageUpgradeOptionsOutput"], () => require("./neoliteProStorageUpgradeOptions"));

export { NeoliteProVmArgs } from "./neoliteProVm";
export type NeoliteProVm = import("./neoliteProVm").NeoliteProVm;
export const NeoliteProVm: typeof import("./neoliteProVm").NeoliteProVm = null as any;
utilities.lazyLoad(exports, ["NeoliteProVm"], () => require("./neoliteProVm"));

export { NeoliteProductsArgs, NeoliteProductsResult } from "./neoliteProducts";
export const neoliteProducts: typeof import("./neoliteProducts").neoliteProducts = null as any;
export const neoliteProductsOutput: typeof import("./neoliteProducts").neoliteProductsOutput = null as any;
utilities.lazyLoad(exports, ["neoliteProducts","neoliteProductsOutput"], () => require("./neoliteProducts"));

export { NeoliteSnapshotArgs } from "./neoliteSnapshot";
export type NeoliteSnapshot = import("./neoliteSnapshot").NeoliteSnapshot;
export const NeoliteSnapshot: typeof import("./neoliteSnapshot").NeoliteSnapshot = null as any;
utilities.lazyLoad(exports, ["NeoliteSnapshot"], () => require("./neoliteSnapshot"));

export { NeoliteStorageUpgradeOptionsArgs, NeoliteStorageUpgradeOptionsResult, NeoliteStorageUpgradeOptionsOutputArgs } from "./neoliteStorageUpgradeOptions";
export const neoliteStorageUpgradeOptions: typeof import("./neoliteStorageUpgradeOptions").neoliteStorageUpgradeOptions = null as any;
export const neoliteStorageUpgradeOptionsOutput: typeof import("./neoliteStorageUpgradeOptions").neoliteStorageUpgradeOptionsOutput = null as any;
utilities.lazyLoad(exports, ["neoliteStorageUpgradeOptions","neoliteStorageUpgradeOptionsOutput"], () => require("./neoliteStorageUpgradeOptions"));

export { NeoliteVmArgs } from "./neoliteVm";
export type NeoliteVm = import("./neoliteVm").NeoliteVm;
export const NeoliteVm: typeof import("./neoliteVm").NeoliteVm = null as any;
utilities.lazyLoad(exports, ["NeoliteVm"], () => require("./neoliteVm"));

export { NeoliteVmFromSnapshotArgs } from "./neoliteVmFromSnapshot";
export type NeoliteVmFromSnapshot = import("./neoliteVmFromSnapshot").NeoliteVmFromSnapshot;
export const NeoliteVmFromSnapshot: typeof import("./neoliteVmFromSnapshot").NeoliteVmFromSnapshot = null as any;
utilities.lazyLoad(exports, ["NeoliteVmFromSnapshot"], () => require("./neoliteVmFromSnapshot"));

export { ObjectStorageArgs } from "./objectStorage";
export type ObjectStorage = import("./objectStorage").ObjectStorage;
export const ObjectStorage: typeof import("./objectStorage").ObjectStorage = null as any;
utilities.lazyLoad(exports, ["ObjectStorage"], () => require("./objectStorage"));

export { ObjectStorageBucketArgs } from "./objectStorageBucket";
export type ObjectStorageBucket = import("./objectStorageBucket").ObjectStorageBucket;
export const ObjectStorageBucket: typeof import("./objectStorageBucket").ObjectStorageBucket = null as any;
utilities.lazyLoad(exports, ["ObjectStorageBucket"], () => require("./objectStorageBucket"));

export { ObjectStorageBucketsArgs, ObjectStorageBucketsResult, ObjectStorageBucketsOutputArgs } from "./objectStorageBuckets";
export const objectStorageBuckets: typeof import("./objectStorageBuckets").objectStorageBuckets = null as any;
export const objectStorageBucketsOutput: typeof import("./objectStorageBuckets").objectStorageBucketsOutput = null as any;
utilities.lazyLoad(exports, ["objectStorageBuckets","objectStorageBucketsOutput"], () => require("./objectStorageBuckets"));

export { ObjectStorageCredentialArgs } from "./objectStorageCredential";
export type ObjectStorageCredential = import("./objectStorageCredential").ObjectStorageCredential;
export const ObjectStorageCredential: typeof import("./objectStorageCredential").ObjectStorageCredential = null as any;
utilities.lazyLoad(exports, ["ObjectStorageCredential"], () => require("./objectStorageCredential"));

export { ObjectStorageCredentialsArgs, ObjectStorageCredentialsResult, ObjectStorageCredentialsOutputArgs } from "./objectStorageCredentials";
export const objectStorageCredentials: typeof import("./objectStorageCredentials").objectStorageCredentials = null as any;
export const objectStorageCredentialsOutput: typeof import("./objectStorageCredentials").objectStorageCredentialsOutput = null as any;
utilities.lazyLoad(exports, ["objectStorageCredentials","objectStorageCredentialsOutput"], () => require("./objectStorageCredentials"));

export { ObjectStorageInstancesArgs, ObjectStorageInstancesResult, ObjectStorageInstancesOutputArgs } from "./objectStorageInstances";
export const objectStorageInstances: typeof import("./objectStorageInstances").objectStorageInstances = null as any;
export const objectStorageInstancesOutput: typeof import("./objectStorageInstances").objectStorageInstancesOutput = null as any;
utilities.lazyLoad(exports, ["objectStorageInstances","objectStorageInstancesOutput"], () => require("./objectStorageInstances"));

export { ObjectStorageObjectArgs } from "./objectStorageObject";
export type ObjectStorageObject = import("./objectStorageObject").ObjectStorageObject;
export const ObjectStorageObject: typeof import("./objectStorageObject").ObjectStorageObject = null as any;
utilities.lazyLoad(exports, ["ObjectStorageObject"], () => require("./objectStorageObject"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "biznetgio:index:Baremetal":
                return new Baremetal(name, <any>undefined, { urn })
            case "biznetgio:index:BaremetalAdditionalIp":
                return new BaremetalAdditionalIp(name, <any>undefined, { urn })
            case "biznetgio:index:BaremetalAdditionalIpAssignment":
                return new BaremetalAdditionalIpAssignment(name, <any>undefined, { urn })
            case "biznetgio:index:BaremetalElasticStorage":
                return new BaremetalElasticStorage(name, <any>undefined, { urn })
            case "biznetgio:index:BaremetalKeypair":
                return new BaremetalKeypair(name, <any>undefined, { urn })
            case "biznetgio:index:GpuInstance":
                return new GpuInstance(name, <any>undefined, { urn })
            case "biznetgio:index:GpuKeypair":
                return new GpuKeypair(name, <any>undefined, { urn })
            case "biznetgio:index:NeoliteDisk":
                return new NeoliteDisk(name, <any>undefined, { urn })
            case "biznetgio:index:NeoliteKeypair":
                return new NeoliteKeypair(name, <any>undefined, { urn })
            case "biznetgio:index:NeoliteProDisk":
                return new NeoliteProDisk(name, <any>undefined, { urn })
            case "biznetgio:index:NeoliteProKeypair":
                return new NeoliteProKeypair(name, <any>undefined, { urn })
            case "biznetgio:index:NeoliteProSnapshot":
                return new NeoliteProSnapshot(name, <any>undefined, { urn })
            case "biznetgio:index:NeoliteProVm":
                return new NeoliteProVm(name, <any>undefined, { urn })
            case "biznetgio:index:NeoliteSnapshot":
                return new NeoliteSnapshot(name, <any>undefined, { urn })
            case "biznetgio:index:NeoliteVm":
                return new NeoliteVm(name, <any>undefined, { urn })
            case "biznetgio:index:NeoliteVmFromSnapshot":
                return new NeoliteVmFromSnapshot(name, <any>undefined, { urn })
            case "biznetgio:index:ObjectStorage":
                return new ObjectStorage(name, <any>undefined, { urn })
            case "biznetgio:index:ObjectStorageBucket":
                return new ObjectStorageBucket(name, <any>undefined, { urn })
            case "biznetgio:index:ObjectStorageCredential":
                return new ObjectStorageCredential(name, <any>undefined, { urn })
            case "biznetgio:index:ObjectStorageObject":
                return new ObjectStorageObject(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("biznetgio", "index", _module)
pulumi.runtime.registerResourcePackage("biznetgio", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:biznetgio") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
