// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function neoliteStorageUpgradeOptions(args: NeoliteStorageUpgradeOptionsArgs, opts?: pulumi.InvokeOptions): Promise<NeoliteStorageUpgradeOptionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("biznetgio:index:neoliteStorageUpgradeOptions", {
        "accountId": args.accountId,
    }, opts);
}

export interface NeoliteStorageUpgradeOptionsArgs {
    /**
     * Account id of the NEO Lite VM.
     */
    accountId: number;
}

export interface NeoliteStorageUpgradeOptionsResult {
    readonly raw: string;
}
export function neoliteStorageUpgradeOptionsOutput(args: NeoliteStorageUpgradeOptionsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<NeoliteStorageUpgradeOptionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("biznetgio:index:neoliteStorageUpgradeOptions", {
        "accountId": args.accountId,
    }, opts);
}

export interface NeoliteStorageUpgradeOptionsOutputArgs {
    /**
     * Account id of the NEO Lite VM.
     */
    accountId: pulumi.Input<number>;
}
