// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class NeoliteVm extends pulumi.CustomResource {
    /**
     * Get an existing NeoliteVm resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): NeoliteVm {
        return new NeoliteVm(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'biznetgio:index:NeoliteVm';

    /**
     * Returns true if the given object is an instance of NeoliteVm.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NeoliteVm {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NeoliteVm.__pulumiType;
    }

    /**
     * Siklus billing aktif.
     */
    declare public /*out*/ readonly billingcycle: pulumi.Output<string>;
    /**
     * Cloud-init password VM (sensitive).
     */
    declare public /*out*/ readonly ciPassword: pulumi.Output<string>;
    /**
     * Cloud-init user VM.
     */
    declare public /*out*/ readonly ciUser: pulumi.Output<string>;
    /**
     * Password console saat create. Write-only: ga pernah di-refetch dari API.
     */
    declare public readonly consolePassword: pulumi.Output<string>;
    /**
     * Jumlah CPU VM.
     */
    declare public /*out*/ readonly cpus: pulumi.Output<number>;
    /**
     * Siklus billing: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
     */
    declare public readonly cycle: pulumi.Output<string>;
    /**
     * Deskripsi VM.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Ukuran disk target (GB, absolute — bukan tambahan). Cuma bisa naik, bukan turun.
     */
    declare public readonly diskSize: pulumi.Output<number | undefined>;
    /**
     * Id keypair dari `NeoliteKeypair`. Bisa diganti via change-keypair.
     */
    declare public readonly keypairId: pulumi.Output<number>;
    /**
     * Invoice terakhir VM.
     */
    declare public /*out*/ readonly lastInvoice: pulumi.Output<outputs.NeoliteLastInvoice>;
    /**
     * Ukuran disk maksimal VM (GB).
     */
    declare public /*out*/ readonly maxDisk: pulumi.Output<number>;
    /**
     * Memory maksimal VM (MB).
     */
    declare public /*out*/ readonly maxMem: pulumi.Output<number>;
    /**
     * Memory yang dipakai VM (MB).
     */
    declare public /*out*/ readonly mem: pulumi.Output<number>;
    /**
     * Trigger one-shot migrate ke NEO Lite Pro: isi neolitepro_product_id target. Ganti nilainya buat re-trigger.
     */
    declare public readonly migrateToPro: pulumi.Output<string | undefined>;
    /**
     * Tanggal tagihan berikutnya.
     */
    declare public /*out*/ readonly nextDue: pulumi.Output<string>;
    /**
     * Order id dari response create.
     */
    declare public /*out*/ readonly orderId: pulumi.Output<string>;
    /**
     * Nama OS yang jalan di VM.
     */
    declare public /*out*/ readonly osName: pulumi.Output<string>;
    /**
     * Bayar invoice pake kartu kredit saat order. Default true (auto-charge). Set false kalau mau ninggalin invoice unpaid di portal — resource bakal stuck Pending sampai dibayar.
     */
    declare public readonly payWithCreditCard: pulumi.Output<boolean | undefined>;
    /**
     * Power state VM: start, stop, suspend, resume, atau shutdown. Update cuma mengirim action kalau nilainya berubah.
     */
    declare public readonly powerState: pulumi.Output<string | undefined>;
    /**
     * Product id dari function `getProducts` atau portal.
     */
    declare public readonly productId: pulumi.Output<number>;
    /**
     * Nama product aktif.
     */
    declare public /*out*/ readonly productName: pulumi.Output<string>;
    /**
     * Kode promo saat order.
     */
    declare public readonly promocode: pulumi.Output<string | undefined>;
    /**
     * Full JSON response akun terakhir dari API, buat akses field yang belum dimodel (cipassword di-mask).
     */
    declare public /*out*/ readonly raw: pulumi.Output<string>;
    /**
     * Kalau berubah, VM di-rebuild (wipe OS) pake OS baru via endpoint rebuild. List OS valid ada di function `getOsList`.
     */
    declare public readonly rebuildOs: pulumi.Output<string | undefined>;
    /**
     * Nominal recurring per siklus.
     */
    declare public /*out*/ readonly recurringAmount: pulumi.Output<number>;
    /**
     * Region VM.
     */
    declare public /*out*/ readonly region: pulumi.Output<string>;
    /**
     * Label region VM.
     */
    declare public /*out*/ readonly regionLabel: pulumi.Output<string>;
    /**
     * OS yang dipasang saat create, dari function `getOsList`. Ganti OS = pakai `rebuildOs`.
     */
    declare public readonly selectOs: pulumi.Output<string>;
    /**
     * User SSH & console yang dipasang saat create.
     */
    declare public readonly sshAndConsoleUser: pulumi.Output<string>;
    /**
     * Status akun terakhir dari API (Active, Pending, Suspended, Terminated).
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * Uptime VM dalam detik.
     */
    declare public /*out*/ readonly uptime: pulumi.Output<number>;
    /**
     * Nama VM. Default `server-name`. Bisa diubah via change-vm-name.
     */
    declare public readonly vmName: pulumi.Output<string | undefined>;

    /**
     * Create a NeoliteVm resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NeoliteVmArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.consolePassword === undefined && !opts.urn) {
                throw new Error("Missing required property 'consolePassword'");
            }
            if (args?.cycle === undefined && !opts.urn) {
                throw new Error("Missing required property 'cycle'");
            }
            if (args?.keypairId === undefined && !opts.urn) {
                throw new Error("Missing required property 'keypairId'");
            }
            if (args?.productId === undefined && !opts.urn) {
                throw new Error("Missing required property 'productId'");
            }
            if (args?.selectOs === undefined && !opts.urn) {
                throw new Error("Missing required property 'selectOs'");
            }
            if (args?.sshAndConsoleUser === undefined && !opts.urn) {
                throw new Error("Missing required property 'sshAndConsoleUser'");
            }
            resourceInputs["consolePassword"] = args?.consolePassword ? pulumi.secret(args.consolePassword) : undefined;
            resourceInputs["cycle"] = args?.cycle;
            resourceInputs["description"] = (args?.description) ?? "";
            resourceInputs["diskSize"] = args?.diskSize;
            resourceInputs["keypairId"] = args?.keypairId;
            resourceInputs["migrateToPro"] = args?.migrateToPro;
            resourceInputs["payWithCreditCard"] = (args?.payWithCreditCard) ?? true;
            resourceInputs["powerState"] = args?.powerState;
            resourceInputs["productId"] = args?.productId;
            resourceInputs["promocode"] = (args?.promocode) ?? "";
            resourceInputs["rebuildOs"] = args?.rebuildOs;
            resourceInputs["selectOs"] = args?.selectOs;
            resourceInputs["sshAndConsoleUser"] = args?.sshAndConsoleUser;
            resourceInputs["vmName"] = (args?.vmName) ?? "server-name";
            resourceInputs["billingcycle"] = undefined /*out*/;
            resourceInputs["ciPassword"] = undefined /*out*/;
            resourceInputs["ciUser"] = undefined /*out*/;
            resourceInputs["cpus"] = undefined /*out*/;
            resourceInputs["lastInvoice"] = undefined /*out*/;
            resourceInputs["maxDisk"] = undefined /*out*/;
            resourceInputs["maxMem"] = undefined /*out*/;
            resourceInputs["mem"] = undefined /*out*/;
            resourceInputs["nextDue"] = undefined /*out*/;
            resourceInputs["orderId"] = undefined /*out*/;
            resourceInputs["osName"] = undefined /*out*/;
            resourceInputs["productName"] = undefined /*out*/;
            resourceInputs["raw"] = undefined /*out*/;
            resourceInputs["recurringAmount"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["regionLabel"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["uptime"] = undefined /*out*/;
        } else {
            resourceInputs["billingcycle"] = undefined /*out*/;
            resourceInputs["ciPassword"] = undefined /*out*/;
            resourceInputs["ciUser"] = undefined /*out*/;
            resourceInputs["consolePassword"] = undefined /*out*/;
            resourceInputs["cpus"] = undefined /*out*/;
            resourceInputs["cycle"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["diskSize"] = undefined /*out*/;
            resourceInputs["keypairId"] = undefined /*out*/;
            resourceInputs["lastInvoice"] = undefined /*out*/;
            resourceInputs["maxDisk"] = undefined /*out*/;
            resourceInputs["maxMem"] = undefined /*out*/;
            resourceInputs["mem"] = undefined /*out*/;
            resourceInputs["migrateToPro"] = undefined /*out*/;
            resourceInputs["nextDue"] = undefined /*out*/;
            resourceInputs["orderId"] = undefined /*out*/;
            resourceInputs["osName"] = undefined /*out*/;
            resourceInputs["payWithCreditCard"] = undefined /*out*/;
            resourceInputs["powerState"] = undefined /*out*/;
            resourceInputs["productId"] = undefined /*out*/;
            resourceInputs["productName"] = undefined /*out*/;
            resourceInputs["promocode"] = undefined /*out*/;
            resourceInputs["raw"] = undefined /*out*/;
            resourceInputs["rebuildOs"] = undefined /*out*/;
            resourceInputs["recurringAmount"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["regionLabel"] = undefined /*out*/;
            resourceInputs["selectOs"] = undefined /*out*/;
            resourceInputs["sshAndConsoleUser"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["uptime"] = undefined /*out*/;
            resourceInputs["vmName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["ciPassword", "consolePassword", "raw"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(NeoliteVm.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a NeoliteVm resource.
 */
export interface NeoliteVmArgs {
    /**
     * Password console saat create. Write-only: ga pernah di-refetch dari API.
     */
    consolePassword: pulumi.Input<string>;
    /**
     * Siklus billing: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
     */
    cycle: pulumi.Input<string>;
    /**
     * Deskripsi VM.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Ukuran disk target (GB, absolute — bukan tambahan). Cuma bisa naik, bukan turun.
     */
    diskSize?: pulumi.Input<number | undefined>;
    /**
     * Id keypair dari `NeoliteKeypair`. Bisa diganti via change-keypair.
     */
    keypairId: pulumi.Input<number>;
    /**
     * Trigger one-shot migrate ke NEO Lite Pro: isi neolitepro_product_id target. Ganti nilainya buat re-trigger.
     */
    migrateToPro?: pulumi.Input<string | undefined>;
    /**
     * Bayar invoice pake kartu kredit saat order. Default true (auto-charge). Set false kalau mau ninggalin invoice unpaid di portal — resource bakal stuck Pending sampai dibayar.
     */
    payWithCreditCard?: pulumi.Input<boolean | undefined>;
    /**
     * Power state VM: start, stop, suspend, resume, atau shutdown. Update cuma mengirim action kalau nilainya berubah.
     */
    powerState?: pulumi.Input<string | undefined>;
    /**
     * Product id dari function `getProducts` atau portal.
     */
    productId: pulumi.Input<number>;
    /**
     * Kode promo saat order.
     */
    promocode?: pulumi.Input<string | undefined>;
    /**
     * Kalau berubah, VM di-rebuild (wipe OS) pake OS baru via endpoint rebuild. List OS valid ada di function `getOsList`.
     */
    rebuildOs?: pulumi.Input<string | undefined>;
    /**
     * OS yang dipasang saat create, dari function `getOsList`. Ganti OS = pakai `rebuildOs`.
     */
    selectOs: pulumi.Input<string>;
    /**
     * User SSH & console yang dipasang saat create.
     */
    sshAndConsoleUser: pulumi.Input<string>;
    /**
     * Nama VM. Default `server-name`. Bisa diubah via change-vm-name.
     */
    vmName?: pulumi.Input<string | undefined>;
}
