// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class NeoliteProDisk extends pulumi.CustomResource {
    /**
     * Get an existing NeoliteProDisk resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): NeoliteProDisk {
        return new NeoliteProDisk(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'biznetgio:index:NeoliteProDisk';

    /**
     * Returns true if the given object is an instance of NeoliteProDisk.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NeoliteProDisk {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NeoliteProDisk.__pulumiType;
    }

    /**
     * Siklus billing: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
     */
    declare public readonly cycle: pulumi.Output<string>;
    /**
     * Account id VM NEO Lite Pro tempat disk dipasang.
     */
    declare public readonly neoliteAccountId: pulumi.Output<number>;
    /**
     * Order id dari response create.
     */
    declare public /*out*/ readonly orderId: pulumi.Output<string>;
    /**
     * Bayar invoice pake kartu kredit saat order. Default true (auto-charge). Set false kalau mau ninggalin invoice unpaid di portal — resource bakal stuck Pending sampai dibayar.
     */
    declare public readonly payWithCreditCard: pulumi.Output<boolean | undefined>;
    /**
     * Product id disk dari endpoint `/neolite-pros/disks/products`.
     */
    declare public readonly productId: pulumi.Output<number>;
    /**
     * Kode promo saat order.
     */
    declare public readonly promocode: pulumi.Output<string | undefined>;
    /**
     * Full JSON response disk terakhir dari API, buat akses field yang belum dimodel.
     */
    declare public /*out*/ readonly raw: pulumi.Output<string>;
    /**
     * Nama layanan disk. Default `service-name`.
     */
    declare public readonly serviceName: pulumi.Output<string | undefined>;
    /**
     * Ukuran disk (GB). Default 30 (minimal product disk pro). Cuma bisa naik, bukan turun.
     */
    declare public readonly size: pulumi.Output<number | undefined>;
    /**
     * Status disk (Active, Pending, Suspended, Terminated).
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;

    /**
     * Create a NeoliteProDisk resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NeoliteProDiskArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.cycle === undefined && !opts.urn) {
                throw new Error("Missing required property 'cycle'");
            }
            if (args?.neoliteAccountId === undefined && !opts.urn) {
                throw new Error("Missing required property 'neoliteAccountId'");
            }
            if (args?.productId === undefined && !opts.urn) {
                throw new Error("Missing required property 'productId'");
            }
            resourceInputs["cycle"] = args?.cycle;
            resourceInputs["neoliteAccountId"] = args?.neoliteAccountId;
            resourceInputs["payWithCreditCard"] = (args?.payWithCreditCard) ?? true;
            resourceInputs["productId"] = args?.productId;
            resourceInputs["promocode"] = (args?.promocode) ?? "";
            resourceInputs["serviceName"] = (args?.serviceName) ?? "service-name";
            resourceInputs["size"] = (args?.size) ?? 30;
            resourceInputs["orderId"] = undefined /*out*/;
            resourceInputs["raw"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        } else {
            resourceInputs["cycle"] = undefined /*out*/;
            resourceInputs["neoliteAccountId"] = undefined /*out*/;
            resourceInputs["orderId"] = undefined /*out*/;
            resourceInputs["payWithCreditCard"] = undefined /*out*/;
            resourceInputs["productId"] = undefined /*out*/;
            resourceInputs["promocode"] = undefined /*out*/;
            resourceInputs["raw"] = undefined /*out*/;
            resourceInputs["serviceName"] = undefined /*out*/;
            resourceInputs["size"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["raw"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(NeoliteProDisk.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a NeoliteProDisk resource.
 */
export interface NeoliteProDiskArgs {
    /**
     * Siklus billing: m monthly, a annual, q quarterly, s semiannual, b biennial, t triennial, p4, p5.
     */
    cycle: pulumi.Input<string>;
    /**
     * Account id VM NEO Lite Pro tempat disk dipasang.
     */
    neoliteAccountId: pulumi.Input<number>;
    /**
     * Bayar invoice pake kartu kredit saat order. Default true (auto-charge). Set false kalau mau ninggalin invoice unpaid di portal — resource bakal stuck Pending sampai dibayar.
     */
    payWithCreditCard?: pulumi.Input<boolean | undefined>;
    /**
     * Product id disk dari endpoint `/neolite-pros/disks/products`.
     */
    productId: pulumi.Input<number>;
    /**
     * Kode promo saat order.
     */
    promocode?: pulumi.Input<string | undefined>;
    /**
     * Nama layanan disk. Default `service-name`.
     */
    serviceName?: pulumi.Input<string | undefined>;
    /**
     * Ukuran disk (GB). Default 30 (minimal product disk pro). Cuma bisa naik, bukan turun.
     */
    size?: pulumi.Input<number | undefined>;
}
