// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function neoliteOsList(args: NeoliteOsListArgs, opts?: pulumi.InvokeOptions): Promise<NeoliteOsListResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("biznetgio:index:neoliteOsList", {
        "productId": args.productId,
    }, opts);
}

export interface NeoliteOsListArgs {
    /**
     * Product id NEO Lite.
     */
    productId: number;
}

export interface NeoliteOsListResult {
    readonly oss: outputs.NeoliteOsItem[];
}
export function neoliteOsListOutput(args: NeoliteOsListOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<NeoliteOsListResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("biznetgio:index:neoliteOsList", {
        "productId": args.productId,
    }, opts);
}

export interface NeoliteOsListOutputArgs {
    /**
     * Product id NEO Lite.
     */
    productId: pulumi.Input<number>;
}
// wip 510
