// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function neoliteProIPAvailability(args: NeoliteProIPAvailabilityArgs, opts?: pulumi.InvokeOptions): Promise<NeoliteProIPAvailabilityResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("biznetgio:index:neoliteProIPAvailability", {
        "productId": args.productId,
    }, opts);
}

export interface NeoliteProIPAvailabilityArgs {
    /**
     * Product id NEO Lite Pro.
     */
    productId: number;
}

export interface NeoliteProIPAvailabilityResult {
    readonly available: boolean;
}
export function neoliteProIPAvailabilityOutput(args: NeoliteProIPAvailabilityOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<NeoliteProIPAvailabilityResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("biznetgio:index:neoliteProIPAvailability", {
        "productId": args.productId,
    }, opts);
}

export interface NeoliteProIPAvailabilityOutputArgs {
    /**
     * Product id NEO Lite Pro.
     */
    productId: pulumi.Input<number>;
}
