// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ObjectStorageObject extends pulumi.CustomResource {
    /**
     * Get an existing ObjectStorageObject resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ObjectStorageObject {
        return new ObjectStorageObject(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'biznetgio:index:ObjectStorageObject';

    /**
     * Returns true if the given object is an instance of ObjectStorageObject.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ObjectStorageObject {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ObjectStorageObject.__pulumiType;
    }

    /**
     * Object storage instance account id. Create-only.
     */
    declare public readonly accountId: pulumi.Output<string>;
    /**
     * S3-style canned ACL applied to the object. Defaults to empty.
     */
    declare public readonly acl: pulumi.Output<string | undefined>;
    /**
     * Bucket name. Create-only.
     */
    declare public readonly bucket: pulumi.Output<string>;
    /**
     * Inline content to upload. Exactly one of `source`/`content` required.
     */
    declare public readonly content: pulumi.Output<string | undefined>;
    /**
     * Object key inside the bucket. Create-only.
     */
    declare public readonly key: pulumi.Output<string>;
    /**
     * Raw JSON of the last read response, for anything not modeled yet.
     */
    declare public /*out*/ readonly raw: pulumi.Output<string>;
    /**
     * Path to the local file to upload. Exactly one of `source`/`content` required.
     */
    declare public readonly source: pulumi.Output<string | undefined>;

    /**
     * Create a ObjectStorageObject resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ObjectStorageObjectArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.accountId === undefined && !opts.urn) {
                throw new Error("Missing required property 'accountId'");
            }
            if (args?.bucket === undefined && !opts.urn) {
                throw new Error("Missing required property 'bucket'");
            }
            if (args?.key === undefined && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            resourceInputs["accountId"] = args?.accountId;
            resourceInputs["acl"] = (args?.acl) ?? "";
            resourceInputs["bucket"] = args?.bucket;
            resourceInputs["content"] = args?.content ? pulumi.secret(args.content) : undefined;
            resourceInputs["key"] = args?.key;
            resourceInputs["source"] = args?.source;
            resourceInputs["raw"] = undefined /*out*/;
        } else {
            resourceInputs["accountId"] = undefined /*out*/;
            resourceInputs["acl"] = undefined /*out*/;
            resourceInputs["bucket"] = undefined /*out*/;
            resourceInputs["content"] = undefined /*out*/;
            resourceInputs["key"] = undefined /*out*/;
            resourceInputs["raw"] = undefined /*out*/;
            resourceInputs["source"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["content", "raw"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        const replaceOnChanges = { replaceOnChanges: ["accountId", "bucket", "content", "key", "source"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(ObjectStorageObject.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ObjectStorageObject resource.
 */
export interface ObjectStorageObjectArgs {
    /**
     * Object storage instance account id. Create-only.
     */
    accountId: pulumi.Input<string>;
    /**
     * S3-style canned ACL applied to the object. Defaults to empty.
     */
    acl?: pulumi.Input<string | undefined>;
    /**
     * Bucket name. Create-only.
     */
    bucket: pulumi.Input<string>;
    /**
     * Inline content to upload. Exactly one of `source`/`content` required.
     */
    content?: pulumi.Input<string | undefined>;
    /**
     * Object key inside the bucket. Create-only.
     */
    key: pulumi.Input<string>;
    /**
     * Path to the local file to upload. Exactly one of `source`/`content` required.
     */
    source?: pulumi.Input<string | undefined>;
}
