// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'biznetgio';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * BiznetGIO API token (x-token header). Falls back to BIZNETGIO_API_KEY.
     */
    declare public readonly apiToken: pulumi.Output<string | undefined>;
    /**
     * BiznetGIO API base URL. Falls back to BIZNETGIO_BASE_URL.
     */
    declare public readonly baseUrl: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["apiToken"] = (args?.apiToken ? pulumi.secret(args.apiToken) : undefined) ?? utilities.getEnv("BIZNETGIO_API_KEY");
            resourceInputs["baseUrl"] = (args?.baseUrl) ?? (utilities.getEnv("BIZNETGIO_BASE_URL") || "https://api.portal.biznetgio.com/v1");
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiToken"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * BiznetGIO API token (x-token header). Falls back to BIZNETGIO_API_KEY.
     */
    apiToken?: pulumi.Input<string | undefined>;
    /**
     * BiznetGIO API base URL. Falls back to BIZNETGIO_BASE_URL.
     */
    baseUrl?: pulumi.Input<string | undefined>;
}
